- galaxy_ng/app/api/ui/viewsets/namespace.py
Fixing issue with Namespace creation:
Request:
```
Request URL:https://ci.foo.redhat.com:1337/api/automation-hub/v3/_ui/namespaces/
Request Method:POST
{"JSON":{"groups":["6269497","system:partner-engineers"],"name":"rblanco"}}
```
Response:
```
{"groups":"Provided identifications are not numbers"}
```
> Updated namespace viewset to match changes in galaxy-api/pull/155

- galaxy_ng/app/api/v3/viewsets.py
- galaxy_ng/app/common/parsers.py
(port of fix for galaxy-api)
In ansible-galaxy versions 2.9, the body of the multipart/form
POST'ed as part of the 'publish' command causes the default
django/drf multipart/form parsers to ignore the 'sha256' content.
When the parser ignores it, the sha256 value is None, which
the galaxy-api publish code considers an optional value.
So when the publish / import is passed to pulp api via
galaxy_pulp, the pulp side doesn't check that the artifacts
sha256sum matches the 'sha256' value (since it is None).
This adds a custom parser that subclasses the drf 'MultiPartParser'
but does some pre-processing on the request body stream to
correct it before it is sent to the base MultiPartParser.
Fixes ansible/galaxy-dev#246
> Handle the multipart/form bodies sent from ansible2.9

- dev/automation-hub/galaxy_ng.env
- dev/common/galaxy_ng.env
- dev/docker-compose.yml
- galaxy_ng/app/api/v3/viewsets.py
- galaxy_ng/app/settings.py
* Use CONTENT_PATH_PREFIX setting from pulpcore to
build content app URL.
* Fix missing X_PULP_CONTENT_HOST setting for development
environment.
> fix: Malformed content app URL

- openapi/openapi.yaml
Actual implementation of 'POST
/api/automation-hub/artifacts/collections'
doesn't enforce it, so update spec.
Fixes: ansible/galaxy-dev#290
> Fix openapi so 'sha256' field for is not required.

- dev/automation-hub/galaxy_ng.env
When following along with https://pulp-ansible.readthedocs.io/en/latest/workflows/collections.html, I hit a few bugs that required these variables to be set.
> Fix pulp content url in dev env

- docker/bin/wait-for-migrations
Increase timeout in `wait-for-migrations` script from 10 to 60 seconds
to prevent possible failure doe to timeout on low CPU limits.
> Increase timeout for migrations

- galaxy_ng/app/settings.py
- galaxy_ng/app/urls.py
* Enable django_prometheus middlewares.
* Add `/metrics` URL.
Issue: #10
> Configure prometheus metrics for django app

- docker/bin/start-api
Add `GUNICORN_FORWARDED_ALLOW_IPS` parameter to `docker/bin/start-api`
script to add configurable option `--forwarded-allow-ips` for gunicorn.
By default gunicorn strips all `X-Forwarded-*` headers unless this
options is specified. It is useful whenever gunicorn is run
behind a reverse proxy not on the same host.
This is typical for OpenShift deployment environment.
> build: Add parameter to start-api container script

- setup.py
Change introduced in #78 causes failure during installation
due to insonsistent dependency resolution. Adding explicit
django dependency with a version restriction.
> Fix dependency resolution when installing project

- setup.py
* Add pulpcore maximum version restriction to fix conflict with
pulp-ansible.
* Update minimal pulp-ansible required version to 0.2.0b11.
> Fix dependency conflicts

- compose
- dev/docker-compose.yml
- docker/entrypoint.sh
Adds possibility to run project dependencies from local
filesystem in editable mode. This patch changes directory being
mounted to containers from project directory to its parent directory.
By setting `DEV_SOURCE_PATH` environment variable it is possible to
include additional projects to be installed in editable mode.
Project directory path is relative to galaxy_ng parent directory and
separated by colon `:`. Default `DEV_SOURCE_PATH=galaxy_ng`
Example:
$ export DEV_SOURCE_PATH='galaxy_ng:galaxy-importer'
$ ./compose up
> Multiple development projects

- dev/docker-compose.yml
`"DEV_SOURCE_PATH=${DEV_SOURCE_PATH}"` is needed in the worker container for galaxy-importer to work per the wiki [additional-development-dependencies](https://github.com/ansible/galaxy_ng/wiki/Automation-Hub-SaaS-Development/_edit#additional-development-dependencies) instructions, this PR adds to the other pulp containers as I assume they would be needed for pulp-ansible
> Allow all pulp containers to get dev installs

- Dockerfile
- ansible.cfg
Error occurs in openshift env, a permission error on creating the tmp dir
> Add ansible tmp dir to fix running ansible-doc in importer

- .travis.yml
This will make sure the dependencies necessary to build the PyPI wheel are installed before the deploy is run.
> Move PyPI deploy to end of travis test stage.

- galaxy_ng/__init__.py
4.2.0a4 was missing some UI updates, so I'm pushing a new release to include https://github.com/ansible/ansible-hub-ui/releases/tag/4.2.0a3
> Bump version for pypi

- .flake8
Ignore all the current flake8 errors
So that flake8 is somewhat useful for the time being.
This can be updated to stop ignoring the errors as
we fix them.
(Most of the errors could be easily fixed in other prs if we want to enforce them, but
for now try to get flake8 passing so it means something when it starts failing)
> Flake8 ignore doc errors for now

- CHANGES/122.bugfix
- CHANGES/159.bugfix
- release_requirements.txt
The galaxy-importer version 0.2.3 includes:
* fix for importer job scheduling issues with importer resource params
* fix for importer error on unexpected docstring format
Works #122, #159
> Update galaxy-importer dependency to 0.2.3

- README.md
- At the end of the example playbook, add a config role that creates a default repository, distribution and a permission group.
- Give the user some clue on accessing the new server.
Depends on https://github.com/pulp/pulp_installer/pull/293
> Adds config role and login instructions

- galaxy_ng/app/api/urls.py
- galaxy_ng/app/api/v3/serializers.py
- galaxy_ng/app/api/v3/urls.py
- galaxy_ng/app/api/v3/viewsets.py
- galaxy_ng/app/api/views.py
- galaxy_ng/app/models/collectionimport.py
- galaxy_ng/app/settings.py
This replaces most of galaxy_ng/app/api/v3/ with viewsets based on the pulp_ansible v3 viewsets eliminating the use of galaxy_pulp for those views.
This also adds a new set of api endpoints that are exposed on urls based on each available
pulp Distribution's base_path. ie, there is an api endpoint for each pulp Repository
The new 'per Distribution' endpoints:
```
/api/automation-hub/content/<str:path>/v3/collections/	galaxy_ng.app.api.v3.viewsets.CollectionViewSet	galaxy:api:per_distribution:collection-list
/api/automation-hub/content/<str:path>/v3/collections/<str:namespace>/<str:name>/	galaxy_ng.app.api.v3.viewsets.CollectionViewSet	galaxy:api:per_distribution:collection
/api/automation-hub/content/<str:path>/v3/collections/<str:namespace>/<str:name>/versions/ …
```
> Use pulp viewsets for 'v3' and add per repo/distro v3 style endpoints

- galaxy_ng/app/api/v3/viewsets.py
First pass at returning the CollectionImport url
include the repo <path> in the response to
a POST to:
/api/automation-hub/content/automation-hub/v3/artifacts/collections/
Better fix will be either add method to CollectionImport to build
url with pass in <path>.
Or Better, to add a field to CollectionImport that references the
Repository the collection was imported to, so it can fill out the
<path> in the url pattern itself in get_absolute_url()
Issue: #167
> Fix import record url returned from publish

- galaxy_ng/app/api/urls.py
- galaxy_ng/app/api/v3/urls.py
- galaxy_ng/app/api/v3/viewsets.py
Add a galaxy-api style Artifact Download viewset
This is a wrapper around a request to pulp content
app itself. Mainly so metrics can be incremented.
Note the StreamingHTTPResponse has to use
response.raw.stream(amt=4096) as the content iterator
since the response.iter_content() automatically
decompresses tar.gz files.
> Add galaxy dev style artifact download

- README.md
Reference: https://pulp.plan.io/issues/6760
> Updated the required roles names

- galaxy_ng/app/api/base.py
- galaxy_ng/app/api/ui/viewsets/collection.py
- galaxy_ng/app/api/v3/viewsets/collection.py
- galaxy_ng/tests/unit/api/test_api_ui_auth_views.py
Authentication unit tests were failing if being executed with
`GALAXY_DEPLOYMENT_MODE` setting value other than 'standalone'.
This was caused by several factors:
1. When other `GALAXY_DEPLOYMENT_MODE` is used, usually
authentication and permission classes are different.
For these unit tests to pass it is required that.
`SessionAuthentication` and `TokenAuthentication` authentication
classes are used.
This is fixed by overriding `GALAXY_AUTHENTICATION_CLASSES`
and `GALAXY_PERMISSION_CLASSES` settings variables for related
unit tests.
2. Settings that were overridden in unit tests were not applied
properly, because settings values were read at module import time
and settings were not reloaded if set later by `@override_settings`
decorator.
This is fixed by refactoring local settings from …
> Fix unit tests failing when run in non-standalone mode

- CHANGES/187.feature
- galaxy_ng/app/api/ui/urls.py
- galaxy_ng/app/api/ui/views/__init__.py
- galaxy_ng/app/api/ui/views/auth.py
- galaxy_ng/app/api/urls.py
- galaxy_ng/app/api/v3/urls.py
- galaxy_ng/app/api/v3/views/__init__.py
- galaxy_ng/app/api/v3/views/auth.py
- galaxy_ng/tests/unit/api/test_api_ui_auth_views.py
- galaxy_ng/tests/unit/api/test_api_v3_auth_views.py
- openapi/openapi.yaml
- openapi/ui_openapi.yaml
* Token API is moved from UI to v3 and now is served at ``<prefix>/v3/auth/token/``.
* Token API does not support ``GET`` method anymore,
token is returned to client only once after creation.
* Add support of HTTP Basic authentication method to the Token API.
Issue: #187
> Improvements to the Token API

- CHANGES/170.feature
- dev/standalone/galaxy_ng.env
- galaxy_ng/app/api/v3/viewsets/collection.py
- galaxy_ng/app/settings.py
- galaxy_ng/app/tasks/__init__.py
- galaxy_ng/app/tasks/publishing.py
- galaxy_ng/tests/unit/app/test_tasks.py
- release_requirements.txt
- setup.py
* Add config setting for when to require approval of a collection version
* Add galaxy_ng task to call pulp_ansible `import_collection` task then auto-approve collection version
* In CollectionUploadViewSet dispatch pulp task from pulp_ansible or galaxy_ng based on config
Works #170
> Auto-approve collection version on import

- CHANGES/214.bugfix
- galaxy_ng/app/api/v3/viewsets/collection.py
Add a certification="certified" filter to the default queryset
Issue: #214
> Fix CollectionVersionViewSet showing uncertified content

- .travis/custom_check_pull_request.py
* Fix No-Issue label not recognized in commit message.
* Fix `get_commit_message()` returned commit message with
patch. Now returns only a commit message.
No-Issue
> Fix commit message check string for Travis CI

- README.md
- Move password var to the top
- Updates the note, pointing out that there are 2 places where the var must be set.
> Make password change clearer

- CHANGES/41.feature
- galaxy_ng/app/api/v3/urls.py
- galaxy_ng/app/api/v3/viewsets/__init__.py
- galaxy_ng/app/api/v3/viewsets/collection.py
- galaxy_ng/app/tasks/__init__.py
- galaxy_ng/app/tasks/promotion.py
- openapi/openapi.yaml
`move/` endpoint on a CollectionVersion that starts 2 pulp tasks... 1 to make a new RepositoryVerison of source repo without CollectionVersion, and 1 to make a new RepositoryVersion of destination repo with CollectionVersion. Works #41, #117
Example:
`api/automation-hub/content/automation-hub/v3/collections/<str:namespace>/<str:name>/versions/<str:version>/move/<str:source_path>/<str:dest_path>/`
Testing:
1. Confirm a version (i.e. `1.0.74`) in list http://localhost:5001/api/automation-hub/content/staging/v3/collections/awcrosby/collection_test/versions/
2. POST to http://localhost:5001/api/automation-hub/v3/collections/awcrosby/collection_test/versions/1.0.74/move/staging/automation-hub/ and see task ids returned
3. Confirm version no longer in source_repo list: …
> Promotion collection version move/ endpoint

- README.md
Earlier today in `pulp/pulp_installer`
https://github.com/pulp/pulp_installer/pull/332 got merged. This leads
to one having to specify the pulp_redis role explicitly.
It has a WIKI Impact
> README: Make call to pulp_redis explicit

- CHANGES/247.bugfix
- galaxy_ng/app/api/v3/serializers/__init__.py
- galaxy_ng/app/api/v3/serializers/collection.py
- galaxy_ng/app/api/v3/urls.py
- galaxy_ng/app/api/v3/viewsets/collection.py
The pulp_ansible viewsets build hrefs by reverse() on the
pulp_ansible url name. But the galaxy_ng names are different
and include url namespaces ('galaxy:api:v3:collection' for ex).
Makes collection api endpoints serialize correctly, with the various
href's pointing to the right places. That includes:
1. Not pointing to the pulp hrefs
1. pointing to either the default-content endpoint or the per-repo
endpoints
Update the collection url 'names' so that suffix matches the
upstream pulp names exactly (sanes url namespace)
Add custom collection Serializer's that uses view_namespace for url reverse.
Add a serializers.collections.HrefNamespaceMixin to use
with the galaxy_ng subclasses of collection related
pulp_ansible.app.galaxy Serializers.
Update the collection related viewsets to use the …
> Fix wrong href's in results from collection viewsets

- CHANGES/256.bugfix
- galaxy_ng/app/api/v3/viewsets/collection.py
In the move to use the pulp viewsets, the previous
workaround for ansible/galaxy-dev#246 didn't
get added back. That was added in 035371f819a168b
but got removed in 1245d37bf5.
So, add it back.
This manifests itself with older versions of ansible-galaxy
on 'publish'. If the server doesn't workaround the multipart
parser, the sha256 value in the body will be ignored, and
cause 400 errors about the sha256sum mismatch.
> Fix for bad multipart posts workaround got rm, readd

- galaxy_ng/app/api/ui/viewsets/user.py
Cannot sort Users by `last_name` via API
Call `http://0.0.0.0:8002/api/automation-hub/v3/_ui/users/?sort=-last_name&offset=0&limit=10`
Returns `400` with
```
{"errors":[{"status":"400","code":"invalid_choice","title":"Invalid input.","detail":"Select a valid choice. -last_name is not one of the available choices.","source":{"parameter":"sort"}}]}
```
Returns `200` and sorted data like it does for `first_name, username, email`
@newswangerd Please have a look, thanks :)
> Add sort last_name for User

- CHANGES/118.misc
- galaxy_ng/app/api/ui/serializers/collection.py
- galaxy_ng/app/api/ui/viewsets/collection.py
- galaxy_ng/tests/unit/api/test_api_ui_collectionversion_viewsets.py
Closes-Issue: #118
* Adds query by repo
* Removes the use of galaxy_pulp for list() and retrieve()
With this, the UI can make these changes to the Certification Dashboard (#119):
* Change query parameter used from `certification` to `repository`
* Change approval collection version api call from `certification/` to `move/` (#140)
This leaves the certification/ endpoint working until the UI stops using it
> Support query by repo for _ui CollectionVersionViewSet

- CHANGES/288.misc
- galaxy_ng/app/api/ui/serializers/collection.py
- galaxy_ng/tests/unit/api/test_api_ui_collectionversion_viewsets.py
For the certification dashboard, add a `repository_list` field to the _ui collection-version endpoint.
This field includes a `Repository` if the `CollectionVersion` is included in the latest `RepositoryVersion`
An example:
```
"repository_list": [
"automation-hub",
"org-my_org"
]
```
> Add repository_list to data returned in _ui collection-version endpoint

- docker/bin/start-worker
Pulp worker were deployed with pre-defined name to avoid
stalled tasks. However this issue is not reproducible
at current pulpcore version.
References:
[1] https://pulp.plan.io/issues/7119
No-Issue
> Remove static naming for pulp worker

- CHANGES/117.feature
- galaxy_ng/app/api/v3/viewsets/collection.py
- galaxy_ng/app/settings.py
- galaxy_ng/app/tasks/__init__.py
- galaxy_ng/app/tasks/publishing.py
- galaxy_ng/tests/unit/app/test_tasks.py
Closes-Issue: #117
Adds custom task to call pulp_ansible import_collection, then
enqueues tasks to move CollectionVersion from whichever repository
it is coming into, to the staging repository.
Adds names for staging repo and rejected repo to settings.
> Add repo name params and task to move from inbound to staging repo

- dev/automation-hub/initial_data.json
Have development fixtures automatically create a `staging` and `rejected` repo, in addition to the `automation-hub` repo. After this, wiki manual steps will need to be updated.
Related-Issue: #117
> Update development pulp data fixture with staging and rejected repos

- CHANGES/37.feature
- CHANGES/38.feature
- galaxy_ng/app/api/v3/viewsets/namespace.py
- galaxy_ng/app/migrations/0003_inbound_repo_per_namespace.py
- galaxy_ng/tests/unit/api/test_api_v3_namespace_viewsets.py
Closes-Issue: #37
* Create and delete repo on api namespace create and delete
* The repo is tied to the namespace by name
* This applies to pulp Repository and Distribution
* Convention uses same text for names and base_path of repo and distro
> Auto create and delete inbound pulp repo per namespace

- CHANGES/318.bugfix
- dev/standalone/galaxy_ng.env
- galaxy_ng/app/api/v3/viewsets/collection.py
Fix usage of parameter `settings.GALAXY_REQUIRE_CONTENT_APPROVAL`
that disables content auto approval.
Closes-Issue: #318
> Fix auto certification parameter check

- .travis/Containerfile.j2
- .travis/before_install.sh
- .travis/before_script.sh
- .travis/build_container.yaml
- .travis/install.sh
- .travis/script.sh
- .travis/start_container.yaml
- galaxy_ng/app/api/ui/viewsets/collection.py
- galaxy_ng/app/api/v3/viewsets/namespace.py
- setup.py
- Making build errors easier to see
- Removing pulpcore upper bound
- OpenAPI v3 with drf-spectacular
Problem:
```
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/usr/local/lib/python3.7/site-packages/pulp_ansible/app/viewsets.py", line 18, in <module>
from pulpcore.plugin.models import PulpTemporaryFile
ImportError: cannot import name 'PulpTemporaryFile' from 'pulpcore.plugin.models' (/usr/local/lib/python3.7/site-packages/pulpcore/plugin/models/__init__.py)
```
Solution:
Removing pulpcore upper bound
Alternative: https://github.com/ansible/galaxy_ng/pull/321
> Updating and fixing the CI

- Makefile
No-Issue
```
galaxy_ng$ make help 
Usage: make <target>
Targets:
help:             ## Show the help.
requirements:     ## Update python dependencies lock files (i.e. requirements.txt).
docker/build:     ## Build all development images.
docker/test:      ## Run unit tests.
galaxy_ng$
```
> Add unit test command to Makefile

- CHANGES/93.feature
- openapi/openapi.yaml
Update openAPI, add server with /api/automation-hub/
Also add the leading /v3/ to urls where needed, since it
is not implied anymore since the per-org endpoints aren't
at /api/automation-hub/v3/ but
/api/automation-hub/content/{base_path}/v3
Issue: #93
https://github.com/ansible/galaxy_ng/issues/93
> Update openapi.yml to include /content/{distribution_base_path}

- CHANGES/295.feature
- galaxy_ng/app/api/v3/serializers/__init__.py
- galaxy_ng/app/api/v3/serializers/task.py
- galaxy_ng/app/api/v3/urls.py
- galaxy_ng/app/api/v3/viewsets/__init__.py
- galaxy_ng/app/api/v3/viewsets/collection.py
- galaxy_ng/app/api/v3/viewsets/task.py
Closes-Issue: #295
Add task view for certification dashboard to get status of pulp tasks
on CollectionVersion move. Also useful for other pulp tasks such as
importing, moving repos on import, and sync
Update CollectionVersion move endpoint permission to be same as
certification dashboard
Example endpoints:
```
http://localhost:5001/api/automation-hub/v3/tasks/
http://localhost:5001/api/automation-hub/v3/tasks/acc6fea7-12c2-48fb-b6c5-85f1a3237404/
```
> Add task view for certification dashboard, update move permission

- CHANGES/316.feature
- galaxy_ng/app/tasks/publishing.py
- galaxy_ng/tests/unit/app/test_tasks.py
Closes-Issue: #316
* On GALAXY_REQUIRE_CONTENT_APPROVAL=False edit the auto approve task to
use pulp repos to automatically promote content to golden repo
> Update import_and_auto_approve task to use pulp repos

- .travis/before_install.sh
- .travis/install.sh
- CHANGES/380.feature
- requirements/requirements.common.txt
- requirements/requirements.insights.txt
- requirements/requirements.standalone.in
- requirements/requirements.standalone.txt
- setup.py
Now that all the Pulp features needed for 4.2.0b are released, we can pin to the latest packages. Reverses the work done in #330.
Closes-Issue: #380
> Pinning to latest pulpcore, pulp-ansible and pulp-container

- requirements/requirements.common.txt
- requirements/requirements.insights.txt
- requirements/requirements.standalone.txt
- requirements/requirements.txt
No-Issue
Undoing the version change `galaxy-importer` from `0.2.8rc10` to `0.2.7` done in 3c3924f
> Set galaxy-importer back to 0.2.8rc10

- CHANGES/120.feature
- galaxy_ng/app/api/v3/viewsets/collection.py
Related-Issue: #120
With the certified flag on a CollectionVersion no longer denoting
whether or not the version is certfied, the filter is being removed from
the CollectionVersionViewSet.
> Remove v3 CollectionVersion certified flag filter

- galaxy_ng/tests/functional/api/test_crud_content_unit.py
No-Issue
Re-add test that was commented-out in a8243fa, now that
pulp_ansible fix is in: https://github.com/pulp/pulp_ansible/pull/339
> Re-add temporarily-removed api functional test

- CHANGES/403.bugfix
- galaxy_ng/app/api/v3/urls.py
- galaxy_ng/app/api/v3/viewsets/__init__.py
- galaxy_ng/app/api/v3/viewsets/collection.py
Closes-Issue: #403
Add endpoint `v3/collections/<namespace>/<collection>/versions/<version_number>/docs-blob/` by subclassing pulp_ansible view
~~- Add `docs_blob_url` to: `v3/collections/<namespace>/<collection>/versions/<version_number>/`~~
> Add docs_blob to v3 api for collection versions

- CHANGES/282.feature
- galaxy_ng/app/access_control/statements/insights.py
- galaxy_ng/app/access_control/statements/standalone.py
- galaxy_ng/app/api/ui/serializers/collection.py
- galaxy_ng/app/api/ui/serializers/user.py
- galaxy_ng/app/api/ui/viewsets/collection.py
- galaxy_ng/app/api/urls.py
- galaxy_ng/app/api/v3/serializers/sync.py
- galaxy_ng/app/api/v3/urls.py
- galaxy_ng/app/api/v3/views/__init__.py
- galaxy_ng/app/api/v3/views/sync.py
- galaxy_ng/app/api/v3/viewsets/__init__.py
- galaxy_ng/app/api/v3/viewsets/sync.py
- galaxy_ng/app/constants.py
- galaxy_ng/app/models/__init__.py
- galaxy_ng/tests/unit/api/base.py
- galaxy_ng/tests/unit/api/test_api_ui_collection_viewsets.py
- galaxy_ng/tests/unit/api/test_api_ui_sync_config.py
- endpoint: `/content/<distribution>/v3/sync/config/`
- methods: GET/PUT
- endpoint: `/content/<distribution>/v3/sync/`  (taken from #409) 
- methods: POST
Issue: #282
> Add endpoints for sync/config management

- .travis/generate_python_manifest.py
No-Issue
Fixes master branch manifest travis logic to skip git+ source
installs instead of skipping editable installs
> Skip git source installs for manifest generation

- Dockerfile.rhel8
(cherry picked from commit 7c67690b2480d535eb727d1db1bd27a2101aab43)
Backport: #422
> Fix entrypoint script name in Dockerfile.rhel8 (#422)

- dev/automation-hub/initial_data.json
- galaxy_ng/tests/unit/api/test_api_ui_sync_config.py
Add data to `initial_data.json` to insert remotes
for `rh-certified` and `community` repositories and
its respective distributions.
Also fixed tests because of new validation rules on pulp_ansible
```py
{
'errors': [
{
'status': '400', 
'code': 'invalid', 
'title': 'Invalid input.', 
'detail': "Invalid URL https://galaxy.ansible.com. Ensure the URL ends in either '/v2/collections' or '/v3/collections'"
}
]
}
```
> Add fixtures for rh-certified and community remotes

- CHANGES/428.feature
- galaxy_ng/app/api/v3/viewsets/collection.py
In the CollectionMoveViewSet, if either of the repositories
involved is the 'golden' repo, then enqueue a
'curate_all_synclist_repository' task that start
tasks that curate all synclist repositories based on
the synclist associated with it.
ie, when the main repo changes, kick off tasks to update
all the repos based on it.
Issue: #428
> On changes to golden repo, trigger all synclist tasks

- galaxy_ng/app/api/v3/serializers/sync.py
According to comment by @bmbouter on
https://github.com/ansible/galaxy_ng/pull/410/files#r486534931
Our Serializer should not override policy field until
pulp_ansible supports other policies.
No-Issue
> HOTFIX: Remove policy field from SyncConfig serializer

- CHANGES/430.misc
- galaxy_ng/app/management/commands/create-remote.py
- galaxy_ng/tests/unit/app/management/commands/test_create_remote.py
```
$ create-remote rh-certified https://url.tld/v3/collections --options
```
or loading a requirement_file
```
$ create-remote community https://galaxy.ansible.com/v3/collections -r
/tmp/my_requirements.yaml
```
```
❯ manage.py create-remote --help
usage: django-admin create-remote [-h] [--token TOKEN] [--policy POLICY]
[--auth_url AUTH_URL]
[--repository REPOSITORY]
[--distribution DISTRIBUTION]
[-r REQUIREMENTS_FILE] [--version]
[-v {0,1,2,3}] [--settings SETTINGS]
[--pythonpath PYTHONPATH] [--traceback]
[--no-color] [--force-color]
name url
positional arguments:
name                  Remote Name
url                   Remote Feed URL, Should not end with a '/', should end
in v2/collections or v3/collections
optional arguments:
-h, --help            show this help message and exit …
```
> Added create-remote management command.

- CHANGES/439.misc
- galaxy_ng/app/api/ui/serializers/collection.py
- galaxy_ng/app/api/ui/urls.py
- galaxy_ng/app/api/ui/viewsets/collection.py
- galaxy_ng/tests/unit/api/test_api_ui_collection_viewsets.py
Closes-Issue: #439
Changes the ui collection endpoint view to subclass pulp which adds keyword search and tag filtering support. Further duplication can be removed once the noted pulp issue is resolved.
> Update ui collection endpoint to subclass pulp and support search

- galaxy_ng/app/common/pulp.py
This might be me not knowing where to look for it. But I was looking to disable cert validation by enabling a toggle on the settings file and I couldn't find it. This commit allows me to do that.
If there is another way to currently do it please let me know and feel free to close this PR.
Issue: #464
> TLS: Allow one to disable certificate verification from settings file

- dev/automation-hub/initial_data.json
As we expected, putting in the IDs for permissions into the dev fixtures broke and is currently blocking the fixtures from running.
> Remove permissions from pe group in fixtures.

- .travis/before_install.sh
- CHANGES/476.feature
- Makefile
- requirements/requirements.common.txt
- requirements/requirements.insights.txt
- requirements/requirements.standalone.in
- requirements/requirements.standalone.txt
- setup.py
The ANSIBLE_SKIP_CONFLICT_CHECK additions to
the pip-compile lines are because otherwise
pip-compile fails with error:
Upgrading directly from ansible-2.9 or less to ansible-2.10 or greater with pip is
known to cause problems.  Please uninstall the old version found at:
/home/adrian/venvs/galaxy_ng_2/lib64/python3.6/site-packages/ansible/__init__.py
and install the new version:
pip uninstall ansible
pip install ansible
If you have a broken installation, perhaps because ansible-base was installed before
ansible was upgraded, try this to resolve it:
pip install --force-reinstall ansible ansible-base
If ansible is installed in a different location than you will be installing it now
(for example, if the old version is installed by a system package manager to …
> Update pulpcore to >=3.7,<3.9, pulp_ansible~=0.4.0  #476

- CHANGES/473.misc
- galaxy_ng/app/webserver_snippets/apache.conf
- galaxy_ng/app/webserver_snippets/nginx.conf
Restrict access to pulpcore and pulp_ansible API from a reverse proxy
configured by pulp installer.
Issue: #473
> Restrict access to pulp API from reverse proxy

- CHANGES/496.bugfix
- galaxy_ng/app/access_control/access_policy.py
- galaxy_ng/app/api/urls.py
- galaxy_ng/app/api/v3/viewsets/collection.py
- galaxy_ng/app/settings.py
Closes-Issue: #496
Uploads with no distro specified will use `inbound-<namespace>` distro based on filename namespace
> Use filename namespace on upload when no distro specified

- CHANGES/31.bugfix
- galaxy_ng/app/api/v3/serializers/collection.py
The ValidationError was getting raised with a 'details'
dict that didn't include a 'code', so it was unset.
Pass in a code to use _get_error_details() to generate
the 'detail' dict correctly with a valid 'invalid'.
Fixes #31
> Better error for invalid filename

- .travis/check_pulpcore_imports.sh
- CHANGES/390.misc
- galaxy_ng/app/tasks/synclist.py
Since we require pulpcore 3.7+ now, we don't need
these pulpcore import excludes in the travis ci checks
Issue: #390
> Remove excludes from check_pulpcore_includes CI script

- openapi/openapi.yaml
* Fix authentication url
* Change server url to match the dev environment.
The OpenAPI spec had an incorrect url for authentication, as it hadn't been updated since the URL was changed from `/auth/token` to `/v3/auth/token`.
~~I've also changed the server url so that it properly matches the dev environment, which starts the server on port 8002 rather than 5001.~~ EDIT 3: This change resulted due to my misunderstanding of the containerization setup, and I've revised the PR to omit it.
EDIT: you can view my changes at https://petstore.swagger.io/?url=https://raw.githubusercontent.com/hendersonreed/galaxy_ng/fix-openapi-spec-auth-url/openapi/openapi.yaml#/
EDIT 2: pasted the wrong url in my first edit, so I fixed that.
> Fix OpenAPI spec auth url

- CHANGES/493.bugfix
- galaxy_ng/app/migrations/0009_add_repoversion_to_inbound_repos.py
Closes-Issue: #493
Adds missing init `RepositoryVersion` to inbound repos
created in 0003_inbound_repo_per_namespace.
> Migration to add missing RepositoryVersion to inbound repos

- .travis/check_pulpcore_imports.sh
- galaxy_ng/app/customadmin.py
- galaxy_ng/app/settings.py
- galaxy_ng/app/urls.py
This change enables custom admin site at configurable URL
It is temporary workaround and should be removed when
pulp/pulpcore#948 is released.
No-Issue
> Temporary django admin site at custom URL

- galaxy_ng/app/api/ui/old_urls.py
- galaxy_ng/app/api/ui/serializers/__init__.py
- galaxy_ng/app/api/ui/serializers/collection.py
- galaxy_ng/app/api/ui/urls.py
- galaxy_ng/app/api/ui/viewsets/__init__.py
- galaxy_ng/app/api/ui/viewsets/collection.py
- galaxy_ng/tests/unit/api/test_api_ui_collection_viewsets.py
This endpoint is no longer used by the UI and was replaced with per-repo collections logic.
> Remove ui api non-repo collections endpoint

- CHANGES/27.bugfix
- galaxy_ng/app/api/ui/viewsets/distribution.py
Add 'accept_global_perms' to the get_objects_for_user() request
to avoid hitting scenario 2 mentioned in
https://django-guardian.readthedocs.io/en/stable/api/guardian.shortcuts.html#get-objects-for-user
The default for 'accept_global_perms' is True, which makes
get_objects_for_user() match any objects based on model
perms not object perms.
Issue: AAH-27
> Fix my-distributions show only sycnlist distros with obj perms

- CHANGES/21.misc
- galaxy_ng/app/api/ui/serializers/__init__.py
- galaxy_ng/app/api/ui/serializers/collection.py
- galaxy_ng/app/api/ui/viewsets/collection.py
- galaxy_ng/app/api/v3/serializers/sync.py
- galaxy_ng/app/api/v3/viewsets/sync.py
- Combined serializers for /remotes and /sync/config as the model is the
same
- Used a Mixin to deduplicate existing code
- Added extra fields to the serializer: 
- username
- password
- proxy_url
- client_key
- client_cert
- tls_validation
- ca_cert
- pulp_href
- pk
- download_concurrecy
Issue: AAH-21
Reference: https://pulp-ansible.readthedocs.io/en/latest/restapi.html#operation/remotes_ansible_collection_list
> API: Surface all remote config options

- CHANGES/98.bugfix
- galaxy_ng/app/api/ui/viewsets/collection.py
The fields list tuple passed to OrderedFilter needs
'field_name' and 'parameter_name'.
The field_name needs to use the related field
description syntax (ie, 'galaxy_import__created_at')
Closes-Issue: AAH-98
> Fix sort=created on ui /imports/collections/  (AAH-98)

- CHANGES/99.bugfix
- galaxy_ng/app/api/v3/viewsets/collection.py
The pkey of galaxy's CollectionImport (galaxy_collectionimport table)
is task_id. But the 'task_id' is a OneToOne to a
pulp_ansible.app.models.CollectionImport now instead of just
a plain UUID.
So, get the right pulp CollectionImport and use it for
task_id when creating a galaxy_ng.app.models.CollectionImport.
> Fix import task errors about ansible.CollectionImport

- CHANGES/94.misc
- galaxy_ng/app/api/ui/serializers/distribution.py
Previously repo content counts were showing the sum of all content across all repo versions. This update will only show the content in the latest version.
Issue: AAH-94
> Fix repo content count 

- galaxy_ng/app/management/commands/create-remote.py
- galaxy_ng/tests/unit/app/management/commands/test_create_remote.py
pulp-ansible 0.50 changed validation to allow only URLs ending in a trailing /
No-Issue
> Fix create-remote cmd validation for trailing /

- CHANGES/122.bugfix
- galaxy_ng/app/api/ui/viewsets/collection.py
All the returned querysets must keep the same fields.
Add deprecated as an annotated field for empty queryset.
Issue: AAH-122
> Add deprecated as an annotated field for empty queryset.

- CHANGES/97.bugfix
- galaxy_ng/app/api/ui/viewsets/my_synclist.py
Apply 'accept_global_perms' fix from https://github.com/ansible/galaxy_ng/pull/523 to my-synclist
Issue: AAH-97
> Fix my-synclist to show only synclists with obj permissions

- galaxy_ng/app/access_control/statements/insights.py
In the access control statements, make consistent the
data type for condition when there is a single condition
No-Issue
> Make consistent access control data types

- galaxy_ng/app/migrations/0011_collection_import_task_id_fk.py
Change the 0011 migrations to cleanup any orphan
galaxy_collectionimport rows that have a task_id that
does not point to an existing ansible_collectionimport.
ie, cases where ansible_collectionimport and core_task
were cleaned up by hand but galaxy_collectionimport was not.
(There was no fk or cascade link between them, so the deletes
on ansible_collectionimport would not cause errors while
also not deleting the related rows in galaxy_collectionimport).
No-Issue
> Cleanup orphan gng col_imports before altering the table

- CHANGES/12.bugfix
- dev/automation-hub/initial_data.json
Pulp ansible validation for remotes changed so
the fixtures URLs needs an extra `/` at the end
Issue: AAH-12
> Fix the remote configuration fixtures

- galaxy_ng/tests/unit/api/test_api_ui_sync_config.py
Required by pulp_ansible https://github.com/pulp/pulp_ansible/pull/418
No-Issue
> Add token param to unit tests for syncconfig

- CHANGES/132.bugfix
- galaxy_ng/app/api/v3/serializers/namespace.py
- galaxy_ng/app/api/v3/viewsets/namespace.py
- galaxy_ng/app/exceptions.py
Related isssue: https://issues.redhat.com/browse/AAH-132
1. Namespace creation fails when links are associated.
solution: link_data was missing relationship with namespace instance
2. Error 500 was raised when trying to create a namespace with existing name.
solution: validate for existence before the creation of dependent instances on ViewSet.create method.
```
❯ http post :8002/api/automation-hub/_ui/v1/namespaces/ "Authorization: Token b1a99acc28ebfd33fc2ce4684408079456efe6de" <<<'{"name":"testing15","company":"Redhat","email":"user@example.com","avatar_url":"https://www.redhat.com/cms/managed-files/styles/wysiwyg_full_width/s3/Logo-RedHat-Hat-Color-CMYK%20%281%29.jpg?itok=Mf0Ff9jq","description":"string","links":[{"name": "homepage","url":"http://www.google.com"}],"groups":[{"name":"sy …
```
> Fix for 2 issues reported on AHH-132

- galaxy_ng/app/api/v3/serializers/collection.py
- galaxy_ng/app/api/v3/viewsets/collection.py
- galaxy_ng/app/tasks/publishing.py
- galaxy_ng/tests/unit/app/test_tasks.py
This reverts commit 0ab1e0f which requires pulp_ansible 0.5.1
No-Issue
> Revert "Fix the passing along of filename data (#546)"

- dev/automation-hub/initial_data.json
In order to sync to work, the remote URL should point
to the API root endpoint.
No-Issue
> Changed remote fixtures URL pointing to the api root

- .travis/before_install.sh
- requirements/requirements.common.txt
- requirements/requirements.insights.txt
- requirements/requirements.standalone.txt
- setup.py
Updates included in 0.5.1:
* allows for galaxy_ng fix: Fix the passing along of filename data #546
* track when versions for a collection have been updated https://pulp.plan.io/issues/7775, includes field updated_at to use latest instead of highest version pulp/pulp_ansible#416
* resolve token refreshes every request to cloud.redhat.com
No-Issue
> Upgrade pulp_ansible to 0.5.1

- galaxy_ng/app/api/v3/serializers/collection.py
- galaxy_ng/app/api/v3/viewsets/collection.py
- galaxy_ng/app/tasks/publishing.py
- galaxy_ng/tests/unit/app/test_tasks.py
Re-applies the fix in https://github.com/ansible/galaxy_ng/pull/546 which was temporarily reverted
No-Issue
> Fix the passing along of filename data

- .github/patchback.yml
Patchback watches for pull requests with the `backport-{version}` label. When PRs are merged with the label, backpatch will create a backport PR that cherrypicks the commits in the PR to `stable-{version}`.
For example a PR with the `backport-4.2` label will result in a PR with cherry-picked commits on branch `stable-4.2`.
> Add patchback support for auto cherry picking backports.

- CHANGES/152.bugfix
- galaxy_ng/app/api/ui/viewsets/group.py
- galaxy_ng/app/api/v3/viewsets/namespace.py
- galaxy_ng/tests/unit/api/test_api_v3_namespace_viewsets.py
- In case of existing group or namespace API returns 409 conflict
- Fixed error message that was not well formatted on PR #562
- Added unittest for namespace
Issue: AAH-152
**Before**:
**After:**
> API to return 409 in case of existing group/namespace

- CHANGES/185.feature
- setup.py
This commit allows one to specify an alternative name for the build
and and alternative UI URL.
The goal of this commit is to allow nightly builds in the form of
```
ALTERNATE_VERSION = 4.3.0dev20201130gitb48b56e ALTERNATE_UI_DOWNLOAD_URL = https://github.com/ansible/ansible-hub-ui/tarball/master python setup.py sdist
```
> setup.py: Allow greater version and UI URL flexibility

- Dockerfile
This is helpful to know which registry we are pulling centos:8 from.
Ideally we should move this to quay.io, once we know images are
officially published there.
Signed-off-by: Paul Belanger <pabelanger@redhat.com>
> Namespace Dockerfile FROM statement

- CHANGES/166.bugfix
- galaxy_ng/app/api/v3/viewsets/namespace.py
The namespaces api now performs a partial match on namespace name and namespace company name when using the 'keywords' query parameter.
> Perform partial matches on namespace keywork lookups.

- CHANGES/139.misc
- galaxy_ng/app/api/v3/viewsets/collection.py
- galaxy_ng/app/api/v3/viewsets/namespace.py
- galaxy_ng/app/constants.py
- galaxy_ng/app/models/namespace.py
- galaxy_ng/tests/unit/api/test_api_v3_namespace_viewsets.py
- galaxy_ng/tests/unit/test_models.py
- Creation of inbound repo and distro moved to Namespace model manager
- Logic for deletion also moved to namespace manager
- Unit tests added
Issue: AAH-139
> Move creation of inboud repo and distro to Namespace model manager.

- CHANGES/195.bugfix
- galaxy_ng/app/api/ui/viewsets/collection.py
- galaxy_ng/app/api/v3/viewsets/namespace.py
Fix AAH-195: https://issues.redhat.com/browse/AAH-195
Fix the KeyError by replacing the getitem with the use of `.get` and letting the underlying validation to raise the proper error.
In the case of namespaces the serializer validation will raise 400 saying `name is required`
In the case of collections the error is on routing system, for some reason it is not providing the `path` key as it was detected by the monitoring system it is not easy to reproduce.
There is another issue to track the routing problems: https://issues.redhat.com/browse/AAH-157
> Check for path key using .get to avoid KeyError on collections

- .travis/custom_check_pull_request.py
- CHANGES/44.bugfix
Check for 404 status code instead of `ok` so it works
even for unlogged sessions.
Issue: AAH-44
> Fix how CI checks for Jira issue existence

- .travis/check_pulpcore_imports.sh
- CHANGES/16.misc
- galaxy_ng/app/api/v3/serializers/__init__.py
- galaxy_ng/app/api/v3/serializers/task.py
- galaxy_ng/app/api/v3/viewsets/task.py
- galaxy_ng/tests/unit/api/test_api_v3_tasks.py
Issue: AAH-16
Replaces #488 
/tasks/
```json
GET /api/automation-hub/v3/tasks/
HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept
{
"meta": {
"count": 2
},
"links": {
"first": "/api/automation-hub/v3/tasks/?limit=10&offset=0",
"next": null,
"last": "/api/automation-hub/v3/tasks/?limit=10&offset=0"
},
"data": [
{
"pulp_id": "4a02f4b2-201c-4c71-8d5b-56a717332d20",
"name": "pulp_ansible.app.tasks.collections.sync",
"repository": "rh-certified",
"state": "failed",
"started_at": "2020-11-09T16:32:47.436947Z",
"finished_at": "2020-11-09T16:32:48.340957Z",
"href": "/api/automation-hub/v3/tasks/4a02f4b2-201c-4c71-8d5b-56a717332d20/"
},
{
"pulp_id": "51d13b1d-328b-4354-b832-b1c706055522",
"name": "pulp_ansible.app.tasks.collections.sync", …
```
> Add more fields to /tasks endpoint

- Dockerfile
This looks to be the official place container images are published now
from the centos team. It also means we can avoid getting ratelimits from
dockerhub.
Signed-off-by: Paul Belanger <pabelanger@redhat.com>
> Pull centos:8 from quay.io

- CHANGES/282.bugfix
- galaxy_ng/app/api/v3/serializers/sync.py
On /sync/config the fields password and token was being exposed
as plain text so we decided to obfuscate those
fields and make them write_only so it is not possible to
access password or token via API but only set it.
> **NOTE**: this password is not related to proxy, this is
the password used to authenticate to the remote.
Related: https://bugzilla.redhat.com/show_bug.cgi?id=1920613
Issue: AAH-282
> Make token and password obfuscated on the API docs for /sync/config

- .compose.env.example
- CHANGES/257.misc
- compose
- dev/Dockerfile.base
- dev/docker-compose.yml
- dev/standalone/Dockerfile
- docker/entrypoint.sh
Add `LOCK_REQUIREMENTS` variable on `.compose.env`
when this variable is set to `0` compose build will
bypass the installation of `requirements/*` lock files
avoiding VersionConflicts when using `master` checkout
for `pulpcore` and `pulp_ansible`.
also if that variable is set to `0` the entrypoint invoked
by `./compose up|run` will bypass the optization argument
`--no-deps` allowing the installation of bleeding edge
requirements introduced by pulp_ansible/pulpcore.
**NO** breaking change is added, the new variable is by default set to `1` to keep the current behaviour.
1. **Clone** locally `galaxy_ng`, `pulpcore` and `pulp_ansible` all the
repos must be located at the same directory level.
```
cd ~/projects/
git clone https://github.com/pulp/pulpcore
git clone …
```
> Make lockfiles optional for dev containers.

- requirements/requirements.common.txt
- requirements/requirements.insights.txt
- requirements/requirements.standalone.txt
- requirements/requirements.txt
Update `requirements/` requirement files to use new pip-tools format while keeping requirement changes to a minimum
> Update requirement files to use new pip-tools format

- CHANGES/265.bufix
- CHANGES/266.bugfix
- galaxy_ng/app/access_control/access_policy.py
- galaxy_ng/app/access_control/statements/standalone.py
- galaxy_ng/tests/unit/api/test_api_ui_user_viewsets.py
Prevent admin users from deleting admin users
Don't allow users that are 'superuser' or are
called 'admin' to be deleted.
Add conditionals to UserViewSet policy for
'user_is_superuser' and 'user_is_admin'.
Issue: AAH-266
(Currently includes changes for AAH-265 as well, since they are needed)
> Users or admins cant delete admins 266

- CHANGES/291.bugfix
- galaxy_ng/app/api/v3/serializers/sync.py
- galaxy_ng/app/common/proxy_url.py
- galaxy_ng/tests/unit/api/test_api_ui_sync_config.py
the pulpcore database field proxy_url holds
information in form: `http://user:pass@host:port`
This PR splits that field in 3 different fields
only for API retrieval (GET)
proxy_address - `http://host:port`
proxy_username - `user`
proxy_password - `pass`
As those 3 fields doesn;t exist (yet) in pulpcore database model
in order to save we need to rejoin those 3 fields so
it get back to it regular form.
we want to omit the `:pass` fragment from our retrieval API, but still expose user, host and port fragments
Issue: AAH-291
> Split proxy password field

- CHANGES/120.misc
- galaxy_ng/app/api/v3/serializers/sync.py
- galaxy_ng/tests/unit/api/test_api_ui_sync_config.py
Issue: AAH-120
Adds the following field to the sync endpoints:
```
"write_only_fields": [
{
"name": "client_key",
"is_set": false
},
{
"name": "token",
"is_set": false
},
{
"name": "password",
"is_set": false
},
{
"name": "proxy_password",
"is_set": true
}
]
```
> Add field detailing if a write only value is set or not.

- requirements/requirements.common.txt
- requirements/requirements.insights.txt
- requirements/requirements.standalone.txt
- requirements/requirements.txt
- setup.py
Run pip-compile --upgrade for packages: `cryptography`, `pygments`, and
`galaxy-importer` (which has `bleach` dependency)
Used `pip-tools==5.4.0` to generate deps to keep same format for stable-4.2 branch.
Related:
* pygments dep issue: https://bugzilla.redhat.com/show_bug.cgi?id=1922136
* cryptography dep issue: https://bugzilla.redhat.com/show_bug.cgi?id=1926226 AAH-331
* bleach issue https://bugzilla.redhat.com/show_bug.cgi?id=1827491 AAH-327 AAH-328
> Update stable-4.2 dependencies

- requirements/requirements.common.txt
- requirements/requirements.insights.txt
- requirements/requirements.standalone.in
- requirements/requirements.standalone.txt
2.3.1 includes this fix: https://github.com/pulp/pulp_container/pull/236 which was preventing us from using the pulp_container registry alongside galaxy_ng
> Update to pulp_container 2.3.1

- CHANGES/291.bugfix
- galaxy_ng/app/api/v3/serializers/sync.py
- galaxy_ng/app/common/proxy_url.py
- galaxy_ng/tests/unit/api/test_api_ui_sync_config.py
Backport: #630 
the pulpcore database field proxy_url holds
information in form: `http://user:pass@host:port`
Representation.
This PR splits that field in 3 different fields
only for API retrieval (GET)
proxy_address - `http://host:port`
proxy_username - `user`
proxy_password - `pass`
Saving.
As those 3 fields doesn;t exist (yet) in pulpcore database model
in order to save we need to rejoin those 3 fields so
it get back to it regular form.
Why?
we want to omit the `:pass` fragment from our retrieval API.
Issue: AAH-291
(cherry picked from commit a3b512dd25fbae899a56b685533c5c39997d7011)
> Backport: Split proxy_url in 3 fields (#630)

- CHANGES/120.misc
- galaxy_ng/app/api/v3/serializers/sync.py
- galaxy_ng/tests/unit/api/test_api_ui_sync_config.py
Backport: #626 
* Add field detailing if a write only value is set or not.
Issue: AAH-120
(cherry picked from commit c3e24a4ca79a5081e952774c1ae79b9e2a9b332c)
> Backport: Add field detailing if a write only value is set or not. (#626)

- CHANGES/393.misc
- galaxy_ng/app/api/v3/serializers/collection.py
- galaxy_ng/app/api/v3/views/sync.py
- galaxy_ng/app/api/v3/viewsets/collection.py
Pulpcore 3.10 introduced some breaking changes
- On serializers `highest_versions` has been removed out of the context
- On download_url `content_artifact` has been also moved out of context
- Sync now requires `optimize=True` attribute
And also some non-breaking changes
- Viewsets `retrieve` is not needed because distro_path is now part of pulp-ansible and can be removed from our side
- `self._deprecation` is not necessary (included by mistake on a
previous PR)
Issue: AAH-393
> Fixing pulpcore 3.10+ breaking changes and renamings

- CHANGES/277.feature
- galaxy_ng/app/api/ui/serializers/__init__.py
- galaxy_ng/app/api/ui/serializers/execution_environment.py
- galaxy_ng/app/api/ui/urls.py
- galaxy_ng/app/api/ui/viewsets/__init__.py
- galaxy_ng/app/api/ui/viewsets/execution_environment.py
- setup.py
- Refactors container repo api paths to use more streamlined regex paths
- Add new api at `_ui/v1/execution-environments/repositories/{repo_path}/_content/images/` that returns a list of images in a repo.
- Add ability to filter images by tag and digest
- Add ability to sort images by `created`
API response
```
{
"meta": {
"count": 3
},
"links": {
"first": "/api/automation-hub/_ui/v1/execution-environments/repositories/ubuntu/_content/images/?limit=10&offset=0",
"next": null,
"last": "/api/automation-hub/_ui/v1/execution-environments/repositories/ubuntu/_content/images/?limit=10&offset=0"
},
"data": [
{
"pulp_id": "fb1fe61c-434f-4d4d-8c64-12d33d08258b",
"digest": "sha256:7d945d49c683b8ec367e86b010ab224199317d3fbf6461c448917a3fda17303d",
"schema_version": 2,
"media_type": …
```
> Add endpoint for returning images in a container repo.

- CHANGES/50.bugfix
- galaxy_ng/app/api/ui/viewsets/my_synclist.py
- galaxy_ng/app/settings.py
- galaxy_ng/app/tasks/synclist.py
Fix large number of enqueued synclist related tasks by doing the
following changes:
* Call `add_and_remove` tasks directly.
* Call `curate_synclist_repository` task in batches.
* Batch size is set to 200.
> Reduce excessive number of spawned synclist tasks

- galaxy_ng/app/api/ui/viewsets/my_synclist.py
> Fix wrong get_object_or_404 call in synclist curate

- CHANGES/276.feature
- galaxy_ng/app/api/ui/serializers/__init__.py
- galaxy_ng/app/api/ui/serializers/execution_environment.py
- galaxy_ng/app/api/ui/urls.py
- galaxy_ng/app/api/ui/viewsets/__init__.py
- galaxy_ng/app/api/ui/viewsets/execution_environment.py
Adds `_ui/v1/execution-environments/repositories/<container>/_content/history/` endpoint which returns a list of repository versions that have Tags or Manifests that has been added or removed from the registry.
```
{
"meta": {
"count": 1
},
"links": {
"first": "/api/automation-hub/_ui/v1/execution-environments/repositories/postgres/_content/history/?limit=10&offset=0",
"next": null,
"last": "/api/automation-hub/_ui/v1/execution-environments/repositories/postgres/_content/history/?limit=10&offset=0"
},
"data": [
{
"pulp_id": "41c336a1-bd53-478a-ad8a-e322bbed8794",
"added": [
{
"pulp_id": "12d401ca-0f4d-44cb-9230-2becdaf61348",
"pulp_type": "container.manifest",
"manifest_digest": "sha256:be73fdba6d4e542e5fd10abb5aef072cf2c52547ebd3e39dd72e6ca3f98c8233",
"tag_name": null …
```
> Add container repository history api.

- .compose.env.example
- CHANGES/387.misc
- Makefile
- compose
- dev/Dockerfile.base
- dev/docker-compose.yml
- dev/insights/Dockerfile
- dev/standalone/Dockerfile
- requirements/requirements.dev.txt
- setup.py
```make
❯ make         
Usage: make <target>
Targets:
help:             ## Show the help.
requirements:     ## Update python dependencies lock files (i.e. requirements.txt).
changelog:        ## Build the changelog
docker/build:     ## Build all development images.
docker/test:      ## Run unit tests.
docker/loaddata:  ## Load initial data from fixtures
docker/migrate:   ## Run django migrations
docker/resetdb:   ## Cleans database
api/get:          ## Make an api get request using 'httpie'
api/shell:        ## Opens django management shell in api container
api/bash:         ## Opens bash session in the api container
api/runserver:    ## Runs api using django webserver for debugging
```
deps branches.
- if `LOCK_REQUIREMENTS` is disabled, all deps listed on `DEV_SOURCE_PATH` is unppined …
> Add make targets for common tasks on dev env and support for env snapshots

- compose
`source` accepts only filenames on bash <3 and on Mac
So this new solution uses `eval` to evaluate the
result of grep and export only env vars from `.compose.env`
that was not already defined on the shell.
This works only on bash >3 and zsh **But doesn't work on a mac, because `source` and `sed` are different on mac bash**
```bash
source <(grep -v '^#' .compose.env | sed -E 's|^(.+)=(.*)$|: ${\1=\2}; export \1|g')
```
This works on bash<3 >3, bash and zsh  
```bash
eval "$(grep -v '^#' .compose.env | sed -E 's|^(.+)=(.*)$| export \1=${\1:-\2} |g' | xargs -L 1)"
```
Explained:
- grep `.compose.env` without comment lines
* `grep -v '^#' .compose.env`
- pass each grepped line to sed
- sed splits KEY=value in two groups `\1 and \2`
* `| sed -E 's|^(.+)=(.*)$|`
- we use that to build `export …
> Hotfix for compose.env load on bash <3 and on a Mac

- compose
reported by @himdel
```diff
- sed -E 's|^(.+)=(.*)$| export \1=${\1:-\2} |g'
+ sed -E 's|^(.+)=(.*)$|export \1=${\1:-\2}|g'
```
```bash
$ grep -v '^#' .compose.env | sed -E 's|^(.+)=(.*)$| export \1=${\1:-\2} |g' | xargs -L 1
export COMPOSE_PROFILE=${COMPOSE_PROFILE:-standalone} export DEV_SOURCE_PATH=${DEV_SOURCE_PATH:-galaxy_ng} export LOCK_REQUIREMENTS=${LOCK_REQUIREMENTS:-1} export ANSIBLE_HUB_UI_PATH=${ANSIBLE_HUB_UI_PATH:-/home/himdel/ansible-hub-ui}
```
then
```bash
$ grep -v '^#' .compose.env | sed -E 's|^(.+)=(.*)$|export \1=${\1:-\2}|g' | xargs -L 1 
export COMPOSE_PROFILE=${COMPOSE_PROFILE:-standalone}
export DEV_SOURCE_PATH=${DEV_SOURCE_PATH:-galaxy_ng}
export ANSIBLE_HUB_UI_PATH=${ANSIBLE_HUB_UI_PATH:-/home/rochacbruno/Projects/ansible-hub-ui}
```
No white space inside sed …
> [hotfix][dev-env] Extra space inside `sed` avoids new line creation.

- compose
Figured out how to dump the database from a running container...
./compose exec postgres pg_dump -U galaxy_ng galaxy_ng -Fc > pg.dump
Except that dump is invalid because it starts with the 4 INFO lines compose outputs.
Since the 5th line is only going to stderr, adding >&2 to the other INFO outputs as well.
Cc @rochacbruno
> compose: print INFO messages to stderr, not stdout

- CHANGES/409.feature
- galaxy_ng/app/api/ui/serializers/collection.py
Field `requires_ansible` is available in the following endpoints:
* /_ui/v1/repo/published/<namespace>/<collection_name>/
* /_ui/v1/repo/published/<namespace>/<collection_name>/?version=<#.#.#>
* /v3/collections/<namespace>/<collection_name>/versions/
* /v3/collections/<namespace>/<collection_name>/versions/<#.#.#>/
Issue: AAH-409
> Add requires_ansible to the collection api endpoints

- CHANGES/453.bugfix
- galaxy_ng/app/api/ui/viewsets/group.py
pulpcore 3.10.0 introduced [queryset_filtering_required_permission](https://github.com/pulp/pulpcore/blob/master/pulpcore/app/viewsets/user.py#L109)
attribute to GroupViewSet with a permission not used by galaxy_ng.
Currently it can not be overridden simply by setting to None,
so the attribute is removed from the subclass.
Issue: AAH-453
> Fix groups endpoint viewable only by admin

- galaxy_ng/app/api/v3/urls.py
- galaxy_ng/tests/unit/api/test_api_v3_collections.py
Endpoints are deactivated temporaty until
https://issues.redhat.com/browse/AAH-224 is resolved.
No-Issue
> Deactivate Unpaginated Sync Endpoints

- galaxy_ng/app/api/ui/urls.py
When a container contains a dash...
docker pull hello-world
docker image tag hello-world localhost:5001/hello-world
docker push localhost:5001/hello-world
docker image tag hello-world localhost:5001/whatever/hello-world
docker push localhost:5001/whatever/hello-world
the api request for `GET /api/automation-hub/_ui/v1/execution-environments/repositories/whatever/hello-world/` (or just `...repositories/hello-world/`)
returns a 404, because no route matches
Changing `\w+` to `[-\w]+` to allow dashes.
No-Issue
Cc @newswangerd , @ZitaNemeckova 
This is a follow-up to https://github.com/ansible/galaxy_ng/pull/658, to allow for dashes in container names. (Such as https://hub.docker.com/_/hello-world ).
(Docker allows to push to `hello-world/hello-world` as well, so added the dash to both the …
> urls: allow dashes in container names

- CHANGES/482.bugfix
- galaxy_ng/app/common/openapi.py
- galaxy_ng/app/settings.py
Without it, some of the playbooks that depend on the
https://github.com/ansible/galaxy_collection
collection will fail.
Issue: AAH-482
> Expose /pulp/api/v3/status in openapi as used by pulp squeezer

- CHANGES/486.bugfix
- docker/entrypoint.sh
This change should be removed once Pulp recognizes REDIS_SSL parameter when building settings for RQ in `pulpcore/rqconfig.py`
Issue: AAH-486
> Replace PULP_REDIS* env variables with PULP_REDIS_URL env variable

- CHANGES/489.bugfix
- requirements/requirements.common.txt
- requirements/requirements.insights.txt
- requirements/requirements.standalone.txt
- setup.py
Issue: AAH-489
But only Django, and not any deps updated by pip-compile.
Opening as new PR to compare CI results.
See https://github.com/ansible/galaxy_ng/pull/713  for full 'make requirements' diff.
> Update stable-4.2 branch to use Django 2.2.20  (AAH-489)

- CHANGES/478.misc
- galaxy_ng/app/settings.py
> Disable django guardian's anonymous user.

- dev/docker-compose.yml
Tested by removing the code from the #715 disaster and building a clean dev environment, uploading a collection and syncing Red Hat Certified.
No-Issue
> Upgrade postgresql in dev environment

- docker/entrypoint.sh
- Unset variable errors reported on line 100
- TCP port localhost:6379 not available
Issue: AAH-486
> Fix docker entrypoint errors introduced by #715

- CHANGES/431.bugfix
- requirements/requirements.common.txt
- requirements/requirements.insights.txt
- requirements/requirements.standalone.txt
- setup.py
Uses file_url from caller for remote storage to support additional
pulp backend storage types
AAH-431
> Upgrade galaxy-importer to 0.3.1

- setup.py
During the python package build:
- If the `ALTERNATE_UI_DOWNLOAD_URL` environment variable is set, attempt to download the specified UI.
- Attempt to download the version of the UI that matches the current version of the API.
- If no version can be found, download the UI from https://github.com/ansible/ansible-hub-ui/releases/tag/dev
This is a companion to https://github.com/ansible/ansible-hub-ui/pull/372, which provides a build of the master branch on the 'dev' github release.
> Download correct version of UI during package builds.

- Makefile
Use PIP_COMPILE_UPDATE_SPEC='-P pulp-container==2.5.1' to update
just pulp-container.
The default for PIP_COMPILE_UPDATE_SPEC is '-U' which
updates everything.
Issue: No-Issue
> Add PIP_COMPILE_UPDATE_SPEC to update specific packages on 'make requirements'

- setup.py
Pin django to 2.2.20 until https://pulp.plan.io/issues/8691 is resolved.
This fixes CI build issues for now.
No-Issue
> Temporarily pin django to 2.2.20

- CHANGES/584.misc
- setup.py
Pin django to 2.2.20 until https://pulp.plan.io/issues/8691 is resolved.
This fixes CI build issues for now.
No-Issue
(cherry picked from commit 57f3922f3fe7719c5da5519e2b0dafca3ccfb8e5)
This is in lieu of https://pulp.plan.io/issues/8691 or an upstream django fix for https://code.djangoproject.com/ticket/32718
> Temporarily pin stable 4.3 django==2.2.20 workaround

- .travis/before_install.sh
- CHANGES/563.misc
- requirements/requirements.common.txt
- requirements/requirements.insights.txt
- requirements/requirements.standalone.txt
- setup.py
Issue: AAH-563
(cherry picked from commit b8a8f3ae1d41bb886d4c85437db1c40ef6e8463d)
Note: This is going to fail CI until https://pulp.plan.io/issues/8691 is resolved and backported to pulpcore 3.11 branch.
> Update pulpcore dep to 3.11.1

- .travis/before_install.sh
- CHANGES/570.misc
- requirements/requirements.common.txt
- requirements/requirements.insights.txt
- requirements/requirements.standalone.txt
- setup.py
Issue: AAH-570
(cherry picked from commit 3e01e36ec0c8b7a4687d4c6bfca0f9efba1d8c1f)
Note: This is going to fail CI until https://pulp.plan.io/issues/8691 is resolved and backported to pulpcore 3.11 branch.
> Update pulp_ansible dep to 0.7.3

- dev/Dockerfile.base
In the dev docker environment, `compose build` takes ages, on the `chown -R ...` step.
That's because we have to chown every single python dependency that we just downloaded as root, fixing that.
Before:
(root) python -m venv /venv	# creates and populates a venv
(root) pip install ...		# installs deps in there
(root) chown -R galaxy /venv	# changes owner of all these files
After:
(root) mkdir /venv
(root) chown galaxy /venv	# while still empty
(galaxy) python -m venv /venv
(galaxy) pip install		# no chown for these
We can also skip chowning `/app`, using `COPY --chown` instead.
`django-admin collectstatic` needs to run as root however (fails on `/var/lib/pulp` access otherwise),
and keeping the final chown for the rest of the files.
No-Issue
---
Running the original version except with …
> dev/Dockerfile.base: install python deps as galaxy user, don't chown after

- CHANGES/583.bugfix
- CHANGES/584.misc
- CHANGES/601.bugfix
- requirements/requirements.common.txt
- requirements/requirements.insights.txt
- requirements/requirements.standalone.txt
- setup.py
Bump from LTS 2.2.20 to 2.2.23
2.2.21 included some security improvements but
also a new django bug that caused a bug in pulpcore
https://pulp.plan.io/issues/8691
2.2.22 has fix for:
CVE-2021-32052 django: header injection possibility
since URLValidator accepted newlines in input on Python.
But 2.2.22 still had the bug introduced in 2.2.21
2.2.23 resolves the issue that causes
https://pulp.plan.io/issues/8691
Issue: AAH-601
Issue: AAH-583
Issue: AAH-584
> Rev to django~=2.2.23 for cve and bug fixes.

- CHANGES/637.bugfix
- requirements/requirements.common.txt
- requirements/requirements.insights.txt
- requirements/requirements.standalone.txt
- setup.py
pulpcore uses 'rq' which uses 'click'.
click version 8.0.0 or higher don't work with
python < 3.8 and we currently use python~=3.6
If click>=8.0.0 is used with python 3.6. it will
eventually raise an exception like:
ValueError: 'default' must be a list when 'multiple' is true.
See https://pulp.plan.io/issues/8744
> Pin click==7.1.2, click>=8.0.0 req py38

- CHANGES/581.misc
- docker/entrypoint.sh
Update to only populate PULP_REDIS_URL if the relevant PULP_REDIS_* environment variables are set.
Issue: AAH-581
> Update Redis connection settings

- galaxy_ng/app/migrations/0017_populate_repos_and_remotes.py
When [galaxy_collection](https://github.com/ansible/galaxy_collection/blob/devel/roles/post_install_config/vars/main.yml#L21-L22) is used on provisioning the 4.2 system it creates a distribution having.
```
base_path: 'rh-certified'    
name: 'red-hat-certified'
```
Then when 4.3 migrations run it tries to fetch existing distribution using the `name` as the key.
```py
AnsibleDistribution.get_or_create(name="rh-certified", defaults={base_path="rh-certified", ...})
```
The problem is that the name in DB is `red-hat-certified` so the above `get_or_create` will fail to `get` and so 
will try to create a new distribution using `name=rh-certified, base_path=rh-certified` and this will raise `IntergrityError` on db because `base_path` is unique.
The simplest solution is to use `base_path` …
> Change migration to use base_path for Distribution

- CHANGES/582.feature
- openshift/clowder/clowd-app.yaml
- pr_check.sh
~~Draft PR until #776, #786 are merged.~~ Merged.
Issue: AAH-582
> Deploy to ephemeral env in pr_check

- requirements/requirements.common.txt
- requirements/requirements.insights.txt
- requirements/requirements.standalone.txt
- setup.py
This is currently breaking pulp-operator
https://github.com/pulp/pulp-operator/runs/2652733659?check_suite_focus=true
pulp-container 2.6 requires pulpcore >=3.12.1
https://github.com/pulp/pulp_container/blob/2.6.0/requirements.txt
> Pin pulp-container

- requirements/requirements.common.txt
- requirements/requirements.insights.txt
- requirements/requirements.standalone.in
- requirements/requirements.standalone.txt
- setup.py
- Remove pulp container
- Update to latest django LTS
- Pin to pulp core 3.7
No-Issue
> Remove pulp-container from 4.2.

- CHANGES/224.misc
- docker/etc/settings.py
- galaxy_ng/app/api/v3/urls.py
Streamed andpoints enabled on https://github.com/pulp/pulp_ansible/pull/586
Requires PR: https://github.com/pulp/pulp_ansible/pull/586
Issue: AAH-224
> Re-Enable /collections/all/ endpoints (now streamed)

- docker/etc/settings.py
- pr_check.sh
This change replaces call to `_deploy_ephemeral_env.sh` script
with it's contents and adds additional required `--no-remove-resources`
parameter to the `bonfire deploy` call.
No-Issue
> Workaround bonfire stripping resource limits of ClowdApp

- dev/insights/docker-compose-ui.yaml
Running the insights mode, the *host* `/etc/hosts` should contain these:
127.0.0.1 prod.foo.redhat.com
127.0.0.1 stage.foo.redhat.com
127.0.0.1 qa.foo.redhat.com
127.0.0.1 ci.foo.redhat.com
Under some circumstances, the host `/etc/hosts` get mounted inside the container as well, having the container see the same hosts as the host machine.
Under other circumstances, this doesn't happen, and the container `/etc/hosts` is missing these entries.
That causes..
insights_proxy_1    | GET /beta/ansible/automation-hub from https://ui:8002/beta/ansible/automation-hub
insights_proxy_1    | An error occurred while resolving an ESI tag for the ci.foo.redhat.com host
insights_proxy_1    | { [While requesting GET|https://ci.foo.redhat.com:1337/apps/chrome/snippets/body.html|Accept:text/html, …
> insights/docker-compose-ui: add *.foo.redhat.com extra_hosts

- .github/workflows/scripts/check_commits.py
This keeps changelog entries as a one-line summary of the change, since there is a link to the issue that gives more background, otherwise its hard to review a summary of changes ex: https://github.com/ansible/galaxy_ng/blob/master/CHANGES.rst#430a2-2021-04-16
> Enforce that each changelog entry is a single line

- docker/etc/settings.py
- openshift/clowder/clowd-app.yaml
* Add required `PULP_RH_ENTITLEMENT_REQUIRED` environment variable.
* Set pulp-content-app listen port to Clowder's private
webService port (`10000`).
* Configure pulp-content-app host:port for galaxy-api.
* Remove redundant `GALAXY_DEPLOYMENT_MODE` from container settings.py.
* Add `ANSIBLE_API_HOSTNAME` parameter to be set based on
`CONTENT_ORIGIN`
No-Issue
> Clowder: Update port numbers and settings

- galaxy_ng/app/webserver_snippets/apache.conf
scheme is handled by pulp_installer,
${pulp-api} already includes http or https
https://github.com/pulp/pulp_installer/blob/master/roles/pulp_webserver/templates/pulp-vhost.conf.j2#L1-L2
https://github.com/pulp/pulp_installer/blob/master/roles/pulp_webserver/vars/main.yml#L3-L4
related to https://pulp.plan.io/issues/8130
> Fix apache snippet

- dev/Dockerfile.base
No-Issue
This builds on #731. 
Use `mkdir --mode` to make most of the dirs group 'sticky' so group perms stick, so user can continue to write to subdirs even if ROOT unintentionally creates dirs 0755. 
Some rearranging of dir creation order so we can create parent dirs first so we can make them group sticky.
For `/var/lib/pulp` for example, this removes the need for a `chown -R /var/lib/pulp`.
On top of #731, it seems to shave about ~25secs off a `./compose build` down to about ~1m15sec.  Down from about ~3m30s before either #731 or this change.
> Speedup dev docker builds by using g+s to avoid chown -R

- CHANGES/606.misc
- galaxy_ng/app/api/v3/urls.py
- galaxy_ng/app/api/v3/views/__init__.py
- galaxy_ng/app/api/v3/views/excludes.py
pulp_ansible sync is going to try a fetch on `{REMOTE}/<path>/excludes/`
this endpoint returns the consolidated synclist for exclude policy.
ex:
Given a synclist distro: `/api/automation-hub/content/5910538-synclist/`
Collections served at: `/api/automation-hub/content/5910538-synclist/v3/collections/`
Excludes served at: `/api/automation-hub/content/5910538-synclist/v3/excludes/`
Accept: application/json
```json
{
"collections": [
{
"name": "newswangerd.collection_demo"
},
{
"name": "fernandomorais.kubernetes_fork"
}
]
}
```
Accept: application/yaml
```yaml
collections:
- name: newswangerd.collection_demo
- name: fernandomorais.kubernetes_fork
```
Issue: AAH-606
> Add endpoint to return the /excludes/ list from synclists.

- CHANGES/157.bugfix
- galaxy_ng/app/api/views.py
The api call:
```bash
❯ http :8002/api/automation-hub/content/anything_can_be_passed_here/
```
Before:
```
{
"available_versions": { "v3": "v3/" },
"distro_base_path": "anything_can_be_passed_here",
"galaxy_ng_version": "4.2.0",
"pulp_ansible_version": "0.5.0",
"server_version": "4.2.0"
}
```
Now:
```bash
{
"errors": [
{
"status": "404",
"code": "not_found",
"title": "Not found."
}
]
}
```
If an existing distro is requested
```bash
{
"available_versions": {
"v3": "v3/"
},
"server_version": "4.4.0dev",
"galaxy_ng_version": "4.4.0dev",
"pulp_ansible_version": "0.7.3",
"distro_base_path": "5910538-synclist"
}
```
If no distro_bse_path is provided
```bash
GET /api/automation-hub/
{
"available_versions": {
"v3": "v3/"
},
"server_version": "4.4.0dev",
"galaxy_ng_version": "4.4.0dev", …
```
> Make the API Root view to raise 404 if distro doesn't exist.

- CHANGES/646.bugfix
- galaxy_ng/app/api/ui/viewsets/collection.py
Issue https://issues.redhat.com/browse/AAH-646
Implemented state and keyword filters for imports API.
Request URL: 
http://localhost:8002/api/automation-hub/_ui/v1/imports/collections/?namespace=ibm&keywords=ibm&state=completed&sort=-created&offset=0&limit=10
> Fix imports filter

- CHANGES/603.misc
- requirements/requirements.common.txt
- requirements/requirements.insights.txt
- requirements/requirements.standalone.txt
- setup.py
Remove `click` from our requirements list, it's no longer needed after updating to Python 3.8
Issue: AAH-603
> Remove click requirement

- Makefile
This allows for updating requirements using just local files (setup.py and requirements.*.in)
`make requirements/update_local`
Updating just one package via pip
`make requirements/update_local_and_pip_param package=click`
Updating all packages via pip
`make requirements/update_local_and_pip_all`
> Add make endpoint that updates requirements without using pip

- .travis/before_install.sh
- requirements/requirements.common.txt
- requirements/requirements.insights.txt
- requirements/requirements.standalone.txt
- setup.py
Due to a breaking change with the pulpcore 3.14 bindings 
we made:
pulp-ansible 0.8.1: pulpcore>=3.12.1,<3.14
pulp-ansible 0.9.0: pulpcore>=3.14,<3.15
https://docs.pulpproject.org/pulp_ansible/changes.html#changelog
> Bump pulp-ansible to 0.9.0

- CHANGES/739.bugfix
- galaxy_ng/app/models/namespace.py
- galaxy_ng/tests/unit/test_models.py
This will create a new Repository and Distribution for every
Namespace in Galaxy.
Issue: AAH-739
> Create per namespace inbound repos on all namespace creation

- setup.py
Allows users to run `python setup.py prepare_static` with a `--force-download-ui` flag that removes any existing static files and re downloads them from github.
This will be used for setting up the UI in the pulp dev environment.
> Add option to override existing UI when downloading UI from github

- galaxy_ng/app/api/ui/serializers/execution_environment.py
- galaxy_ng/app/api/v3/serializers/sync.py
- galaxy_ng/app/api/v3/viewsets/collection.py
Pulp now uses `pulp_id` for task IDs, instead of `id`
> Update tasks to use pulp_id instead of id.

- .github/workflows/scripts/post_before_script.sh
- CHANGES/830.misc
- MANIFEST.in
- galaxy_ng/app/access_control/access_policy.py
- galaxy_ng/app/access_control/fields.py
- galaxy_ng/app/api/base.py
- galaxy_ng/app/api/ui/serializers/synclist.py
- galaxy_ng/app/api/ui/serializers/user.py
- galaxy_ng/app/api/ui/viewsets/collection.py
- galaxy_ng/app/api/ui/viewsets/group.py
- galaxy_ng/app/api/utils.py
- galaxy_ng/app/api/v3/serializers/namespace.py
- galaxy_ng/app/api/v3/serializers/sync.py
- galaxy_ng/app/api/v3/views/sync.py
- galaxy_ng/app/api/v3/viewsets/collection.py
- galaxy_ng/app/api/v3/viewsets/namespace.py
- galaxy_ng/app/settings.py
- galaxy_ng/app/tasks/publishing.py
- galaxy_ng/app/tasks/synclist.py
- galaxy_ng/locale/es/LC_MESSAGES/django.po
- galaxy_ng/locale/fr/LC_MESSAGES/django.po
- galaxy_ng/locale/ja/LC_MESSAGES/django.po
- galaxy_ng/locale/nl/LC_MESSAGES/django.po
- galaxy_ng/locale/zh/LC_MESSAGES/django.po
- galaxy_ng/tests/unit/api/test_localization.py
Issue: [AAH-830](https://issues.redhat.com/browse/AAH-830)
Marked most of the strings for translation and added gettext_lazy import, but I'm not sure about these translations:
- `self.stdout.write`
- `self.status_messages.append`
- `parser.add_argument('name', type=slugify, help=_("Remote Name"))`
- `log.info, log.debug, log.warning`
> Mark API strings for translation

- .github/workflows/nightly_latest.yml
- .github/workflows/scripts/post_before_install.sh
- CHANGES/871.misc
This is already possible to run a PR CI checks using specific pull-request for repos,
for example, one can add:
```bash
Required PR: https://github.com/pulp/pulpcore/pulls/456
Required PR: https://github.com/ansible/galaxy-importer/pulls/999
```
And the CI will checkout to that specific PR before installing and running the tests.
Right now on galaxy_ng if you try it, you will get a **failure on installation** because pip will Conflict on deps version, to solve that add to commit msg also `env:LOCK_REQUIREMENTS=0` and this will work similar to what we have on our docker based environment, it will remove the pinned versions from galaxy_ng/setup.py and allow pip to install.
So the commit message would contain:
```bash
Required PR: https://github.com/pulp/pulpcore/pulls/456
Required PR: …
```
> Allow running latest/main branches or revision on PR CI.

- .gitleaks.toml
- openshift/clowder/clowd-app.yaml
- openshift/database-migration.yaml
Mount pulp encryption secret in ClowdApp and database migration
template.
NOTES:
1. For stage and production deployment a secret must exist
before the deployment is executed.
2. Migtation template ref must be updated along with image tag
in the app-interface to pick up changes in this commit.
No-Issue
> Clowder: Add pulp encryption secret

- galaxy_ng/app/__init__.py
- galaxy_ng/app/access_control/access_policy.py
- galaxy_ng/tests/unit/api/synclist_base.py
Tl:DR; 
```py
from galaxy_ng.app.access_control.statements import PULP_CONTAINER_VIEWSETS, ANYTHINGELSE
```
---
Galaxy has a custom accesscontrol statements module
if that module is imported before the django settings is configured
by pulp/dynaconf, then it is impossible to access settings on that
module.
It is also safer to load extra-django things only after the app.ready()
is executed.
No-Issue
> galaxy custom access control statements should be lazily loaded.

- Makefile
- dev/standalone/Dockerfile
The `gettext` package is needed to be able to run `django-admin makemessages` in order to extract strings.  This PR adds that dependency to the dev/standalone/Dockerfile, which appears to be a wrapper around the galaxy_ng base image.  
I built it locally and it works:
```
[galaxy@d8cb2f9d6dc0 /]$ dnf list installed | grep gettext
gettext.x86_64                                0.19.8.1-17.el8                         @ubi-8-baseos   
gettext-libs.x86_64                           0.19.8.1-17.el8                         @ubi-8-baseos 
```
Using the following steps, I am now able to extract strings successfully:
```
git clone 
cd galaxy_ng
cp .compose.env.example .compose.env
./compose build
./compose run --rm api bash -c "cd /app/galaxy_ng && django-admin makemessages --all"
```
> gettext is needed by localization automation to extract strings

- openshift/clowder/clowd-app.yaml
Secrets data in OpenShift \ K8S must be base64 encoded.
No-Issue
> Clowder: Fix pulp encryption key value

- galaxy_ng/app/__init__.py
- galaxy_ng/app/models/collectionsync.py
- galaxy_ng/app/signals/__init__.py
- galaxy_ng/app/signals/handlers.py
Strictly speaking, signal handling and registration code can live anywhere you like, although it’s
recommended to avoid the application’s root module and its models module to minimize side-effects
of importing code.
In practice, signal handlers are usually defined in a signals submodule of the application they
relate to. Signal receivers are connected in the ready() method of your application configuration
class. If you’re using the receiver() decorator, simply import the signals submodule inside
ready().
https://docs.djangoproject.com/en/3.2/topics/signals/
https://stackoverflow.com/a/22924754
No-Issue
> Move signals to its own module and load on app.ready()

- requirements/requirements.common.txt
- requirements/requirements.insights.txt
- requirements/requirements.standalone.txt
- setup.py
This PR also removes the temporary pulpcore source checkout debugging
No-Issue
> Upgrade to pulpcore==3.14.6 to fix OpenShift deploys

- galaxy_ng/app/api/views.py
Currently APIRoot shows only versions for galaxy and pulp_ansible,
as we added dependency on more plugins it is useful to get the
isntalled versions for core, container and importer.
No-Issue
> Surface versions of all plugins on APIRoot

- CHANGES/709.feature
- galaxy_ng/app/access_control/statements/insights.py
- galaxy_ng/app/access_control/statements/standalone.py
- galaxy_ng/app/api/ui/serializers/user.py
- galaxy_ng/app/api/v3/viewsets/namespace.py
- galaxy_ng/tests/unit/api/base.py
- galaxy_ng/tests/unit/api/test_api_v3_namespace_viewsets.py
Allow DELETE requests on `/api/automation-hub/v3/namespaces/<name>/`
path.
1. Perform a check to see if there are any collections in the namespace.
If there are, return a failure.
2. Delete the inbound pulp distro and repository
3. Delete the namespace object.
return: Response(status=204)
NOTES:
- DELETE endpoints doesn't accept payload
- Return doesn't include a pulp task id as Namespace is on galaxy_ng and
deleted only after the collection dependents check is performed, there is no pulp_task involved.
Issue: AAH-709
> Add endpoint for namespace deletion

- .gitleaks.toml
The `files` only variable only looks at individual file names, regardless of path.  We should be using the `path` variable here in the `.gitleaks.toml` conf.
> Use paths, not files syntax for gitleaks

- Makefile
- dev_requirements.txt
- functest_requirements.txt
- galaxy_ng/app/management/commands/create-test-collections.py
- galaxy_ng/tests/constants.py
- galaxy_ng/tests/unit/api/test_api_v3_collections.py
- pyproject.toml
- requirements/requirements.dev.txt
- unittest_requirements.txt
Before `make help` would output targets and summary in the same line and was difficult to keep aligned.
Now `make help` adds a newline between the targets and summary.
```bash
Usage: make <target>
Targets:
help:             
requirements/no-pip-upgrade:     
requirements/pip-upgrade-single-package:     
requirements/pip-upgrade-all:     
changelog:        
lint:             
fmt:              
docker/prune:     
docker/build:     
docker/test:      
docker/loaddata:  
docker/migrate:   
docker/resetdb:   
docker/translations:   
docker/all: 	                                
api/get:          
api/shell:        
api/bash:         
api/runserver:    
api/routes:       
api/create-test-collections:   
```
To lint the code we already use `flake8 --config=flake8.cfg`, this command has been …
> Improvements on Makefile + collection generation for testing.

- CHANGES/896.feature
- galaxy_ng/app/access_control/access_policy.py
- galaxy_ng/app/access_control/statements/standalone.py
- galaxy_ng/app/api/ui/viewsets/execution_environment.py
Issue: AAH-896
See Jira Issue: https://issues.redhat.com/browse/AAH-896
The pr creates the access policy for the container registries endpoint. 
* Allows authenticated users to view registries
* Allows users with model create permissions to create new registries
* Allows users with model update permissions to update registries
* Prevents deletion
> create access policy for container registries endpoint

- dev/Dockerfile.base
- dev/standalone/Dockerfile
Adds logging file with permissions and owner.  Now a dev only needs to update the `GALAXY_ENABLE_API_ACCESS_LOG` to enable logging in the container dev environment.
No-Issue
> Add configuration for API access logging to dev environment

- dev/insights/docker-compose.yml
- dev/standalone-keycloak/docker-compose.yml
- dev/standalone/docker-compose.yml
docker compose allows `env_file` to be a list of .env files
those files are loaded in order.
It makes easier to have custom local settings.
Ex:
`.compose.env`
```bash
PULP_GALAXY_ENABLE_API_ACCESS_LOG=true
```
will enable logs to be written to `/var/log/galaxy_api_access.log`
No-Issue
> Pass .compose.env variables to the containers

- CHANGES/881.feature
- galaxy_ng/app/access_control/access_policy.py
- galaxy_ng/app/access_control/mixins.py
- galaxy_ng/app/access_control/statements/standalone.py
- galaxy_ng/app/api/ui/serializers/user.py
- galaxy_ng/app/api/ui/views/auth.py
- galaxy_ng/app/api/ui/viewsets/user.py
- galaxy_ng/app/api/v3/viewsets/collection.py
- galaxy_ng/app/settings.py
- galaxy_ng/tests/unit/api/test_view_only_access.py
- galaxy_ng/tests/unit/api/test_view_only_collections.py
Set the `GALAXY_ENABLE_VIEW_ONLY_ACCESS` in `galaxy_ng/app/settings.py` to `True` and load Hub.
Issue: AAH-881
> Enable view-only collection browsing

- CHANGES/917.misc
- galaxy_ng/app/api/ui/urls.py
- galaxy_ng/app/api/ui/views/__init__.py
- galaxy_ng/app/api/ui/views/settings.py
- galaxy_ng/tests/unit/api/test_api_ui_settings.py
Add '_ui/v1/settings' endpoint to expose `GALAXY_ENABLE_UNAUTHENTICATED_COLLECTION_ACCESS` and `GALAXY_ENABLE_UNAUTHENTICATED_COLLECTION_DOWNLOAD` to the UI
Depends on #909 for the settings above to be defined.
Issue: AAH-917
> Add '_ui/v1/settings' endpoint

- Makefile
- galaxy_ng/app/management/commands/create-test-collections.py
As part of my other PR #939 I needed to generated fake data for testing, I added here some improvements as I needed.
```bash
$ django-admin create-test-collections --strategy=faux --ns=1 --cols=4
You are about to populate the system with 4 test collections.
This operation cannot be undone
Proceed? (Y/n)y
Created namespace ycafiztl
/api/automation-hub/v3/namespaces/ycafiztl/
{'task': '/api/automation-hub/content/inbound-ycafiztl/v3/imports/collections/c5ec2222-9f38-431e-80c1-75dde8d75efb/'}
Collection 'kczhvlinrd' created
/api/automation-hub/content/published/v3/collections/ycafiztl/kczhvlinrd/versions/3.6.2/
A new version for 'kczhvlinrd' created
/api/automation-hub/content/published/v3/collections/ycafiztl/kczhvlinrd/versions/3.6.3/
Collection 'rmgrjelkbw' created …
```
> Fixes to the script that generates fakes collections for testing.

- CHANGES/901.feature
- dev/standalone-keycloak/galaxy_ng.env
- dev/standalone/galaxy_ng.env
- galaxy_ng/app/dynaconf_hooks.py
- galaxy_ng/app/settings.py
Issue: https://issues.redhat.com/browse/AAH-901
Controller needs basic authentication on the galaxy APIs so they can use registry credentials to query our api.
> Enable basic (username/password) authentication for galaxy apis.

- CHANGES/712.feature
- CHANGES/713.feature
- Makefile
- galaxy_ng/app/access_control/statements/standalone.py
- galaxy_ng/app/api/ui/urls.py
- galaxy_ng/app/api/ui/viewsets/execution_environment.py
- galaxy_ng/app/tasks/deletion.py
- galaxy_ng/app/viewsets.py
Issue: AAH-712
Issue: AAH-713
Added support for `DELETE` request on routes:
```bash
/api/automation-hub/_ui/v1/execution-environments/repositories/<base_path>/
/api/automation-hub/_ui/v1/execution-environments/repositories/<base_path>/_content/images/<str:manifest_ref>/
```
**plus**
Added a `make api/push-test-images` to feed system with some images for manual testing,
It is not possible **yet** to automate container testing as it is pending on #937
So this PR relies on manual testing only.
> Add Container Repo and Container Image Deletion

- galaxy_ng/app/api/v3/serializers/collection.py
No-Issue
I filed an issue in redmine, before figuring out this is a galaxy_ng problem: https://pulp.plan.io/issues/9405. Do you need me to create and link this to a jira issue? 
Also, are there tests for the V3 unpaginated endpoints? I ran into this issue while trying to implement synclist on the AH staging environment.
> Fix download url for V3 unpaginated collection versions endpoint

- CHANGES/938.feature
- galaxy_ng/app/api/ui/viewsets/execution_environment.py
This pr adds additional fields to the sorting feature, namely `created_at` and `updated_at`.
See issue: https://issues.redhat.com/browse/AAH-925
> add additional filters to container registries endpoint

- galaxy_ng/app/api/ui/urls.py
Repository endpoints need to be under _content/ so that they can detect `/` in repo names
> Move repository sync endpoint to _content/sync/

- CHANGES/864.feature
- galaxy_ng/app/access_control/statements/standalone.py
- galaxy_ng/app/api/ui/serializers/execution_environment.py
- galaxy_ng/app/api/ui/urls.py
- galaxy_ng/app/api/ui/views/__init__.py
- galaxy_ng/app/api/ui/views/index_execution_environments.py
- galaxy_ng/app/models/container.py
- galaxy_ng/app/tasks/__init__.py
- galaxy_ng/app/tasks/index_registry.py
Add `_ui/v1/execution-environments/registries/{registry_pk}/index/` endpoint.
```
curl \
-X POST \
-H 'Content-Type: application/json' \
curl_flags  -u admin:admin \
http://localhost:5001/api/automation-hub/_ui/v1/execution-environments/registries/{registry_pk}/index/
```
Launches a task that:
- Checks if the registry is indexable (for now, that just means that it's a red hat registry instance)
- Launches a task that reaches out to catalog.redhat.com and pulls a list of execution environments
- For each EE in the response, launch a task that creates a new remote repository in the registry.
> Enable indexing EEs from Red Hat Registry

- galaxy_ng/app/api/ui/serializers/execution_environment.py
No-Issue
Motivation:
> @himdel  after deleting a container image (just one image) I'm getting an error for all subsequent calls of the /_content/images endpoint..
```bash
api_1          | pulp [None]: django.request:ERROR: Internal Server Error: /api/automation-hub/_ui/v1/execution-environments/repositories/mysql/_content/images/
api_1          | Traceback (most recent call last):
api_1          |   File "/venv/lib64/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
api_1          |     response = get_response(request)
api_1          |   File "/venv/lib64/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
api_1          |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
api_1          |   File …
```
> Fix ManifestSerializer when image is deleted.

- CHANGES/952.bugfix
- galaxy_ng/app/api/ui/serializers/user.py
- galaxy_ng/app/api/ui/views/settings.py
Issue: AAH-952
Assignment: Add auth_provider to users/ endpoint to denote an SSO user
See on Jira: https://issues.redhat.com/browse/AAH-952
Creates a new serializer method field, "auth_provider" that checks to see if the user is an SSO user. If so, method returns the SSO provider; if not it returns "django" as a string.
> Add auth_provider to users/ endpoint to denote an SSO user

- galaxy_ng/locale/fr/LC_MESSAGES/django.po
- galaxy_ng/locale/ja/LC_MESSAGES/django.po
- galaxy_ng/locale/zh/LC_MESSAGES/django.po
> This PR pulls in newly translated strings. They were pushed on October 15th. I expect these will need to be backported to 4.4.
Supersed of https://github.com/ansible/galaxy_ng/pull/1040
> Localization: Update translated strings

- CHANGES/1095.bugfix
- galaxy_ng/app/api/ui/viewsets/execution_environment.py
* Fix container deletion for remote repos
Issue: AAH-1095
* Add reservation on remote.
* Fix flake8
(cherry picked from commit a06a621ff4835fe99f8578d269113f4009208e6b)
> Fix container deletion for remote repos (#1045)

- openshift/clowder/clowd-app.yaml
The galaxy-importer uses a quay image to run ansible-test sanity as an
openshift job. This change allows this image tag to be set in our
config.
No-Issue
> Clowder: support IMPORTER_IMAGE_TAG to be defined in config

- openshift/clowder/clowd-app.yaml
The galaxy-importer uses a quay image to run ansible-test sanity as an
openshift job. This change allows this image tag to be set in our
config.
No-Issue
> Support IMPORTER_IMAGE_TAG to be defined in config (#1060)

- CHANGES/1094.bugfix
- galaxy_ng/app/api/ui/views/sync.py
Issue: [AAH-1094](https://issues.redhat.com/browse/AAH-1094)
This fixes the API part of issue AAH-1094.
Task field `reserved_resources_record` doesn't get populated on `galaxy_ng.app.tasks.registry_sync.sync_all_repos_in_registry` action. But we still can get the value from `kwargs` field and return `last_sync_field` which is needed for Registry sync status on UI.
> Fix last_sync_task field on sync_all_repos_in_registry task

- dev/common/docker-compose-ui.yaml
- dev/docker-compose.yml
`swagger_ui`: remove `container_name` to fix clashes when using `DEV_IMAGE_SUFFIX`:
ERROR: for swagger-ui  Cannot create container for service swagger-ui: Conflict. The container name "/swagger_ui_container" is already in use by container "ecabb771316cbcdc7310a2329ceda2e9a38680f998f45a4e3fd9332d973b1377". You have to remove (or rename) that container to be able to reuse that name.
ERROR: Encountered errors while bringing up the project.
￼
and mount `/hub/app/node_modules` as tmpfs, instead of a readonly volume, to let npm write .cache to fix:
ui_1              | [webpack-cli] [Error: ENOENT: no such file or directory, mkdir '/hub/app/node_modules/.cache'] {
ui_1              |   errno: -2,
ui_1              |   code: 'ENOENT',
ui_1              |   syscall: 'mkdir',
ui_1              | …
> Fix insights dev mode ui failing to write /hub/app/node_modules/.cache

- .github/post-job-template.yml.j2
- .github/workflows/ci.yml
- CHANGES/804.misc
Issue AAH-804
Related to https://github.com/ansible/ansible-hub-ui/pull/1144
lint-po is released as https://pypi.org/project/lint-po/,
so just adding a task to install and run it (and re-running `plugin-template --github galaxy_ng`) :)
> ci workflow: add a lint-po task to run gettext linter

- galaxy_ng/app/api/ui/serializers/collection.py
```
Traceback (most recent call last):
File "/usr/local/lib/pulp/bin/pulpcore-manager", line 33, in <module>
sys.exit(load_entry_point('pulpcore', 'console_scripts', 'pulpcore-manager')())
File "/var/lib/pulp/devel/pulpcore/pulpcore/app/manage.py", line 11, in manage
execute_from_command_line(sys.argv)
File "/usr/local/lib/pulp/lib64/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
utility.execute()
File "/usr/local/lib/pulp/lib64/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
django.setup()
File "/usr/local/lib/pulp/lib64/python3.8/site-packages/django/__init__.py", line 24, in setup
apps.populate(settings.INSTALLED_APPS)
File "/usr/local/lib/pulp/lib64/python3.8/site-packages/django/apps/registry.py", …
```
> Fix pulp_installer CI error

- Makefile
bash has it's own version of the test(1) command (`[`),
but sh will use `/bin/test`
`/bin/test` does not support `==` for string comparison, `=` is correct
bash test supports both
=> running make anything with non-bash /bin/sh causes:
$ make dev/bumpversion-patch
/bin/sh: 1: [: unexpected operator
fixing to use `=` and be sh compatible
No-Issue
> Makefile: fix bashism

- .github/workflows/nightly_latest.yml
I'm investigating why pulp_installer CI raises errors while nightly latest workflow don't
https://github.com/ansible/galaxy_ng/pull/1086#issuecomment-1005604275
Keeping the logs for successful runs will help with the investigation
> Keep logs for nightly latest

- CHANGES/1097.misc
- galaxy_ng/tests/integration/api/test_artifact_upload.py
- galaxy_ng/tests/integration/conftest.py
- openshift/clowder/clowd-app.yaml
* Update openshift galaxy-importer config to require a tag from a tag list
* Update integration tests to include a required tag in collections
Issue: AAH-1097
> Update cloud config to check for required tags

- galaxy_ng/app/api/ui/viewsets/my_synclist.py
Fix dispatch call for synclist curate to use new param
No-Issue
> Fix dispatch call for synclist curate to use new param

- CHANGES/1212.misc
- openshift/clowder/deploy-acceptance.yaml
Issue: AAH-1212
Add job template to be referenced by the post-deploy-test.yml saas file, which will run the job after a successful deploy to the stage environment.
> Cloud: add post deploy tests template

- CHANGES/1254.bugfix
- galaxy_ng/app/api/v3/serializers/sync.py
Issue: [AAH-1254](https://issues.redhat.com/browse/AAH-1254)
On authenticating with proxy credentials, if in `write_only_fields` `proxy_password` is set to True and `proxy_password` is empty in update request (`api/automation-hub/content/community/v3/sync/config/`), there is an error from pulp, because of missing `proxy_password`, so we add the existing `proxy_password` from DB to the request.
> Add missing proxy_password to the request on update

- CHANGES/1395.bugfix
- galaxy_ng/app/api/v3/viewsets/collection.py
- galaxy_ng/app/tasks/synclist.py
Use shared_resources on calling parent task `curate_all_synclist_repository`
and calling child task `curate_synclist_repository_batch`. This prevents
golden_repo from being written to by another task.
Issue: AAH-1395
> Update locks on synclist tasks

- CHANGES/1399.bugfix
- galaxy_ng/app/auth/auth.py
Only attempt to create synclist object if it does not exist. This allows
a group to be associated with a synclist object that already exists.
Issue: AAH-1399
> Check for existing synclist obj before create in RH Auth

- CHANGES/1278.misc
- galaxy_ng/app/access_control/access_policy.py
- galaxy_ng/app/access_control/statements/insights.py
- galaxy_ng/app/api/ui/urls.py
- galaxy_ng/app/api/ui/views/__init__.py
- galaxy_ng/app/api/ui/views/landing_page.py
- galaxy_ng/tests/integration/api/test_landing_page.py
Issue: [AAH-1278](https://issues.redhat.com/browse/AAH-1278)
This commit adds the endpoints for the landing page on the console.redhat.com. It is going to be a self service so all
the dynamic data should be prefilled: collection and partner  in the current case.
Next after this is deployed to STAGE by this [document](https://issues.redhat.com/browse/RHCLOUD-17405)
* I'll contact the platform to add this endpoint to chrome
* After they add the endpoint QE can verify the looks and data displayed on STAGE 
---
The currently used schema is here: https://github.com/RedHatInsights/landing-page-frontend/blob/b1f358352916f3f6b4813e9cfe0b4a7765005109/src/contentApi/ansible-api.js#L500
The expected prefilled format example: https://github.com/RedHatInsights/landing-page-frontend/blob/master/docs/exm …
> Add landing page endpoint for the console redhat

- CHANGES/1278.misc
- galaxy_ng/app/access_control/access_policy.py
- galaxy_ng/app/access_control/statements/insights.py
- galaxy_ng/app/api/ui/urls.py
- galaxy_ng/app/api/ui/views/__init__.py
- galaxy_ng/app/api/ui/views/landing_page.py
- galaxy_ng/tests/integration/api/test_landing_page.py
* Add landing page endpoint for the console.redhat
Issue: AAH-1278
This commit andds the endpoints for the landing page on the
console.redhat.com. It is going to be a self service so all
the dynamic data should be prefilled: collection and partner
count in the current case.
* Add integration tests
> Add landing page endpoint for the console redhat (#1130) - Stable

- galaxy_ng/app/tasks/deletion.py
Stop updating Repository.retain_repo_versions on delete task, so that if
retain_repo_versions has been manually set, the system will not
override.
Update tasks/deletion.py module docs to describe Content removal vs.
deletion and how retain_repo_versions is related.
No-Issue
> Do not update Repository attributes on delete, add docs

- .github/workflows/pulp_constraints.yml
- Makefile
- dev/common/check_pulp_template.sh
Sending a PR, getting all the tests to pass, waiting for reviews, and then being told you might have edited a file that some third party repo script is going to overwrite when the dependencies for this repo are updated ... is highly annoying.
> Add pulp plugin template check script and make target

- galaxy_ng/app/management/commands/set-retain-repo-versions.py
- galaxy_ng/tests/unit/app/management/commands/test_set_retain_repo_versions.py
NoIssue
```bash
[galaxy@468674a141e5 /]$ django-admin set-retain-repo-versions
Usage: django-admin set-retain-repo-versions [-h] --value VALUE --repository REPOSITORY [--exclude EXCLUDE] [-y] [--version] [-v {0,1,2,3}] [--settings SETTINGS] [--pythonpath PYTHONPATH]
[--traceback] [--no-color] [--force-color] [--skip-checks]
django-admin set-retain-repo-versions: error: the following arguments are required: --value, --repository
[galaxy@468674a141e5 /]$ django-admin set-retain-repo-versions --value=2 --repository="*"
This will set the retain repo versions  to 2 for <QuerySet ['published', 'rejected', 'community', 'rh-certified', 'staging', 'inbound-test', 'inbound-footest']>
Proceed? (Y/n)n
Process canceled.
[galaxy@468674a141e5 /]$ django-admin set-retain-repo-versions --value=2 …
```
> Add command to set retain repo versions on repos

- openshift/clowder/clowd-app.yaml
No-issue
parameterize ENABLE_SIGNING and GNUPGHOME envvars in the clowder config to allow ephemeral to be deployed differently from stage and prod
> Clowder: parameterize ENABLE_SIGNING and GNUPGHOME

- openshift/clowder/deploy-acceptance.yaml
Issue: AAH-1212
Convert the post-deploy-test that runs after a stage deploy from a ClowdJobInvocation to a Job that issues a webhook to kick off the IQE tests via Jenkins.
> convert post-deploy-test to jenkins webhook

- galaxy_ng/app/api/ui/views/landing_page.py
No-Issue
The new self service does not needs the permission fields in the schema, since the API already does the verification. This PR removes the unnecessary fields.
> Remove the unnecessary permission fields from the landing page

- .compose.env.example
- .github/workflows/ci_standalone.yml
- Makefile
- compose
- dev/docker-compose.yml
- galaxy_ng/tests/integration/api/test_openapi.py
Runs integration tests against the standalone stack.
> Add standalone integration testing to CI

- CHANGES/1389.bugfix
- galaxy_ng/app/api/ui/viewsets/execution_environment.py
- galaxy_ng/app/tasks/deletion.py
Prevent artifact removal from latest repo version when deleting images
Issue: AAH-1389
> Prevent artifact removal from latest repo version when deleting images

- .ci/scripts/validate_commit_message_custom.py
Signatures are required on all commits, but we're not enforcing it via any known mechanism other than hoping it's caught by human review.
> Check commit signatures

- openshift/clowder/deploy-acceptance.yaml
- watch build queue to verify build started
- reduce backoff limit so that only one trigger is issued
- increase default memory request to meet cluster minimum
AAH-1212
> Optimize post-deploy-test job

- .github/post-job-template.yml.j2
- .github/pre-job-template.yml.j2
- .github/workflows/ci.yml
Move `lint_po` ci check before checks such as `test (pulp)`, since linting issues fail `test (pulp)` before `lint_po` can run.
> Reorder lint_po to be before longer pulp checks

- CHANGES/1092.misc
- galaxy_ng/app/access_control/statements/__init__.py
- galaxy_ng/app/access_control/statements/roles.py
- galaxy_ng/app/signals/handlers.py
- galaxy_ng/tests/integration/api/test_locked_roles.py
- galaxy_ng/tests/integration/conftest.py
Before:
```
galaxy_ng=# select pulp_id, name, description, locked from core_role;
pulp_id                |        name        |         description          | locked 
--------------------------------------+--------------------+------------------------------+--------
f471e6df-ecb2-457e-b6f1-92b9b31ca9bd | core.group_creator |                              | t
e9f09348-f77f-4047-a180-b35cd2981902 | core.group_owner   |                              | t
de17876c-32ab-4d46-97da-492a566663dd | core.group_viewer  |                              | t
170ac59c-b34c-4c5e-aa22-c8504232569d | core.task_owner    | Allow all actions on a task. | t
cb9e3ed5-14ba-471e-a245-ffc28404e7f7 | core.task_viewer   |                              | t
(5 rows)
galaxy_ng=# select * from core_role_permissions;
id | …
```
> Create galaxy_ng specific Roles

- CHANGES/1025.misc
- galaxy_ng/app/api/ui/serializers/collection.py
https://issues.redhat.com/browse/AAH-1025
Current serializer for Collection detail lacks information about deprecation. This PR adds it.
> Collection Detail Api -  Add Deprecated info

- CHANGES/692.bugfix
- galaxy_ng/app/api/v3/viewsets/collection.py
Improve query performance.
Issue: AAH-692
> Improve queries on move api endpoint

- CHANGES/1361.misc
- docker/entrypoint.sh
- galaxy_ng/app/management/commands/maintain-pe-group.py
On container setup, after migrations are run, run a
django management command to create or update a
partner engineering group with a standard set of permissions.
Issue: AAH-1361
> Maintain partner engineering group in insights mode

- CHANGES/1458.feature
- galaxy_ng/app/access_control/fields.py
- galaxy_ng/app/api/base.py
- galaxy_ng/app/api/v3/serializers/namespace.py
- galaxy_ng/tests/unit/api/base.py
- galaxy_ng/tests/unit/api/test_api_v3_namespace_viewsets.py
Adds the `related_fields` query parameter and `my_permissions` to collection Namespaces.
Example:
```
GET http://localhost:5001/api/automation-hub/v3/namespaces/?include_related=my_permissions
"data": [
{
"id": 1,
"name": "test",
"company": "",
"email": "",
"avatar_url": "",
"description": "",
"groups": [
{
"id": 1,
"name": "system:partner-engineers",
"object_permissions": [
"change_namespace",
"upload_to_namespace"
]
}
],
"related_fields": {
"my_permissions": [
"galaxy.change_namespace",
"galaxy.upload_to_namespace"
]
}
},
{
"id": 2,
"name": "test2",
"company": "",
"email": "",
"avatar_url": "",
"description": "",
"groups": [],
"related_fields": {
"my_permissions": []
}
},
]
```
QE reviewer ([exceptions](https://docs.engineering.redhat.com/display/AUTOHUB/Other+Team+Pr …
> Related field query param.

- CHANGES/1025.misc
- galaxy_ng/app/api/ui/serializers/collection.py
This reverts commit 6ce0f25b4fd5b93d778099dfe23bbf3f9f26d44d due to bug found in https://issues.redhat.com/browse/AAH-1473
Issue: AAH-1025
> Revert "Collection Detail Api -  Add Deprecated info (#1169)"

- CHANGES/1214.misc
- pr_check.sh
* patches the frontend-aggregator to use qa-beta from automation-hub-ui-build
* refreshes /config using prod-beta to resolve missing elements
* patches chrome js to fix SSO url
Issue: AAH-1214
> pr-check: use master branch of ansible-hub-ui

- CHANGES/1478.bugfix
- galaxy_ng/app/customadmin.py
- galaxy_ng/app/settings.py
- galaxy_ng/app/urls.py
> Remove customadmin

- galaxy_ng/tests/unit/app/test_tasks.py
Our use of tempfile via override_settings is failing in CI for this branch, using a different approach.
> Fix tempfile failure in CI

- CHANGES.rst
- CHANGES/1349.bugfix
- CHANGES/840.bugfix
- galaxy_ng/__init__.py
- galaxy_ng/app/__init__.py
- setup.cfg
- setup.py
4.3.4 (2022-04-01)
Bugfixes
--------
- Consume proxy authentication fix in pulp_ansible 0.7.4
`AAH-840 <https://issues.redhat.com/browse/AAH-840>`_
- Combine the copy and remove tasks
`AAH-1349 <https://issues.redhat.com/browse/AAH-1349>`_
UI release PR: https://github.com/ansible/ansible-hub-ui/pull/1835
[API PRs](https://github.com/ansible/galaxy_ng/pulls?q=is%3Apr+base%3Astable-4.3+is%3Amerged+-author%3Aapp%2Fdependabot+merged%3A2021-09-17..2022-03-31)
[UI PRs](https://github.com/ansible/ansible-hub-ui/pulls?q=is%3Apr+base%3Astable-4.3+is%3Amerged+-author%3Aapp%2Fdependabot+merged%3A2021-09-17..2022-03-31)
previous: [4.3.3](https://github.com/ansible/galaxy_ng/pull/970)
---
Also removes a `.travis/VERSION` reference from `setup.cfg`, the file was removed in #1129 and causes …
> Release 4.3.4

- .github/workflows/ci_standalone.yml
> Dump the container logs at the end of integration tests

- CHANGES.rst
- galaxy_ng/__init__.py
(No non-UI changes in this release.)
UI release PR: https://github.com/ansible/ansible-hub-ui/pull/1889
previous: [4.2.7](https://github.com/ansible/galaxy_ng/pull/1068)
> Release 4.2.8

- compose
entrypoint.sh makes assumptions about the checkout path inside the volume mounts. If the underlying host galaxy_ng checkout is not named "galaxy_ng" (galaxy_ng.foobar for example) but you also have a folder named "galaxy_ng", the script will not use the galaxy_ng.foobar folder for pip installs. That makes it seem like your code edits aren't being reflected inside the containers and it's not very obvious why.
> Force the compose script to exit if the checkout path is wrong

- dev/common/RUN_INTEGRATION.sh
- dev/ephemeral/smoke_test.sh
- pr_check.sh
* patches chrome js to fix SSO url by restarting mocks instead of exec in frontend-aggregator pod
* update keycloak URL in smoke/integration scripts
Required due to a recent change in the keycloak URL in ephemeral environments
No-Issue
> Ephemeral: patch sso url through mocks restart

- .github/workflows/ci_standalone.yml
There is already another job named `Galaxy CI` and it is confusing
to have the duplicated name on the list.
Also added `workflow_dispatch` to be able to run workflow manually
No-Issue
> Rename standalone job

- galaxy_ng/contrib/cloudwatch.py
add missing service_name for cloudwatch logs
No-Issue
> add missing service_name for cloudwatch logs

- docker/etc/settings.py
deduplicate AWS_S3 bucket name when using virtual-hosted addressing style
Issue: AAH-1468
> deduplicate AWS_S3 bucket name

- galaxy_ng/tests/integration/api/test_openapi.py
The openapi test container was exceeding open file handle quotas when run local, so I also bumped those up for the container ...
```
>           assert docker_pid.returncode == 0, docker_pid.stderr.decode('utf-8')                                                                                                                                                                                                                   E           AssertionError: library initialization failed - unable to allocate file descriptor table - out of memory                                                                                                                                                                               E           assert 139 == 0
E            +  where 139 = …
```
> Increase file handles in openapi test container

- dev/Dockerfile.base
This solution is from @ironfroggy, and replaces the default centos repositories with the archived ones, so that it can continue to install dependencies.
> Fix 4.2 dev env repositories.

- .github/workflows/ci_standalone.yml
- CHANGES/1055.feature
- dev/common/collection_sign.sh
- docker/entrypoint.sh
- galaxy_ng/app/api/ui/serializers/collection.py
- galaxy_ng/app/api/ui/serializers/distribution.py
- galaxy_ng/app/api/ui/views/__init__.py
- galaxy_ng/app/api/ui/views/settings.py
- galaxy_ng/app/api/v3/viewsets/collection.py
- galaxy_ng/app/dynaconf_hooks.py
- galaxy_ng/app/management/commands/set-repo-keyring.py
- galaxy_ng/app/settings.py
- galaxy_ng/tests/integration/api/test_collection_signing.py
- openshift/clowder/clowd-app.yaml
Allow upload of signature for collection version.
- To upload a signature the endpoint is `/pulp/api/v3/content/ansible/collection_signatures/`
The above endpoint expects:
file: path/to/namespace.collection-version.asc (or any filename)
signed_collection: href to CollectionVersion being signed
repository:  href of the repository where that signature must be added
- To set a keyring to a repository
`django-admin set-repo-keyring --repository=staging --keyring=/etc/pulp/certs/galaxy.kbx`
- To set the system to require a signature on approval
`GALAXY_REQUIRE_SIGNATURE_FOR_APPROVAL=True`
then move endpoint will require at least one signature to allow approval.
Issue: AAH-1055
QE reviewer ([exceptions](https://docs.engineering.redhat.com/display/AUTOHUB/Other+Team+Processes# …
> Allow upload of signature for collection version.

- CHANGES/1545.bugfix
- galaxy_ng/tests/integration/conftest.py
- galaxy_ng/tests/integration/package/test_package_install.py
- setup.py
https://issues.redhat.com/browse/AAH-1545
```
(venv) [jtanner@jtw530 galaxy_ng]$ python -c 'import re; newstr = re.sub(r"""(=|^|~|<|>|!)([\S]+)""", "", "pulpcore"); print(f"newstr: {newstr}")'
newstr: 
(venv) [jtanner@jtw530 galaxy_ng]$
```
> Use simple string splitting to remove the requirements versions.

- galaxy_ng/app/settings.py
To go with https://github.com/ansible/ansible-hub-ui/pull/2030 & https://github.com/ansible/galaxy_ng/pull/1244,
which add the translations.. enabling in the list of available languages.
(also https://github.com/ansible/ansible-hub-ui/pull/2031)
> settings.py LANGUAGES: add korean

- dev/insights/galaxy_ng.env
The updated insights mode uses the 8002 port to authenticate and therefore trying to download a collection fails since for the galaxy_ng it sends on the 5001 port. This PR fixes that issue. Thanks @newswangerd for finding this.
> Fix URL for download auth in insighs mode

- CHANGES/1540.feature
- galaxy_ng/app/api/ui/serializers/synclist.py
- galaxy_ng/app/api/ui/viewsets/my_synclist.py
- galaxy_ng/app/api/v3/views/excludes.py
- galaxy_ng/app/api/v3/viewsets/collection.py
- galaxy_ng/app/management/commands/update-synclist-distros.py
- galaxy_ng/tests/integration/api/test_synclist.py
galaxy_ng.app.models.SyncList will no longer be used to curate a
SyncList.repository based on an SyncList.upstream_repository.
This PR removes calls to the curate tasks,
which edit SyncList.repos based the published repo.
SyncList.collections will continue to be updated with
excluded content, and display that at the v3/excludes endpoint
of a distribution, i.e.
api/automation-hub/content/########-synclist/v3/excludes/
This lookup will be performed without first looking up SyncList.repository
We want the viewset api/automation-hub/content/########-synclist/v3/collections/
to display all collections. This will be done via a management command that
looks up all AnsibleDistribution named "/########-synclist" and point it
to the published repo.
Issue: AAH-1540
QE reviewer …
> Serve all collections at synclist distro, stop curation

- dev/insights/docker-compose-ui.yaml
Goes together with https://github.com/ansible/ansible-hub-ui/pull/1526
Removing support for insights_proxy and references to obsolete spandx configs,
and configuring to run the UI the same way as in standalone.
Once we can run the ui in insights mode, that will work,
for now, the UI pr changes the entryfile to show an error message in insights mode.
(The problem is that the dev mode npm run start now involves a webpack plugin calling docker to set up the non-api insights dependencies in containers.)
---
> Insights dev mode (docker) UI update

- galaxy_ng/app/settings.py
This landed for 4.5.0 in #1245, to go with #1248 / #1249 which add the translations.
Making sure we have it in master as well.
> settings.py LANGUAGES: add korean (#1245)

- galaxy_ng/tests/integration/api/test_artifact_upload.py
- galaxy_ng/tests/integration/api/test_collection_delete.py
- galaxy_ng/tests/integration/api/test_collection_signing.py
- galaxy_ng/tests/integration/api/test_move.py
- galaxy_ng/tests/integration/cli/test_dependencies.py
- galaxy_ng/tests/integration/conftest.py
- galaxy_ng/tests/integration/constants.py
- galaxy_ng/tests/integration/utils.py
Integration tests waited for publish (import) to finish but did not wait
for the move task from `inbound-<namespace>` repo to `staging` before
checking `staging` repo. This may be cause of intermittent testing
errors.
No-Issue
> Add waits for task moves to integration tests

- .compose.env.example
- dev/standalone/galaxy_ng.env
No-Issue
Removing the two hardcoded env variables from the dev setup for standalone so [cypress test](https://github.com/ansible/ansible-hub-ui/pull/2069/files) can pass locally. If needed they can be added back in the `.compose.env`
> Removing hardcoded environment variables from dev

- .compose.env.example
The comment was added in #1268, but the example is using python True & False instad of true & false as the rest of the options.
And the note about changing settings.py mentions the name as it would be used in .compose.env, but not in settings.py. (PULP_ prefixed)
Cc @brumik @rochacbruno
> compose.env.example - fix pythonisms

- flake8.cfg
vscode has a convention for invoking a .venv path in the project folder. Unfortunately that path is subject to flake8 and will cause a bunch of errors. I know the venv path is a convention with no standards, but we can expand over time if needed.
> flake8.cfg ignore the .venv path per vscode convention

- .gitignore
- Makefile
Usage:
`make docker/db_snapshot` -> create a database dump and save it to db_snapshots/galaxy.backup
`make docker/db_restore` -> restore the database from db_snapshots/galaxy.backup
Multiple snapshots can be made by passing in `NAME=`
`make docker/db_snapshot NAME=pre-migration` -> creates db_snapshots/pre-migration.backup
`make docker/db_restore NAME=pre-migration` -> restores db_snapshots/pre-migration.backup
This command was originally created to help debug the permissions to roles migration, however I have found it to be useful for cleaning up after tests run as well and wanted to share it.
> Add make command to snapshot database.

- dev/ephemeral/create_objects.py
If anyone were to run these scripts against an ephemeral instance more than once, they'd see a traceback. That scenario probably won't happen often, but it'd be good for the scripts to be able to handle it.
> Make the ephemeral django scripts idempotent.

- dev/common/dynaconf_hooks.py
- dev/docker-compose.yml
- docker/bin/start-api-reload
When developer makes changes on `.compose.env` or `dev/common/settings.py`
the API container reloads the gunicorn process and settings are reflected immediately.
Affects: Docker based dev environment only
No-Issue
> [dev env] Reload API when .compose.env is changed

- dev/standalone/integration-test-dockerfile
No-Issue
Fixes a bug that was preventing some tests from running with `make docker/test/integration/container FLAGS="-k <test_name>"`
> Fix test runs in integration tests container

- dev/Dockerfile.base
- dev/docker-compose.yml
- docker/bin/start-worker-reload
When any `*.py` or `*.env` file changes on galaxy_ng or any other directory added to `DEV_SOURCE_PATH` then worker reloads inside the container.
Affects: docker based dev environment only
No-Issue
> [dev env] reload pulpcore-worker when file changes

- .github/workflows/pulp_constraints.yml
- .github/workflows/scripts/before_install.sh
- .github/workflows/scripts/install.sh
- Makefile
- template_config.yml
* Fix tests: pin CI pulp-ansible version to a release and not HEAD
* Add make command to run the `plugin_template` script
* Updated existing make command name to match `plugin_template`: `pulp/plugin-template-check`
No-Issue
> Pin pulp-ansible in plugin_template, add make cmd

- galaxy_ng/tests/integration/api/test_artifact_upload.py
- galaxy_ng/tests/integration/api/test_collection_signing.py
- galaxy_ng/tests/integration/api/test_move.py
- galaxy_ng/tests/integration/utils.py
Check if we need more and/or smarter waits for a potentially slower
ephemeral environment.
No-Issue
> Improve waits in integration tests

- CHANGES/1690.bugfix
- docs/config/collection_signing.md
- galaxy_ng/app/api/ui/views/feature_flags.py
- galaxy_ng/app/dynaconf_hooks.py
- galaxy_ng/tests/integration/api/test_collection_signing.py
- galaxy_ng/tests/integration/api/test_ui_paths.py
- galaxy_ng/tests/integration/schemas.py
Issue: AAH-1690
The web UI of reads feature flags from `settings.GALAXY_FEATURE_FLAGS` which is a Python `dict` object holding keys to granularly control the signing feature, the flags has default values computed based on 
`settings` and usually **IT IS NOT NEEDED TO CHANGE IT MANUALLY**, however if needed can be manually changed.
For example, to **enable signing feature** + **upload of signatures**
```env
export PULP_GALAXY_FEATURE_FLAGS__signatures_enabled=true
export PULP_GALAXY_FEATURE_FLAGS__can_upload_signatures=true
```
> **TIP** the above can also be defined on `/etc/pulp/settings.py`, remove the `PULP_` prefix and use Python booleans `GALAXY_FEATURE_FLAGS__signatures_enabled = True`
- `signatures_enabled`
- renaming of  `collection_signing` (which will be kept for compatibility) …
> [bugfix] Fix signing feature flags for UI

- galaxy_ng/app/access_control/statements/insights.py
- galaxy_ng/app/access_control/statements/standalone.py
No-Issue
A user with group permission should be able to display `group/roles` and `roles`. Without this, group detail and group management in UI are broken. 
The question is should users with group permissions (`galaxy.view_group`) be able to view roles and visit the `/ui/roles/` screen or only `is_superuser` should be able to do that.
Related to [AAH-1699](https://issues.redhat.com/browse/AAH-1699)
broken UI:
**Merger**: When merging, include the Jira issue link in the …
> Make roles and group/roles visible for users with group permission

- .ci/scripts/extra_linting.sh
- CHANGES/1749.bugfix
- galaxy_ng/app/tasks/deletion.py
Issue: [AAH-1749](https://issues.redhat.com/browse/AAH-1749)
Removing artifacts on deleting collection. Solution taken from [pulp_ansible/tasks/deletion.py](https://github.com/pulp/pulp_ansible/blob/main/pulp_ansible/app/tasks/deletion.py#L79) 
Issue:  [AAH-1749](https://issues.redhat.com/browse/AAH-1749)
Reuploading collection fails with duplicate key: `duplicate key value violates unique constraint "core_artifact_sha256_key"`
**Merger**: When merging, include the Jira issue …
> Artifacts cleanup on deleting collection

- CHANGES/1737.misc
- galaxy_ng/app/tasks/index_registry.py
> Update filter for indexing EEs from catalog.redhat.com

- CHANGES/1738.misc
- galaxy_ng/app/api/ui/views/feature_flags.py
- galaxy_ng/tests/integration/schemas.py
Issue: AAH-1738
```json
{
"display_signatures": true,
"collection_auto_sign": true,
"execution_environments": true,
"collection_signing": true,
"require_upload_signatures": false,
"signatures_enabled": true,
"can_upload_signatures": false,
"can_create_signatures": false,
"_messages": [
"WARNING:GALAXY_COLLECTION_SIGNING_SERVICE is set to 'ansible-default25', however the respective SigningService does not exist in the database.",
"WARNING:GALAXY_AUTO_SIGN_COLLECTIONS is set to True, however the system is not configured with a SigningService to create signatures.",
"INFO:System is configured to display signatures (coming from remote syncs) but is not configured to create or accept upload of signatures."
]
}
```
> Add diagnose messages to the feature-flags endpoint

- galaxy_ng/app/api/ui/viewsets/collection.py
- galaxy_ng/tests/integration/api/test_collection_signing.py
No-Issue
Temporarily disables sign_state and count annotations on ui collection endpoints due to a slow query reported on https://issues.redhat.com/browse/AAH-1775
> [hotfix] Temporarily disable sign_state annotations on UI endpoint.

- CHANGES/1788.misc
- galaxy_ng/app/api/ui/serializers/synclist.py
- galaxy_ng/app/auth/auth.py
- galaxy_ng/tests/unit/app/test_app_auth.py
Stop creating AnsibleRepository with foreign key to SyncList, since CRC installation in insights mode no longer needs them
* Stop creating #####-synclist repos
* On create a SyncList obj, link it to non-synclist repo published
* Add unit test for obj creation during rh auth
Issue: AAH-1788
> Stop creating AnsibleRepository with foreign key to SyncList

- CHANGES/1766.bugfix
- galaxy_ng/app/access_control/statements/insights.py
- galaxy_ng/app/access_control/statements/standalone.py
Let users with `change_group` permission to be able to add roles to the group.
Issue:  [AAH-1766](https://issues.redhat.com/browse/AAH-1766)
Users with the ability to edit groups should be able to add roles to the group. They just can't modify or create new roles.
> Allow roles assignment to group with `change_group` permission

- CHANGES/1828.misc
- galaxy_ng/app/api/ui/serializers/execution_environment.py
Issue: AAH-1828
Pulp container removed the media type from config blobs, which was causing 500s on our api: https://github.com/pulp/pulp_container/pull/600
> Remove deprecated media type from pulp_container.

- .github/workflows/ci_insights.yml
- .github/workflows/ci_standalone-community.yml
- .github/workflows/ci_standalone-ldap.yml
- .github/workflows/ci_standalone.yml
- CHANGES/1492.misc
- CHANGES/1493.misc
- pr_check.sh
* Skip pr_check for docs only PRs
* Skip CI integration test runs for docs only PRs
Issue: AAH-1492
Issue: AAH-1493
> Skip CI jobs for docs only PRs

- galaxy_ng/tests/integration/api/test_groups.py
- galaxy_ng/tests/integration/api/test_rbac_roles.py
Marking existing rbac role tests as standalone-only to prevent failures in insights tests runs.
No-Issue
> Mark existing rbac role tests as standalone-only

- CHANGES/1794.bugfix
- galaxy_ng/app/api/ui/serializers/collection.py
- galaxy_ng/app/api/ui/serializers/execution_environment.py
- galaxy_ng/app/api/ui/viewsets/collection.py
- galaxy_ng/tests/integration/api/test_collection_signing.py
Issue: AAH-1794
Remove counters for partially signed, all signed, and all unsigned collection versions and instead return the sign state of only the latest version of a collection.
> Fix sign_state query for faster collection signing performance

- galaxy_ng/app/migrations/0028_update_synclist_model.py
- galaxy_ng/app/migrations/0029_move_perms_to_roles.py
- galaxy_ng/tests/unit/migrations/test_0028_update_synclist_model.py
- galaxy_ng/tests/unit/migrations/test_0029_move_perms_to_roles.py
The default branch already has a 0028 migration, making sure this branch
appends to that
In the rebase, I chose to rename the migration on master, and this PR fixes that.
No-Issue
> Rename migrations to not override default branch

- galaxy_ng/tests/unit/app/test_app_auth.py
Test the GroupRole object that is created when a new customer logs in insights mode
No-Issue
> Add role check to app auth unit test

- galaxy_ng/app/access_control/statements/insights.py
- galaxy_ng/tests/integration/api/test_ui_paths.py
- galaxy_ng/tests/unit/api/test_api_ui_user_viewsets.py
No-Issue
Update access policy to allow read and update for /users endpoint in `insights` deployment mode
No-Issue
> Allow read and update for insights mode /users

- CHANGES/1690.bugfix
- galaxy_ng/app/api/ui/views/feature_flags.py
- galaxy_ng/app/dynaconf_hooks.py
- galaxy_ng/tests/integration/api/test_collection_signing.py
Issue: AAH-1690
The web UI of reads feature flags from `settings.GALAXY_FEATURE_FLAGS` which is a Python `dict` object holding keys to granularly control the signing feature, the flags has default values computed based on 
`settings` and usually **IT IS NOT NEEDED TO CHANGE IT MANUALLY**, however if needed can be manually changed.
For example, to **enable signing feature** + **upload of signatures**
```env
export PULP_GALAXY_FEATURE_FLAGS__signatures_enabled=true
export PULP_GALAXY_FEATURE_FLAGS__can_upload_signatures=true
```
> **TIP** the above can also be defined on `/etc/pulp/settings.py`, remove the `PULP_` prefix and use Python booleans `GALAXY_FEATURE_FLAGS__signatures_enabled = True`
- `signatures_enabled`
- renaming of  `collection_signing` (which will be kept for compatibility) …
> [Backport to stable-4.5] [bugfix] Fix signing feature flags for UI

- CHANGES/1796.misc
- dev/common/setup_test_data.py
- galaxy_ng/tests/integration/api/test_ui_paths.py
- galaxy_ng/tests/integration/conftest.py
Creates an `ee_admin` user to be used in integration tests.  Replaces the use of the `admin` user in the `test_api_ui_v1_execution_environments_registries` test per the TODO item.
Issue: AAH-1796
> Adds an ee_admin user to test setup

- CHANGES/1770.misc
- galaxy_ng/app/migrations/0017_populate_repos_and_remotes.py
- galaxy_ng/app/migrations/0030_update_collection_remote_rhcertified_url.py
- galaxy_ng/tests/unit/api/test_api_ui_collection_viewsets.py
- galaxy_ng/tests/unit/migrations/test_0030_update_collection_remote_rhcertified_url.py
Change default URL in remote `rh-certified` repository to `https://console.redhat.com/api/automation-hub/`
Issue: [AAH-1770](https://issues.redhat.com/browse/AAH-1770)
> Update remote rh-certified default url

- dev/insights/proxy/flaskapp.py
https://www.grouparoo.com/blog/dont-use-underscores-in-http-headers
By default the Nginx option underscores_in_headers is off
https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/?highlight=underscore#missing-disappearing-http-headers
If you do not explicitly set underscores_in_headers on;, NGINX will silently drop HTTP headers with underscores (which are perfectly valid according to the HTTP standard). This is done in order to prevent ambiguities when mapping headers to CGI variables as both dashes and underscores are mapped to underscores during that process.
https://docs.djangoproject.com/en/4.1/ref/request-response/
With the exception of CONTENT_LENGTH and CONTENT_TYPE, as given above, any HTTP headers in the request are converted to META keys by converting all …
> Use the correct auth header format for insights proxy

- CHANGES/1906.misc
- dev/common/container_sign.sh
- galaxy_ng/app/api/ui/serializers/execution_environment.py
- galaxy_ng/tests/integration/api/test_container_signing.py
Issue: AAH-1906
`http://0.0.0.0:5001/api/automation-hub/_ui/v1/execution-environments/repositories/?name=hello-world`
```
"data": [
{
"id": "7bf357fb-7f78-4879-8793-7caa8a3efd7b",
"name": "hello-world",
"pulp": {
"repository": {
"pulp_id": "db452e37-2b6e-4d59-b638-ffbb933d86df",
"pulp_type": "container.container-push",
"version": 4,
"name": "hello-world",
"description": null,
"pulp_created": "2022-08-11T11:11:13.778021Z",
"pulp_labels": {},
"remote": null,
"sign_state": "signed"   # <--- THIS ####
},
```
**Reviewers**: look for sound code, no [code smells](https://www.codegrip.tech/productivity/everything-you-need-to-kn …
> Add sign_state to UI/API ee repositories

- openshift/clowder/run-job.yaml
* removes randomized id from job name to prevent job from re-running during every reconcile of the environment
* move RERUN parameter from envvar to job name to better control when the job triggers
Issue: AAH-1608
> clowder: modify job template

- openshift/clowder/clowd-app.yaml
* Increase the default api and content-app CPU limit to 1 core
This has shown to reduce the likelihood of a crashloop backoff in ephemeral where `[CRITICAL] WORKER TIMEOUT` errors are seen during container startup.
No-Issue
> clowder: increase cpu limit

- .ci/scripts/extra_linting.sh
- galaxy_ng/tests/integration/utils/urls.py
No-Issue
Ci Lint (`Galaxy CI / lint (pull_request)`) doesn't fail on an error from flake8 command
on current master locally:
```
flake8 --config flake8.cfg
./galaxy_ng/tests/integration/utils/urls.py:3:1: F401 'os' imported but unused
./galaxy_ng/tests/integration/utils/urls.py:5:1: F401 'uuid' imported but unused
./galaxy_ng/tests/integration/utils/urls.py:47:101: E501 line too long (116 > 100 characters)
./galaxy_ng/tests/integration/utils/urls.py:51:101: E501 line too long (103 > 100 characters)
./galaxy_ng/tests/integration/utils/urls.py:52:101: E501 line too long (137 > 100 characters)
./galaxy_ng/tests/integration/utils/urls.py:56:12: E231 missing whitespace after ','
```
see `Run extra lint checks` in https://github.com/ansible/galaxy_ng/actions/runs/3056613257/jobs/4930952071
> Fail CI lint on flake8 error

- dev/standalone-ldap/galaxy_ng.env
- galaxy_ng/tests/integration/api/test_container_ldap.py
- galaxy_ng/tests/integration/conftest.py
> Add a test for pushing containers as an ldap user.

- CHANGES/1585.misc
- galaxy_ng/tests/integration/api/test_container_ldap.py
- galaxy_ng/tests/integration/api/test_ui_paths.py
- galaxy_ng/tests/integration/schemas.py
- galaxy_ng/tests/integration/utils/__init__.py
- galaxy_ng/tests/integration/utils/tasks.py
Adds tests for `container_paths` endpoints in AAH-1585, refactored to create a `UI_Client` `wait_for_task` function.
Issue: AAH-1585
> Add EE integration tests for container_path endpoints

- dev/insights/proxy/flaskapp.py
- galaxy_ng/tests/integration/api/test_community.py
- galaxy_ng/tests/integration/api/test_container_ldap.py
- galaxy_ng/tests/integration/utils/client_ansible_lib.py
- galaxy_ng/tests/integration/utils/urls.py
get_client and it's functional return were making it hard to inspect anything about how the client was spun up, such as the token or token type. This PR has it instead return a class instance with properties and methods that allow better introspection and future refactoring.
> Convert get_client into a callable class for easier consumption.

- CHANGES/1937.bugfix
- galaxy_ng/app/api/v3/serializers/__init__.py
- galaxy_ng/app/api/v3/serializers/collection.py
- galaxy_ng/app/api/v3/urls.py
- galaxy_ng/app/api/v3/viewsets/__init__.py
- galaxy_ng/app/api/v3/viewsets/collection.py
- galaxy_ng/tests/integration/api/test_collection_signing.py
- galaxy_ng/tests/integration/api/test_container_signing.py
Temporary fix for AAH-1932.... disable signatures in the v3 serializer in order for signatures to not be synced from CRC to PAH. For any sync'd signatures, they will be removed after the next sync. This should resolve the PAH UI display issue. This will be the case until the AAH-1932 PAH fix is available to customers.
Issue: AAH-1937
> Disable signatures in the v3 collection detail serializer

- CHANGES/1921.bugfix
- dev/standalone-keycloak/galaxy_ng.env
- dev/standalone-ldap/galaxy_ng.env
- dev/standalone-rbac-roles/galaxy_ng.env
- dev/standalone/galaxy_ng.env
- galaxy_ng/app/dynaconf_hooks.py
Issue: AAH-1921
Note: The reason we could never reproduce this in our environment was because we were setting the correct auth classes in our container, rather than relying on the default ones in settings.py. I've removed all of these settings from our .env files where they shouldn't be changed.
We don't have keycloak CI tests, so suggestions are welcome for how to add tests.
> Fix a bug preventing SSO users from logging in with podman

- galaxy_ng/__init__.py
- galaxy_ng/app/__init__.py
- setup.cfg
- setup.py
No-Issue
Bumping version to 4.6.0b1 as per the Preflight Checklist in the [Release](https://docs.engineering.redhat.com/pages/viewpage.action?spaceKey=AUTOHUB&title=Release+Processes) documentation.
Please review, thank you:)
> bump2ersion 4.6.0b1

- galaxy_ng/__init__.py
- galaxy_ng/app/__init__.py
- setup.cfg
- setup.py
No-Issue
Bumping master version to 4.7.0dev as per the Preflight Checklist in the [Release](https://docs.engineering.redhat.com/pages/viewpage.action?spaceKey=AUTOHUB&title=Release+Processes) documentation for Y-stream releases.
> bump master to 4.7.0dev

- .ci/ansible/Containerfile.j2
Attempt to fix pulp ci by using an older image. 
This will require temporarily disabling this check: `Verify pulp imposed constraints / check_pulp_template_plugin`
No-Issue
> Update pulp ci to use older image

- .ci/scripts/validate_commit_message_custom.py
PR's opened by patchback don't skip the validate_commit_message check as intended. Adding GITHUB_ACTOR check in addition to GITHUB_USER check which may not always be populated.
No-Issue
> Improve skipping the validate_commit_message check

- .github/labeler.yml
- .github/pull_request_template.md
- .github/workflows/labeler.yml
Ensure PR with changes to app functionality gets backport labels to be looked at by PR author and reviewer to keep or remove
No-Issue
**Reviewers**: Look for sound code, no [code smells](https://www.codegrip.tech/productivity/everything-you-need-to-know-about-code-smells/), docs & test coveragee
> Add backport labels to PRs

- galaxy_ng/tests/integration/api/test_ui_paths.py
Removes a pytest mark, currently throwing warnings in CI,  that I missed removing in a previous PR.
No-Issue
> Remove errant pytest mark

- .github/workflows/labeler.yml
Follow-up to #1449 
Only add labels when the PR is first opened, instead of on all updates.
( full list of activity types in https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target )
Cc @awcrosby @jctanner
> labeler: react only when a PR is opened, not on updates

- CHANGES/1965.misc
- openshift/clowder/clowd-app.yaml
* adds health checks to the backend and api to override clowder defaults.
* updates the health checks on the content-app to match the backend and api.
The readiness probe timeout is increased from 1 to 10 seconds to allow for variance based on historical loads.
The liveness probe timeout is increased from 1 to 30 seconds to match upstream network infra timeouts.
The liveness probe failureThreshold is increased from 3 to 6 so that both probes do not fail simultaneously.
Issue: AAH-1965
**Reviewers**: Look for sound code, no [code smells](https://www.codegrip.tech/productivity/everything-you-need-to-know-about-code-smells/), docs & test …
> clowder: tune health checks

- CHANGES/1941.bugfix
- galaxy_ng/app/access_control/statements/insights.py
- galaxy_ng/app/access_control/statements/standalone.py
- galaxy_ng/app/api/ui/serializers/collection.py
- galaxy_ng/app/api/ui/viewsets/collection.py
- galaxy_ng/app/api/v3/urls.py
- galaxy_ng/app/api/v3/viewsets/__init__.py
- galaxy_ng/app/api/v3/viewsets/collection.py
- galaxy_ng/tests/integration/api/test_collection_signing.py
- galaxy_ng/tests/integration/api/test_move.py
- galaxy_ng/tests/integration/utils/__init__.py
- galaxy_ng/tests/integration/utils/collections.py
Issue: AAH-1941
Filtering signatures by distro.repository coming from context["request"]
affects:
http://0.0.0.0:5001/api/automation-hub/_ui/v1/repo/rh-certified/namespace/name/
http://0.0.0.0:5001/api/automation-hub/_ui/v1/repo/rh-certified/
http://0.0.0.0:8002/ui/repo/rh-certified
http://0.0.0.0:8002/ui/repo/rh-certified/namespace/name
http://0.0.0.0:5001/api/automation-hub/_ui/v1/collection-versions/?repository=reponame
Copy Endpoint Added
```bash
/api/automation-hub/content/<str:path>/v3/collections/<str:namespace>/<str:name>/versions/<str:version>/copy/<str:source_path>/<str:dest_path>/	galaxy_ng.app.api.v3.viewsets.collection.CollectionVersionCopyViewSet	galaxy:api:v3:collection-version-copy
/api/automation-hub/v3/collections/<str:namespace>/<str:name>/versions/<str:version>/copy/<st …
```
> Inject context to filter signatures based on distro.repository

- CHANGES/1323.bugfix
- galaxy_ng/app/api/ui/views/auth.py
- galaxy_ng/tests/integration/api/test_ui_paths.py
The default CacheControl value is vague and unset, but set it specifically to no-cache;must-revalidate;no-store for responses from login view.
Issue: AAH-1323
Original test case was the jira issue https://issues.redhat.com/browse/AAH-1277 , of which https://issues.redhat.com/browse/AAH-1323 is a child of.  There is some limited details
about the scanning tool and a link to the output.
Open questions: Does this break our ui login?
To test, get a galaxy_ng up and running, and hit the https://GALAXY_NG_SERVER/ui/ and attempt to log in. Record the response headers. For old versions, this should include a very limited CacheControl header.
With new version, repeat, but this time the response headers should look something like:
```
Cache-Control: max-age=0, no-cache, no-store, must-revalidate …
```
> Set CacheControl hdrs directives no-cache on login

- CHANGES/1937.bugfix
- CHANGES/1985.misc
- galaxy_ng/app/api/v3/serializers/__init__.py
- galaxy_ng/app/api/v3/serializers/collection.py
- galaxy_ng/app/api/v3/urls.py
- galaxy_ng/app/api/v3/viewsets/__init__.py
- galaxy_ng/app/api/v3/viewsets/collection.py
- galaxy_ng/tests/integration/api/test_collection_signing.py
- galaxy_ng/tests/integration/api/test_container_signing.py
Re-enable signatures in the v3 collection detail serializer
This reverts commit 14f148a699b42ba380f85af1ffea9f7c75a183bb.
Issue: AAH-1985
> Revert "Disable signatures in the v3 collection detail serializer (#1455)"

- galaxy_ng/social/__init__.py
- galaxy_ng/tests/integration/api/test_community.py
After building scripts to create users and groups, the "github:<login>" format made less sense when trying to associate the new group name to the namespace that was created after the hypen and lowercase transformations.
> Change social auth created group name to "namespace:<namespace_name>".

- CHANGES/1957.bugfix
- dev/standalone-ldap/galaxy_ng.env
- docs/config/options.md
- docs/integration/ldap.md
- galaxy_ng/app/dynaconf_hooks.py
- galaxy_ng/tests/integration/api/test_ldap.py
Issue: AAH-1957
Add settings `AUTH_LDAP_GROUP_TYPE_PARAMS` as a hashmap
```bash
export PULP_AUTH_LDAP_GROUP_TYPE_PARAMS={name_attr="cn", member_attr="member"}
```
To allow customization og group class params.
> Add option to customize ldap group params

- integration_requirements.txt
No-Issue
Bump from ansible from 2.10.x to 2.13+
> Use ansible-core instead of ansible-base as integration client.

- .github/workflows/ci_insights.yml
- .github/workflows/ci_standalone-community.yml
- .github/workflows/ci_standalone-ldap.yml
- .github/workflows/ci_standalone-rbac-roles.yml
- .github/workflows/ci_standalone.yml
- .github/workflows/pulp_constraints.yml
- dev/common/RUN_INTEGRATION.sh
- dev/ephemeral/run_tests.sh
- dev/ephemeral/smoke_test.sh
- dev/insights/proxy/main.go
- galaxy_ng/tests/integration/api/test_pulp_api.py
- galaxy_ng/tests/integration/utils/client_ansible_galaxy_cli.py
- galaxy_ng/tests/integration/utils/client_ansible_lib.py
- galaxy_ng/tests/integration/utils/collections.py
- integration_requirements.txt
- pr_check.sh
[ephemeral] keycloaks do not have pre-defined refresh_tokens for users. To get an access_token, the client's need to use a "password" grant instead OR bypass the auth_url completely and send a basic auth header.
The galaxy cli skips the auth_url and token if a username is given, so the cli has been using basic auth for a long time against ephemeral.
Ansible 2.11, 2.12 and 2.13 have broken ssl-ignore options for the galaxy-cli so we can't use those for tests.
Ansible core 2.14 requires python >=3.9, so the workflows are now using 3.10
The devshift jenkins worker is EL7 with python ~3.6, so tests need to run inside a container to get 3.10. …
> ephemeral tests fixes

- CHANGES/1966.bugfix
- galaxy_ng/app/tasks/index_registry.py
The task was previously attempting to use a ValidationError from a 'serializers' import that didn't define it.
Use the rest_framework.exceptions.ValidationError instead.
Issue: AAH-1966
To reproduce:
1. Bring a standalone env  (./compose up)
1. run integration tests ( HUB_LOCAL=1 ./dev/common/RUN_INTEGRATION.sh)
1. watch/grep the logs for above traceback  (there should be some before the fix, but none after)
> Fix AttributeError in index_registry task

- dev/common/RUN_INTEGRATION_STAGE.sh
No-Issue
This pipeline (galaxy-ng-integration-tests-stage) needs to use python 3.9 to get past this error
https://jenkins-insights-qe-ci.apps.ocp4.prod.psi.redhat.com/job/galaxy-ng-integration-tests-stage/6/console
To do so, the jenkins job now spins up a container with python 3.9 to run the tests (PR pending to be merged https://github.com/RedHatInsights/iqe-jenkins/pull/667). So that everything works together, this little change in the RUN_INTEGRATION_STAGE.sh  (this PR) is needed.
> adapt RUN_INTEGRATION_STAGE.sh script to new container with python 3.9

- CHANGES/1975.bugfix
- galaxy_ng/tests/integration/api/rbac_actions/utils.py
Replaces string concatenation with f-string and parameters in the function calls throwing the intermittent JSONDecodeError errors. 
Issue: AAH-1975
> Fix intermittent JSONDecodeError

- .github/workflows/scripts/before_install.sh
- .github/workflows/scripts/install.sh
- requirements/requirements.common.txt
- requirements/requirements.insights.txt
- requirements/requirements.standalone.txt
- setup.py
- template_config.yml
No-Issue
Ran `make/requirements` in python3.9 with pip-tools==6.1.0 to preserve requirements.txt sorting
> Update to pulp-ansible==0.13.5

- galaxy_ng/app/management/commands/manage-group-users.py
Allows you to add or remove users from groups for local users. This is needed when Keycloak auth is enabled as there is no way to manage local users otherwise and local users are required to be able to do CI type jobs. This script allows a workaround to be put in place and can be used in conjunction with the other Django scripts in this directory.
No issue exists for this PR.
```
$ django-admin manage-user-groups ansible automation newgroup
Assigned group 'newgroup' to user 'ansible'
Assigned group 'newgroup' to user 'automation'
```
```
$ django-admin manage-user-groups --remove ansible automation newgroup
Removed group 'newgroup' from user 'ansible'
Removed group 'newgroup' from user 'automation'
```
**PR Author**: Add a QE reviewer …
> Add django script to manage users in group

- galaxy_ng/tests/integration/api/test_collection_signing.py
- galaxy_ng/tests/integration/api/test_container_ldap.py
- galaxy_ng/tests/integration/api/test_container_signing.py
- galaxy_ng/tests/integration/api/test_landing_page.py
- galaxy_ng/tests/integration/api/test_ldap.py
- galaxy_ng/tests/integration/api/test_move.py
- galaxy_ng/tests/integration/api/test_pulp_api.py
- galaxy_ng/tests/integration/api/test_remote_sync.py
- galaxy_ng/tests/integration/api/test_ui_paths.py
- galaxy_ng/tests/integration/api/test_v3_plugin_paths.py
Updates remaining integration tests not using `api_prefix` from the `config` object to do so in place of hard-coded `/api/automation-hub`.
No-Issue
> Update integration tests to use api_prefix

- .github/workflows/ci_insights.yml
- .github/workflows/ci_standalone-community.yml
- .github/workflows/ci_standalone-ldap.yml
- .github/workflows/ci_standalone-rbac-roles.yml
- .github/workflows/ci_standalone.yml
No-Issue
Integration tests fail on Install LDAP requirements
```
Run sudo apt-get install -y libsasl2-dev python-dev libldap2-dev libssl-dev build-essential
Reading package lists...
Building dependency tree...
Reading state information...
Package python-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
python2-dev python2 python-dev-is-python3
E: Package 'python-dev' has no installation candidate
Error: Process completed with exit code [10](https://github.com/ansible/galaxy_ng/actions/runs/3583299911/jobs/6028565906#step:5:11)0.
```
**PR Author & Reviewers**: Keep or remove backport labels per [Backporting …
> Switch to `python3` package for LDAP requirements

- .github/workflows/ci_standalone-iqe-rbac-tests.yml
- CHANGES/2033.misc
- dev/common/RUN_INTEGRATION.sh
- dev/common/RUN_INTEGRATION_STAGE.sh
- dev/common/setup_test_data.py
- dev/insights/RUN_INTEGRATION.sh
- dev/standalone-iqe-rbac-tests/Dockerfile
- dev/standalone-iqe-rbac-tests/RUN_INTEGRATION.sh
- dev/standalone-iqe-rbac-tests/docker-compose-ui.yaml
- dev/standalone-iqe-rbac-tests/docker-compose.yml
- dev/standalone-iqe-rbac-tests/galaxy_ng.env
- dev/standalone-iqe-rbac-tests/integration-test-dockerfile
- dev/standalone/RUN_INTEGRATION.sh
- galaxy_ng/tests/integration/api/test_iqe_rbac.py
- galaxy_ng/tests/integration/api/test_v3_plugin_paths.py
- galaxy_ng/tests/integration/conftest.py
- galaxy_ng/tests/integration/utils/iqe_utils.py
- galaxy_ng/tests/integration/utils/rbac_utils.py
- galaxy_ng/tests/integration/utils/tools.py
- integration_requirements.txt
Issue: [AAH-2033](https://issues.redhat.com/browse/AAH-2033)
Import [RBAC tests from IQE repo](https://gitlab.cee.redhat.com/insights-qe/iqe-automation-hub-plugin/-/blob/master/iqe_automation_hub/tests/api/test_rbac.py).
And some required tools too.
They are marked with this decorator @pytest.mark.min_hub_version("4.6dev") so that they get skipped if hub version is lower than 4.6
> Import IQE rbac tests

- .github/workflows/build_publish.yml
No-Issue
- Validate that galaxy_ng version matches tag
- Use `PYPI_RELEASE_TOKEN`
> Add extra validation and use PYPI_RELEASE_TOKEN

- .github/workflows/build_publish.yml
No-Issue
Correct PyPI index from testing to main.
> Use correct PyPI index in gha release process

- galaxy_ng/tests/integration/utils/collections.py
> When someone configures the galaxy client to upload to Automation Hub, they just need the token and the URL to the server correct? or should they use the inbound URL that is shown in the CLI configuration tab of their namespace?
> they don't need that, prob should not use it in case we remove those inbound repos in the future so use https://console.redhat.com/api/automation-hub/
> maybe at least one test should use the inbound repo to show you can upload to a repo. but our CRC workflow is to not need an inbound repo, and for the server to pick the repo it will go in, so the remainder of tests should do that
https://github.com/ansible/galaxy_ng/blob/master/galaxy_ng/tests/integration/api/test_artifact_upload.py#L52-L53
The test_api_publish function tries True&False for use_distribution, …
> Integration: Do not upload to the distribution by default.

- galaxy_ng/tests/integration/api/rbac_actions/utils.py
- galaxy_ng/tests/integration/api/test_rbac_roles.py
Changes:
- fixed a bug where the alpine test container was getting pulled on every test (~10 seconds per test)
- initialize reusable objects once at beginning of test (~22 seconds per test)
- tear down reusable objects once at the end of the tests (~6 seconds per test)
Total time saved: 38 seconds per test (total 8 minutes across 13 tests)
Notes:
Half the test time is used by podman for testing pushing containers. Even when the user doesn't have permissions to push containers, this step still takes 10 seconds and runs 3 times per test. I would like to find a way to further optimize this, but there doesn't seem to be any way around the fact that podman is just really slow.
> Optimize RBAC tests 

- dev/insights/galaxy-importer/galaxy-importer.cfg
- profiles/insights/galaxy-importer/galaxy-importer.cfg
RUN_ANSIBLE_TEST needs to run containers,
which fails from within both the compose dev env and oci_env
That causes collection upload in insights dev and insights tests to take ages and fail...
Running ansible-test sanity on admin-collection_dep_a_mrvrowhp-1.0.0 ...
/usr/bin/env ANSIBLE_LOCAL_TEMP='/tmp/ansible' ansible-test sanity --docker --color yes --failure-ok
Starting new "ansible-test-controller-8Slg3UTx" container.
time="2022-12-05T20:11:53Z" level=warning msg="\"/\" is not a shared mount, this could cause issues or missing mounts with rootless containers"
cannot clone: Operation not permitted
Error: cannot re-exec process
[35mWARNING: Failed to pull docker image "quay.io/ansible/default-test-container:5.9.0". Waiting a few seconds before trying again.[0m …
> Insights dev - disable RUN_ANSIBLE_TEST

- galaxy_ng/app/api/v1/viewsets/roles.py
- galaxy_ng/tests/integration/api/test_community.py
Ordering by full_metadata properties doesn't seem to work and nothing in the default modelviewset seems to alter the querset for ordering. This is a quick fix to add ordering by any field with created by default.
> Use top level created field for default v1 roles ordering.

- .github/workflows/ci_standalone.yml
Now that the db snapshot command is merged, this switches us over from my branch of oci-env to the main branch.
> Update oci-env to pull from main repo

- .github/workflows/ci_standalone-certified-sync.yml
- .github/workflows/ci_standalone.yml
- .github/workflows/ci_standalone_sync.yml
- dev/standalone-certified-sync/RUN_INTEGRATION.sh
- dev/standalone/RUN_INTEGRATION.sh
oci-env is not ready to replace our default dev stack.
* requires a secondary adjacent checkout of oci-env
* won't work with just a pip install
* doesn't conform to all of the workflows in our Makefile
> Move oci-env+sync testing to a separate file.

- .github/workflows/ci_insights.yml
- .github/workflows/ci_standalone-community.yml
- .github/workflows/ci_standalone-iqe-rbac-tests.yml
- .github/workflows/ci_standalone-ldap.yml
- .github/workflows/ci_standalone-rbac-roles.yml
- .github/workflows/ci_standalone.yml
- dev/common/poll.py
We can make using of polling instead of sleeping 120s when spinning up the CI stacks.
> Steal the polling logic from oci-env.

- galaxy_ng/tests/integration/utils/urls.py
Add additional error class in the url retry logic to wait for content to be ready to proceed in test.
No-Issue
> Fix test that fails often against stage env

- CHANGES/1958.bugfix
- galaxy_ng/app/tasks/index_registry.py
This is for the remote registry sync from registry.redhat.io not bringing deprecated Execution Environment.
Issue: AAH-1958
> Issue: AAH-1958

- galaxy_ng/app/settings.py
- galaxy_ng/tests/integration/api/test_tasks.py
No-Issue
`logging_cid` fails with `null` value. 
```
pulp_1   | django.db.utils.IntegrityError: null value in column "logging_cid" of relation "core_task" violates not-null constraint
pulp_1   | DETAIL:  Failing row contains (f9d4f0b4-16f0-47ff-b55b-db437b3c41cf, 2023-01-16 15:38:50.537753+00, 2023-01-16 15:38:50.537775+00, waiting, pulp_ansible.app.tasks.collections.sync, null, null, null, null, null, null, null, null, {"mirror": false, "optimize": true, "remote_pk": "5421af5a-5d70-..., {/api/automation-hub/pulp/api/v3/repositories/ansible/ansible/3d...)
```
Dispatch any `sync, modify, sign` task (for example on endpoint: `/pulp/api/v3/repositories/ansible/ansible/<pk>/sync/`)
Issue appears on latest pulpcore `3.23.0` (Started happening after https://github.com/pulp/pulpcore/pull/3258) …
> Add `django_guid.middleware.guid_middleware` to `MIDDLEWARE` settings

- Makefile
- galaxy_ng/tests/integration/conftest.py
* Standalone script skips certified_sync, allows make target to pass without extra setup
* Add pytest mark for certified_sync
No-Issue
> Update integration test make target to use standalone script

- CHANGES/2137.misc
- setup.py
Dependency mismatch found in pulp_installer CI
Possibly related issue: AAH-2094
Issue: AAH-2137
> Add upper limit to ansible-lint to resolve dependency mismatch

- galaxy_ng/app/management/commands/set-repo-keyring.py
No-Issue
Call get_guid() as a function in set-repo-keyring
Fixes issue where the logging_cid ends up being the python id of the get_guid method name.
> Call get_guid() as a function in set-repo-keyring

- galaxy_ng/tests/integration/api/test_openapi.py
No-Issue
Comment out `test_galaxy_openapi_validation`
Error: 
```=================================== FAILURES ===================================
________________________ test_galaxy_openapi_validation ________________________
galaxy_ng/tests/integration/api/test_openapi.py:65: in test_galaxy_openapi_validation
validate_spec(galaxy_spec)
/tmp/gng_testing/lib/python3.10/site-packages/openapi_spec_validator/shortcuts.py:17: in validate_spec
return validator.validate(spec, spec_url=spec_url)
/tmp/gng_testing/lib/python3.10/site-packages/openapi_spec_validator/validation/proxies.py:28: in validate
raise err
E   openapi_spec_validator.validation.exceptions.OpenAPIValidationError: '2023-01-14' is not a 'date-time'
E   
E   Failed validating 'format' in schema:
E       {'default': '2023-01-14', …
```
> Test `Failed validating 'format' in schema` in test_galaxy_openapi_validation

- dev/Dockerfile.base
`make docker/build` was failing with this error:
```
> [ 4/12] RUN git clone https://github.com/eradman/entr &&     cd entr &&     cp Makefile.linux Makefile &&     make &&     make install:
#7 0.290 Cloning into 'entr'...
#7 2.437 cc  -D_GNU_SOURCE -D_LINUX_PORT -Imissing -DRELEASE=\"5.4\"  missing/strlcpy.c missing/kqueue_inotify.c entr.c -o entr
#7 2.497 missing/kqueue_inotify.c:32:10: fatal error: ../data.h: No such file or directory
#7 2.497  #include "../data.h"
#7 2.497           ^~~~~~~~~~~
#7 2.497 compilation terminated.
#7 2.598 make: *** [Makefile.bsd:15: entr] Error 1
```
No-Issue
**Reviewers**: Look for sound …
> Fix make docker/build on the dev environment.

- CHANGES/2150.bugfix
- docs/integration/ldap.md
- galaxy_ng/app/dynaconf_hooks.py
- galaxy_ng/tests/integration/api/test_ldap.py
MS Active Directory search operation results in the exception [ldap.OPERATIONS_ERROR](https://www.python-ldap.org/en/python-ldap-3.4.0/reference/ldap.html#ldap.OPERATIONS_ERROR) with the diagnostic message text “In order to perform this operation a successful bind must be completed on the connection.” Alternatively, a Samba 4 AD returns the diagnostic message “Operation unavailable without authentication”. What’s happening here?
Solution: When searching from the domain level, MS AD returns referrals (search continuations) for some objects to indicate to the client where to look for these objects. Client-chasing of referrals is a broken concept, since LDAPv3 does not specify which credentials to use when chasing the referral. Windows clients are supposed to simply use their Windows …
> Allow libldap referral chasing to be disabled.

- galaxy_ng/app/access_control/statements/pulp.py
No-Issue
Unauthorized users need to retrieve/list endpoints:
- `pulp/api/v3/content/ansible/collection_versions/` 
- `pulp/api/v3/distributions/ansible/ansible/`
> Allow unauth users to access distributions and collections_versions

- openshift/clowder/clowd-app.yaml
add CONTENT_APP_HOST and CONTENT_APP_PORT envvars to nginx to prevent any impact of https://github.com/ansible/automation-hub-deploy/pull/11
Otherwise this error prevents the clowdapp to deploy:
```nginx: [emerg] host not found in upstream "galaxy-api:5001" in /opt/app-root/etc/nginx.d/default.conf:9```
No-Issue
> fix nginx error in ephemeral/crc

- galaxy_ng/locale/es/LC_MESSAGES/django.po
- galaxy_ng/locale/fr/LC_MESSAGES/django.po
- galaxy_ng/locale/ja/LC_MESSAGES/django.po
- galaxy_ng/locale/ko/LC_MESSAGES/django.po
- galaxy_ng/locale/nl/LC_MESSAGES/django.po
- galaxy_ng/locale/zh/LC_MESSAGES/django.po
> Update PO files

- CHANGES/2112.feature
- dev/common/setup_test_data.py
- dev/standalone-ldap/RUN_INTEGRATION.sh
- dev/standalone-ldap/galaxy_ng.env
- docs/integration/ldap.md
- docs/usage_guide/collections.md
- galaxy_ng/app/api/ui/views/settings.py
- galaxy_ng/app/auth/ldap.py
- galaxy_ng/app/dynaconf_hooks.py
- galaxy_ng/app/settings.py
- galaxy_ng/tests/integration/api/test_ldap.py
- galaxy_ng/tests/integration/conftest.py
- mkdocs.yml
Backport 
* Add GALAXY_LDAP_MIRROR_ONLY_EXISTING_GROUPS setting
Issue: AAH-2112
---------
Co-authored-by: Bruno Rocha <rochacbruno@gmail.com>
(cherry picked from commit f4710e973c3dddf8eb3d77cd5e8c4760a29e7801)
> [backport] Add GALAXY_LDAP_MIRROR_ONLY_EXISTING_GROUPS config option (#1609)

- .github/labeler.yml
- galaxy_ng/__init__.py
- galaxy_ng/app/__init__.py
- setup.cfg
- setup.py
No-Issue
Should we keep using the `pulp_ansible` main dev branch or are we back to pinned version?
> Update master to 4.8.0dev

- CHANGES/2281.misc
- galaxy_ng/app/access_control/access_policy.py
- galaxy_ng/app/access_control/statements/pulp.py
- galaxy_ng/tests/integration/api/test_synclist.py
Issue: AAH-2281
Filter out synclists on the pulp ansible distribution list.
> Hide synclist repos on the distribution list API.

- CHANGES/2223.bugfix
- CHANGES/2224.bugfix
- galaxy_ng/app/access_control/access_policy.py
- galaxy_ng/app/access_control/statements/pulp.py
- galaxy_ng/tests/integration/api/rbac_actions/collections.py
- galaxy_ng/tests/integration/api/test_rbac_roles.py
Added an access condition to the copy/move collection version endpoints to verify the user has permissions to modify both repositories.  Added rbac tests for the endpoints.
In a follow-up PR, I plan to move some logic from the tests to ReusableCollection._reset_collection function.
Issue: AAH-2223, AAH-2224
> Restrict access to copy/move collection version endpoints

- .github/workflows/build_publish.yml
No-Issue
When releasing `4.7.0`, CI action `build_publish` failed on `Install LDAP requirements`
```
Err:13 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 libldap2-dev all 2.5.14+dfsg-0ubuntu0.22.04.1
404  Not Found [IP: 40.119.46.219 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/o/openldap/libldap-dev_2.5.14%2bdfsg-0ubuntu0.22.04.1_amd64.deb  [40](https://github.com/ansible/galaxy_ng/actions/runs/4724662025/jobs/8382178502#step:6:41)4  Not Found [IP: 40.119.46.219 80]
Fetched 5583 kB in 1s (4040 kB/s)
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/o/openldap/libldap2-dev_2.5.14%2bdfsg-0ubuntu0.22.04.1_all.deb  404  Not Found [IP: 40.119.46.219 80]
E: Unable to fetch some archives, maybe run apt-get update or try with …
```
> Add `sudo apt -y update` in `build_publish.yml`

- .github/workflows/i18n.yml
- .github/workflows/scripts/clear_fuzzy_entries.sh
- CHANGES/2265.feature
Issue: AAH-2265
Automate running `django-admin makemessages --all`, ` django-admin compilemessages` and committing translation files weekly.
Solution taken from https://github.com/ansible/ansible-hub-ui/blob/master/.github/workflows/i18n.yml
> Update translations automatically  

- .github/workflows/ci_insights.yml
- .github/workflows/ci_standalone-community.yml
- .github/workflows/ci_standalone-ldap.yml
- .github/workflows/ci_standalone.yml
In bf3503e we skipped required CI jobs for PRs that were docs-only, this results in the PR being unable to merge since those tests are required.
Per GitHub docs there may be no way to skip a required test: https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs
No-Issue
> Don't skip required CI jobs for docs PRs

- CHANGES/2327.bugfix
- galaxy_ng/app/access_control/statements/pulp.py
- galaxy_ng/tests/integration/api/test_container_push_update.py
Issue: AAH-2327
As a superuser I cannot modify a container-push repository via API
```bash
❯ curl -kX 'PATCH' \
'https://FQDN/pulp/api/v3/repositories/container/container-push/6e2fd4fb-cc04-43e6-84c5-6880cbdbea52'/ \
-H 'accept: application/json' \                     
-H 'Authorization: Basic BASE64CREDSFORADMIN' \
-H 'Content-Type: application/json' \
-d '{
"retain_repo_versions": 1
}'
```
Result: 403 `{"detail":"You do not have permission to perform this action."}`
Expected: 200 `{"task": "id"}`
> Fix permission set for updating a container push repo

- .github/workflows/ci_insights.yml
- .github/workflows/ci_standalone-certified-sync.yml
- .github/workflows/ci_standalone-community.yml
- .github/workflows/ci_standalone-iqe-rbac-tests.yml
- .github/workflows/ci_standalone-ldap.yml
- .github/workflows/ci_standalone-rbac-on-repos.yml
- .github/workflows/ci_standalone-rbac-roles.yml
- .github/workflows/ci_standalone-x-repo-search.yml
- .github/workflows/ci_standalone.yml
- dev/common/RUN_INTEGRATION.sh
- dev/standalone-certified-sync/RUN_INTEGRATION.sh
- dev/standalone-community/RUN_INTEGRATION.sh
- dev/standalone-iqe-tests/RUN_RBAC_INTEGRATION.sh
- dev/standalone-iqe-tests/RUN_RBAC_REPOS_INTEGRATION.sh
- dev/standalone-iqe-tests/RUN_X_REPO_SEARCH_INTEGRATION.sh
- dev/standalone-ldap/RUN_INTEGRATION.sh
- dev/standalone-rbac-roles/RUN_INTEGRATION.sh
- dev/standalone/RUN_INTEGRATION.sh
No-Issue
We where seeing CI errors due to https://github.com/docker/docker-py/issues/3113
Problem:
When we do "pip install docker-compose" we are installing unsopported version of docker-compose, which comes with docker-py, which depends on request, which depends on a broken version of urllib3.
Solution:
Start using docker compose v2
New problem, container names are different in compose v2
This PR fixes both problems
> Attempt to fix docker/urllib problem by using compose v2

- galaxy_ng/locale/es/LC_MESSAGES/django.po
- galaxy_ng/locale/fr/LC_MESSAGES/django.po
- galaxy_ng/locale/ja/LC_MESSAGES/django.po
- galaxy_ng/locale/ko/LC_MESSAGES/django.po
- galaxy_ng/locale/nl/LC_MESSAGES/django.po
- galaxy_ng/locale/zh/LC_MESSAGES/django.po
Localization updates for AAP 2.4.
* pulled - 2023 05 09 18 15 20
Replaces https://github.com/ansible/galaxy_ng/pull/1715
> AAP 2.4 Translations (2) 

- dev/docker-compose.yml
- galaxy_ng/app/tasks/publishing.py
- galaxy_ng/tests/integration/api/test_upload_concurrency.py
- galaxy_ng/tests/integration/utils/client_ansible_galaxy_cli.py
The request can have a key for the repository and that must be deleted for the underlying tasks to NOT attempt to create a new repository version, as that is where race conditions most often occur.
No-Issue
(cherry picked from commit 9900a96b8e2b00997964776c65758d284983344d)
> Add a test+fix for upload concurrency. (#1701)

- CHANGES/2362.misc
- galaxy_ng/tests/integration/api/test_api_base.py
- galaxy_ng/tests/integration/api/test_artifact_download.py
- galaxy_ng/tests/integration/api/test_artifact_upload.py
- galaxy_ng/tests/integration/api/test_collection_signing.py
- galaxy_ng/tests/integration/api/test_groups.py
- galaxy_ng/tests/integration/api/test_locked_roles.py
- galaxy_ng/tests/integration/api/test_move.py
- galaxy_ng/tests/integration/api/test_openapi.py
- galaxy_ng/tests/integration/api/test_pulp_api.py
- galaxy_ng/tests/integration/api/test_remote_sync.py
- galaxy_ng/tests/integration/api/test_ui_paths.py
- galaxy_ng/tests/integration/cli/test_dependencies.py
- galaxy_ng/tests/integration/conftest.py
- galaxy_ng/tests/integration/utils/collections.py
This is to make galaxy_ng tests comptatible with AAP 2.2 (hub 4.5):
* skip tests
* replace roles with permissions (pre-rbac hub)
Issue: AAH-2362
> AAP2.2 compatibility

- galaxy_ng/locale/es/LC_MESSAGES/django.po
- galaxy_ng/locale/nl/LC_MESSAGES/django.po
* Updates translation strings for es and nl now that they are done.  
> Note: on the previous PR, I probably should have just omitted the changes for es, nl.  Turns out those were just the Machine translations and the humans weren't done translating.  In the future, the machine translations will only be used if there is a 100% match.
> Pushing updated strings for localization

- .github/workflows/scripts/clear_fuzzy_entries.sh
No-Issue
https://github.com/ansible/galaxy_ng/actions/runs/5140730182 
The script failed, because I forgot to add/backport `clear_fuzzy_entries.sh` script to older branches in https://github.com/ansible/galaxy_ng/pull/1683.
> [stable-4.7] Backport missing `clear_fuzzy_entries.sh` script

- .github/workflows/ci_standalone.yml
- galaxy_ng/tests/integration/api/test_artifact_upload.py
- galaxy_ng/tests/integration/api/test_container_push_update.py
- galaxy_ng/tests/integration/api/test_openapi.py
- galaxy_ng/tests/integration/api/test_ui_paths.py
- galaxy_ng/tests/integration/cli/test_dependencies.py
- galaxy_ng/tests/integration/conftest.py
- galaxy_ng/tests/integration/constants.py
- galaxy_ng/tests/integration/utils.py
No-Issue
Fix `stable-4.5` CI issues and set `continue-on-error: false`
Issues:
- UIClient was missing (Started happening from https://github.com/ansible/galaxy_ng/pull/1604)
-  Skip `test_galaxy_openapi_validation` (https://github.com/ansible/galaxy_ng/pull/1616)
> [stable-4.5] Add UIClient class

- .github/workflows/i18n.yml
No-Issue
Fix https://github.com/ansible/galaxy_ng/pull/1758 wasn't backported to `stable-4.4`, so removing it from translation matrix.
> [i18n] Remove stable-4.4 from matrix

- CHANGES/2328.feature
- galaxy_ng/app/tasks/promotion.py
- galaxy_ng/tests/integration/api/test_upload_to_custom_repos.py
- galaxy_ng/tests/integration/utils/pulp_interfaces.py
- galaxy_ng/tests/integration/utils/urls.py
> Fix publishing collection to specified repository when content approval is set to false

- .readthedocs.yaml
- MANIFEST.in
No-Issue
This adds configuration to build Galaxy NG docs on Read The Docs.
Test build from my fork: https://oranod-galaxy-ng.readthedocs.io/en/latest/
Build logs: https://readthedocs.org/api/v2/build/20986040.txt
> Add readthedocs configuration

- CHANGES/2409.misc
- README.md
- netlify.toml
Docs are now hosted on http://galaxy-ng.readthedocs.io/ this PR sets redirects from old site to the new location
Issue: AAH-2409
> Redirect docs from netlify to RTD

- galaxy_ng/tests/integration/api/test_move.py
- galaxy_ng/tests/integration/api/test_repositories.py
- galaxy_ng/tests/integration/api/test_x_repo_search.py
- galaxy_ng/tests/integration/utils/iqe_utils.py
Skipping tests that sign content in CVP pipelines because content signing is not configured in Operator. This issue will be addressed soon and this change will be reverted.
No-Issue
> skip content signing tests in container verification pipelines

- galaxy_ng/tests/integration/api/test_artifact_upload.py
- requirements/requirements.common.txt
- requirements/requirements.insights.txt
- requirements/requirements.standalone.txt
- setup.py
- template_config.yml
Update to galaxy-importer==0.4.11, which includes calling ansible-lint at the collection level.
No-Issue
> Update to galaxy-importer==0.4.11

- dev/insights/RUN_INTEGRATION.sh
- galaxy_ng/tests/integration/utils/collections.py
The real issue was that the insights docker profile needed to have HUB_UPLOAD_SIGNATURES set to true.
> Undo set_certification test skips

- galaxy_ng/tests/integration/api/test_collection_signing.py
- galaxy_ng/tests/integration/api/test_ui_paths.py
No-Issue
test_collection_signing has been updated so that the order of the tags is ignored.
test_ui_paths: when all the integration tests run once everything's fine, but when the tests are run multiple times against the same hub instance, all the test data generated makes the rh-certified distribution not appear on the first results of the distributions endpoint making the test fail. I opened this jira AAH-2601 to improve the test, but in the meantime an expected failure is raised if this happens (This expected fail should never happen on the pipelines, since they run against new (and without test data) deployments of hub)
> fix azure tests

- dev/ah_collection_plays/ee.yml
> comment out ah collection registry indexing test

- galaxy_ng/app/access_control/access_policy.py
https://github.com/pulp/pulpcore/pull/4090
We subclass and override the get_access_policy function, so pulp's upstream change probably won't directly help us.
> Remove lru caching on get_access_policy for memory performance concerns.

- CHANGES/2615.misc
- requirements/requirements.dev.txt
Issue: AAH-2615
The jedi issues have been fixed, so we don't have to use the old version anymore.
> use updated jedi dependency

- galaxy_ng/app/api/v1/tasks.py
- galaxy_ng/tests/integration/cli/test_community.py
Use the new LegacyRoleLoader class in updated galaxy-importer to import legacy roles
> use galaxy-importer import_legacy_role

- .github/workflows/ci_automation_hub_collection.yml
- dev/ah_collection_plays/content.yml
- dev/ah_collection_plays/ee.yml
- dev/ah_collection_plays/repo.yml
- dev/ah_collection_plays/user.yml
~~The automation hub collection now has a true `galaxy.yml` file in the repository, so the workflow no longer must create the `galaxy.yml`~~
> fix jinja templating call from ah collection workflow

- galaxy_ng/tests/integration/api/test_repositories.py
The  mock insights proxy occasionally has trouble reading/writing to the nginx service and results in a broken pipe error. This PR attempts to retry 2 problematic calls that make tests regularly fail in github actions.
The failures can be reproduced locally by starting up the oci insights profile and running test_move_cv in a loop. It seems to happen less often on my local system than it does on github, but I'm chalking that up to resource constraints in the action workers.
> Add retries to move cv call in test.

- requirements/requirements.common.txt
- requirements/requirements.insights.txt
- requirements/requirements.standalone.txt
- setup.py
Fixing multiple dependabot and prodsec reports. We have to pin the upper bound on pulpcore because we're standardizing on 3.38 the galaxy_ng 4.8.x release. We have to pin the upper bound on pulp-container because the latest is breaking tests.
https://github.com/ansible/galaxy_ng/pull/1663
https://github.com/ansible/galaxy_ng/pull/1690
https://github.com/ansible/galaxy_ng/pull/1731
https://github.com/ansible/galaxy_ng/pull/1809
https://github.com/ansible/galaxy_ng/pull/1828
https://github.com/ansible/galaxy_ng/pull/1839
> Update all dependencies.

- .github/workflows/ci_oci-env-integration.yml
- .github/workflows/deactivated/ci_standalone-certified-sync.yml
- .github/workflows/deactivated/ci_standalone-iqe-rbac-tests.yml
- .github/workflows/deactivated/ci_standalone-rbac-on-repos.yml
- .github/workflows/deactivated/ci_standalone-rbac-roles.yml
- .github/workflows/deactivated/ci_standalone-x-repo-search.yml
- docs/config/options.md
- docs/dev/docker_environment.md
- docs/dev/getting_started.md
- docs/dev/vagrant.md
- docs/usage_guide/collections.md
- docs/usage_guide/installation.md
- docs/usage_guide/rbac.md
- mkdocs.yml
Fixes the docs build warnings and infos
No-Issue
> [Docs] fix docs warnings and broken links

- galaxy_ng/tests/integration/utils/iqe_utils.py
We have now the containerized installer where the automation hub is running inside the container. We don't yet have content signing configured for such deployment. This PR should allow to disable content_signing tests by setting the HUB_CONTENT_SIGNING_ENABLED env var.
> Allow to disable signing tests for containerized AAP

- galaxy_ng/app/api/v3/viewsets/collection.py
Missed integrating this feature when galaxy_ng was bumped to pulp_ansible 0.19.0
No-Issue
> Add check for ANSIBLE_COLLECT_DOWNLOAD_COUNT setting

- CHANGES/2654.misc
- requirements/requirements.common.txt
- requirements/requirements.insights.txt
- requirements/requirements.standalone.txt
- setup.py
Bump pulpcore to 3.28.12 to enable using SystemID in analytics.
Issue: AAH-2654
```
from pulpcore.plugin.models import system_id
system_id() 
```
Should return system id ie: `'0189f470-a428-7310-a635-92cf916a6349'`
> bump pulpcore to 3.28.12

- docker/etc/settings.py
- openshift/clowder/clowd-app.yaml
* moves ANSIBLE_COLLECT_DOWNLOAD_LOG from settings.py to an envvar in clowd-app.yaml
* adds ANSIBLE_COLLECT_DOWNLOAD_COUNT as an envvar in clowd-app.yaml
This will allows for a more explicit configuration between crc and community deployments.
No-Issue
> CRC: move ANSIBLE_COLLECT_DOWNLOAD to envvars in clowd-app

- docs/dev/getting_started.md
fixes the markdown link syntax
Issue: No-Issue
> fix markdown when linking to ansible-hub-ui

- CHANGES/2575.bugfix
- dev/insights/proxy/main.go
- dev/oci_env_integration/actions/insights.py
- dev/oci_env_integration/oci_env_configs/insights.compose.env
- galaxy_ng/app/api/ui/views/auth.py
- galaxy_ng/app/dynaconf_hooks.py
- galaxy_ng/app/tasks/namespaces.py
- galaxy_ng/tests/integration/utils/client_ansible_galaxy_cli.py
- profiles/insights/proxy/main.go
Add minio CI tests
Issue: AAH-2575
> Fix namespace logos on s3

- .github/workflows/i18n.yml
No-Issue
- open pull request only if translation files are changed 
(in django<4, `django-admin makemessages --all` always creates new translation files and updates them with the creation date. Therefore, it is necessary to do git diff check. On master (django>=4), this has been fixed and no files are generated if there are no changes in translation.)
- add stable-4.8
> [i18n] Create PR only if translation (.po) files were updated

- CHANGES/2638.misc
- galaxy_ng/tests/integration/api/test_cross_repository_search.py
No-Issue [AAH-2638](https://issues.redhat.com/browse/AAH-2638)
https://gist.github.com/jerabekjiri/f05ed52c1f3c1fdb68522f063f98fa1f
The `search_url` response includes the incremented collection version (`autohubtest2.immijnge-1.0.1`) in both the `staging` and `published` repositories at the same time. 
I'm not sure why this is happening, since in https://github.com/ansible/galaxy_ng/blob/01e89102e973c57581d3b6bafca6eb6be1b74080/galaxy_ng/tests/integration/conftest.py#L249C32-L249C32, after the collection is built, it waits for the collection to be in the published repository. Nevertheless, this solution fixes the issue by searching only in the published repository.
> test for test_x_repo_search_acl_social_user instability in CI

- galaxy_ng/app/access_control/access_policy.py
- galaxy_ng/app/api/v1/filtersets.py
- galaxy_ng/app/api/v1/models.py
- galaxy_ng/app/api/v1/serializers.py
- galaxy_ng/app/api/v1/tasks.py
- galaxy_ng/app/api/v1/urls.py
- galaxy_ng/app/api/v1/viewsets/__init__.py
- galaxy_ng/app/api/v1/viewsets/namespaces.py
- galaxy_ng/app/dynaconf_hooks.py
- galaxy_ng/app/management/commands/import-galaxy-role.py
- galaxy_ng/app/management/commands/sync-galaxy-namespaces.py
- galaxy_ng/app/management/commands/sync-galaxy-roles.py
- galaxy_ng/app/utils/galaxy.py
- galaxy_ng/app/utils/legacy.py
- galaxy_ng/app/utils/namespaces.py
- galaxy_ng/app/utils/rbac.py
- galaxy_ng/social/__init__.py
- galaxy_ng/social/pipeline/user.py
- galaxy_ng/tests/integration/api/test_aiindex.py
- galaxy_ng/tests/integration/api/test_community.py
- galaxy_ng/tests/integration/community/test_community_namespace_rbac.py
- galaxy_ng/tests/integration/community/test_v1_api.py
- galaxy_ng/tests/integration/utils/__init__.py
- galaxy_ng/tests/integration/utils/legacy.py
- profiles/community/github_mock/flaskapp.py
https://issues.redhat.com/browse/AAH-2197
depends on https://github.com/ansible/galaxy/pull/3248
**What this is doing:**
In the initial v1 implementation, legacy namespaces had an optional foreign key to a v3 namespace. Since many github logins don't conform to v3 namespace name requirements, those foreign keys weren't filled in.
Per AAH-2197 we are forcing all legacy namespaces to have a v3 namespace foreign key and to control access to the legacy namespace via rbac on the v3 namespace.
I've repurposed "provider" namespaces from the old v1 to expose the v3 namespace in the v1 viewsets. Now you can see what the actual v3 namespace for the legacy namespace is and how to get to it. When looking at the /owners endpoint, it will present the list of users that own the v3 namespace. …
> v1 to v3 namespace rbac shim

- galaxy_ng/app/utils/rbac.py
- galaxy_ng/tests/integration/community/test_community_namespace_rbac.py
the old code is probably causing timeouts during social logins because of the number of namespaces it has to iterate through.
> optimize user v3 namespace owner lookups.

- CHANGES/2632.bugfix
- galaxy_ng/app/access_control/access_policy.py
- galaxy_ng/app/access_control/statements/standalone.py
- galaxy_ng/tests/integration/api/test_community.py
- galaxy_ng/tests/integration/utils/client_social_github.py
This PR adds an access policy condition to continue checking non-beta galaxy users permissions to delete/deprecate collections and and verifies social auth users have `galaxy.change_namespace` object permission on the collection's namespace in order to delete a collection.
Issue: AAH-2632
> Ensure beta-galaxy users can delete and deprecate their collections

- galaxy_ng/app/api/v1/serializers.py
- galaxy_ng/app/management/commands/sync-collection-download-counts.py
- galaxy_ng/app/utils/galaxy.py
- galaxy_ng/tests/integration/cli/test_community_sync.py
- galaxy_ng/tests/integration/community/test_community_namespace_rbac.py
https://issues.redhat.com/browse/AAH-2732
> Set galaxy to old-galaxy for community tools and tests.

- galaxy_ng/social/pipeline/user.py
- galaxy_ng/tests/integration/community/test_community_hijacking.py
- galaxy_ng/tests/integration/utils/client_social_github.py
- profiles/community/github_mock/Dockerfile
- profiles/community/github_mock/flaskapp.py
https://issues.redhat.com/browse/AAH-2735
> debug and fix user hijacking.

- README.md
Based on this [Forum Thread](https://forum.ansible.com/t/how-to-submit-issues-for-https-github-com-ansible-galaxy-ng/1254?u=l3d) the URL to the OpenAPI Spec changed.
So there is the new one, I guess.
Repleace the broken OpenAPI Spec Link
Issue: [AAH-####](https://forum.ansible.com/t/how-to-submit-issues-for-https-github-com-ansible-galaxy-ng/1254?u=l3d)
I just changed a link in the README. Please have a look if this is really the correct one. Thanks
> New OpenAPI Spec Link

- CHANGES/2731.bugfix
- galaxy_ng/app/api/v1/filtersets.py
- galaxy_ng/tests/integration/community/test_v1_api.py
> `/api/v1/users?username=test` throws server error (500)

- galaxy_ng/app/api/v1/serializers.py
- galaxy_ng/app/api/v1/tasks.py
- galaxy_ng/tests/integration/api/test_community.py
- galaxy_ng/tests/integration/community/test_community_hijacking.py
- galaxy_ng/tests/integration/utils/legacy.py
there are 5408 roles on old galaxy where the github_user doesn't match the role's namespace name
So when you install laniakea.galaxy, the role found via `?owner_username=laniakea&name=galaxy` is http://old-galaxy.ansible.com/api/v1/roles/51041/ ... which has a github_user key with value Laniakea-elixir-it
The way that worked was the role model linked to a repository model and the repository model linked to a provider namespace model ... the provider namespace's "name" property is what the role serializer emits for github_user
I'm not sure what this means for future imports of the roles considering the authors need to provide the proper org|user name to the CLI ... so I'll have to do some testing on that.
After this fix is deployed, we'll have to inject the missing field into all of the …
> github_user should override namespace.name for legacy roles.

- requirements/requirements.common.txt
- requirements/requirements.insights.txt
- requirements/requirements.standalone.txt
https://issues.redhat.com/browse/AAH-2728
https://bugzilla.redhat.com/show_bug.cgi?id=2241046
https://www.djangoproject.com/weblog/2023/oct/04/security-releases/
> Update django security release 4.2.6

- CHANGES/2775.misc
- dev/ephemeral/patch_ephemeral.sh
* updates the patch_ephemeral.sh script to set CONTENT_ORIGIN properly based on changes in crc-bonfire 4.19
* adds error logic so this issue can be more easily identified if it happens again
Issue: AAH-2775
> set proper CONTENT_ORIGIN for ephemeral pr checks

- galaxy_ng/app/access_control/fields.py
- galaxy_ng/app/access_control/mixins.py
- galaxy_ng/app/api/v3/serializers/namespace.py
- galaxy_ng/app/models/namespace.py
- galaxy_ng/tests/integration/api/test_namespace_management.py
- requirements/requirements.common.txt
- requirements/requirements.insights.txt
- requirements/requirements.standalone.txt
- setup.py
https://issues.redhat.com/browse/AAH-2721
> Allow users for namespace creation.

- galaxy_ng/app/webserver_snippets/nginx.conf
When running oci-env, I can not upload some collections, because the upload size limit is too small.
On actual galaxy.ansible.com, this is [20M](https://github.com/ansible/galaxy-deploy/blob/next/helm-ng/charts/galaxy/charts/galaxy-ui/templates/configmap.yaml#L71), but the oci-env config uses a [10M](https://github.com/pulp/pulp-oci-images/blob/latest/images/s6_assets/nginx.conf#L39) default, only overriding it for `/pulp/api/v3/` (in https://github.com/pulp/pulp-oci-images/blob/latest/images/s6_assets/nginx.conf#L62).
Our api calls go to `/api/automation-hub/`, `/api/galaxy/` or `/api/` so that `client_max_body_size 0;` doesn't apply.
---
I'm *assuming* this is something to fix in galaxy_ng, as those URLs are galaxy-specific, is that right?
(=> added an `/api/` entry in the galaxy_ng …
> nginx: add entry for /api, use client_max_body_size

- CHANGES/2781.bugfix
- galaxy_ng/app/access_control/access_policy.py
- galaxy_ng/app/access_control/statements/standalone.py
- galaxy_ng/tests/integration/api/test_rbac_roles.py
- galaxy_ng/tests/integration/community/test_community_namespace_rbac.py
- galaxy_ng/tests/unit/api/test_api_ui_user_viewsets.py
Users can't see the list of users when trying to add owners to their namespaces.
> Enable social auth users to see other users.

- galaxy_ng/app/management/commands/sync-collection-download-counts.py
- galaxy_ng/tests/integration/cli/test_community_sync.py
- requirements/requirements.common.txt
- requirements/requirements.insights.txt
- requirements/requirements.standalone.txt
- setup.py
No-Issue
https://github.com/pulp/pulp_ansible/blob/main/template_config.yml#L15-L21 `pulp_ansible` 0.19 is unsupported.
> [stable-4.8] Bump pulp_ansible to 0.20.1 and pulpcore to 3.28.17

- galaxy_ng/app/metrics_collection/common_data.py
- galaxy_ng/tests/unit/app/management/commands/analytics/automation_analytics/test_collector.py
- galaxy_ng/tests/unit/app/management/commands/analytics/automation_analytics/test_data.py
- galaxy_ng/tests/unit/app/management/commands/test_metrics_collection_lightspeed.py
Fixes current API call, which uses only base url and `/pulp/api/v3/status` and doesn't work on galaxy-dev. 
Issue: [AA-1892](https://issues.redhat.com/browse/AA-1892)
> Metrics Collection: Added GALAXY_API_PATH_PREFIX to API call

- dev/oci_unit_test
It's the 2nd argument of `dev/oci_unit_test` and it's optional, `galaxy_ng.tests.unit` by default
No-Issue
> Adds tests path argument for oci_unit_test

- .ci/aap_install.groovy
For AAP 2.5, images don't exist in registry.redhat.io, so EE image path needs to be overriden not to use paths like this: [registry.redhat.io/ansible-automation-platform-25/ansible-builder-rhel8](http://registry.redhat.io/ansible-automation-platform-25/ansible-builder-rhel8)  and use [brew.registry.redhat.io](http://brew.registry.redhat.io/)  instead. There is an input file to use unreleased EE images: input/install/ee/unreleased.yml
No-Issue
> use unreleased EE images

- galaxy_ng/app/api/v1/serializers.py
- galaxy_ng/app/api/v1/tasks.py
- galaxy_ng/app/management/commands/import-galaxy-role.py
- galaxy_ng/app/utils/galaxy.py
- galaxy_ng/app/utils/legacy.py
- galaxy_ng/tests/integration/api/test_community.py
- galaxy_ng/tests/integration/cli/test_community.py
- galaxy_ng/tests/unit/app/api/v1/test_tasks.py
https://forum.ansible.com/t/role-import-from-github-results-in-master-release-not-the-tag-release-breaking-installs/1856
After digging around and mapping out the code from github.com/ansible/galaxy ...
- At import time, all tags for the repo are enumerated and added as versions (if semantic version compliant).
- tags should be valid semantic versions or a semantic version starting with 'v'
- the "name" field for a role version is the original tag name.
- the "version" field for a role version is the tag name stripped of any 'v' prefix.
- if the import command includes `--branch=<older-tag>` the old tag will set the role's commit, but ALL tags get added as versions anyway.
- if a tag is removed from the repo, the related role version is also removed.
- in the list view and detail view, …
> Revamp legacyrole versions.

- galaxy_ng/app/api/v1/serializers.py
- galaxy_ng/app/api/v1/urls.py
- galaxy_ng/app/api/v1/viewsets/roles.py
- galaxy_ng/tests/integration/community/test_role_edits.py
A lot of the old legacy roles had their github_user, github_repo, repository.name, namespace.name, name changed over the years. We need a way to alter those fields from the API as people change the source data.
This PR does some hacky things because the data is still all in the json fullmetadata column. In a future PR I want to migrate all the important keys out to 1st class model fields and apply proper constraints.
> Add edit support for some legacyrole fields.

- docker/etc/settings.py
docker/settings.py:LOGGING was missing dynaconf_merge marker and then was overriding the logging configuration
No-Issue
> fix(settings): Add dynaconf_merge to docker/settings:LOGGING

- galaxy_ng/app/api/v1/tasks.py
- galaxy_ng/tests/integration/community/test_role_import_exceptions.py
Exception caused by current code ...
```
File "/venv/lib64/python3.11/site-packages/pulpcore/tasking/tasks.py", line 66, in _execute_task
result = func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/app/galaxy_ng/app/api/v1/tasks.py", line 412, in legacy_role_import
logger.exception(e)
File "/usr/lib64/python3.11/logging/__init__.py", line 1524, in exception
self.error(msg, *args, exc_info=exc_info, **kwargs)
File "/usr/lib64/python3.11/logging/__init__.py", line 1518, in error
self._log(ERROR, msg, args, **kwargs)
File "/usr/lib64/python3.11/logging/__init__.py", line 1634, in _log
self.handle(record)
File "/usr/lib64/python3.11/logging/__init__.py", line 1644, in handle
self.callHandlers(record)
File "/usr/lib64/python3.11/logging/__init__.py", line 1706, in callHandlers …
```
> Stringify exceptions to avoid failed logging serialization.

- galaxy_ng/app/api/v1/serializers.py
To match data from old and new galaxy, we need the github id for each user. It's squirreled away in the social auth table and can be fetched by filtering on the user.
> Add the github id to the v1/user serializer for auditing purposes.

- galaxy_ng/app/api/v1/filtersets.py
No-Issue
```
AttributeError at /api/galaxy/v3/openapi.json
type object 'LegacyRoleImportFilter' has no attribute 'github_user_filter'
```
In https://github.com/ansible/galaxy_ng/blob/master/galaxy_ng/app/api/v1/filtersets.py#L189 `github_user_filter` and `github_repo_filter` are missing filter methods.
> Fix `github_user` and `github_repo` filters in `LegacyRoleImportFilter`

- galaxy_ng/app/api/v1/tasks.py
https://issues.redhat.com/browse/AAH-2843
> Use metadata property for role name instead of the generated one.

- CHANGES/2420.doc
This PR resolves the issue  with number #318 found in the ansible-community / community-team repo
Issue: AAH-2420
> galaxy_collection folder 

- docs/community/devstack.md
- docs/dev/docker_environment.md
Node 16 is no longer maintained, update docs to mention node 18 instead.
UI: ansible/ansible-hub-ui#4582
https://nodejs.org/en/about/previous-releases
> node: update minimum version to 18+

- galaxy_ng/tests/integration/api/test_namespace_management.py
- galaxy_ng/tests/integration/utils/tasks.py
galaxykit usage in namespaces test to check if this solves failures on stage
No-Issue
> increase galaxykit usage

- .ci/aap_upgrade.groovy
Add two new stages to the AAP installation and upgrade pipeline, to check that the data loaded before the upgrade remains consistent after it
No-Issue
> add load data and verify data stages

- .github/workflows/i18n.yml
No-Issue
Since 4.5 (AAP 2.2) is EOL, stop adding translations.
> Drop support for `stable-4.5` in translations

- galaxy_ng/tests/integration/api/test_namespace_management.py
- galaxy_ng/tests/integration/utils/tasks.py
No-Issue
https://github.com/ansible/galaxy_ng/actions/runs/7171839578/job/19529139780?pr=2003#step:8:1344
```
=================================== FAILURES ===================================
_____________________ test_namespace_create_and_delete[v3] _____________________
api_version = 'v3'
galaxy_client = <bound method GalaxyKitClient.gen_authorized_client of <galaxy_ng.tests.integration.utils.iqe_utils.GalaxyKitClient object at 0x7fe17effc490>>
@pytest.mark.galaxyapi_smoke
@pytest.mark.namespace
@pytest.mark.parametrize(
"api_version",
[
'v3',
'_ui/v1'
]
)
@pytest.mark.all
def test_namespace_create_and_delete(api_version, galaxy_client):
"""Tests whether a namespace can be created and deleted"""
gc = galaxy_client("partner_engineer")
new_namespace = f"ns_test_{generate_random_string()}" …
```
> Fix flaky `test_namespace_create_and_delete[v3]`

- galaxy_ng/app/api/v1/filtersets.py
- galaxy_ng/tests/integration/community/test_v1_namespaces.py
- galaxy_ng/tests/integration/utils/legacy.py
https://issues.redhat.com/browse/AAH-2870
> Add a provider filter for legacy namespaces.

- galaxy_ng/app/settings.py
- galaxy_ng/tests/integration/api/test_namespace_management.py
- galaxy_ng/tests/integration/api/test_repositories.py
- galaxy_ng/tests/integration/cli/test_cli_flow.py
https://github.com/pulp/pulpcore/issues/4862
> add pulpdomain middleware to resolve tracebacks on re-upload.

- galaxy_ng/app/api/v1/viewsets/roles.py
- galaxy_ng/app/api/v1/viewsets/sync.py
- galaxy_ng/app/api/v1/viewsets/tasks.py
- galaxy_ng/tests/integration/api/test_community.py
- galaxy_ng/tests/integration/api/test_ui_paths.py
- galaxy_ng/tests/integration/community/test_community_namespace_rbac.py
The UI needs uuids to wait for tasks, bigints lose precision - js treats them as floats ([MAX_SAFE_INTEGER](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER), 53 < 128).
Making `legacy_dispatch` return a tuple of `task_id, pulp_id` (numeric, uuid),
and adding a `pulp_id` field along the existing `task`/`id` fields,
both to `v1/import`, to show an "Import started" task alert in the UI,
and to `v1/sync`, purely for symmetry. (Does it make sense there?)
Meant to support https://github.com/ansible/ansible-hub-ui/pull/4508,
@jctanner does something like this make sense? :)
> v1/sync, v1/import: return pulp task id along with numeric ids

- galaxy_ng/app/api/v1/serializers.py
- galaxy_ng/app/api/v1/tasks.py
- galaxy_ng/app/api/v1/viewsets/roles.py
- galaxy_ng/app/utils/galaxy.py
- galaxy_ng/tests/integration/community/test_role_import_overrides.py
- galaxy_ng/tests/integration/utils/legacy.py
https://issues.redhat.com/browse/AAH-3002
The old API supported a request parameter for `alternate-role-name` for a period of time, but was ultimately removed in https://github.com/ansible/galaxy/commit/1d1519f6cdf3098983c817421ee940db98be0d11
We added support in the galaxy-importer legacy role schema for the namespace name per https://github.com/ansible/galaxy-importer/commit/98e0931139219c61e13279d5a8a0a740e1b65fd7
"role_name" was added to the initial legacy role schema per https://github.com/ansible/galaxy-importer/commit/1927cd6b44d0a4a4713de3b34183f3b06e7856c9
This PR adds a few things ....
1) The `namespace` and `role_name` in meta/main.yml now causes the role import code to attempt to put the role by the given name into the given namespace name. RBAC still requires the github_user …
> support legacy role import overrides for namespace and name.

- CHANGES/3036.misc
- openshift/clowder/clowd-app.yaml
* adds the IMPORTER_JOB_TIMEOUT envvar to the pulp-worker
* increases the importer timeout from the default of 900 seconds to 1800 seconds
Issue: AAH-3036
> crc: add IMPORTER_JOB_TIMEOUT and increase timeout

- galaxy_ng/tests/integration/utils/iqe_utils.py
The ephemeral URL structure has changed, which then causes the is_ephemeral function in tests/integration/iqe_utils.py to return False and then cause the the rest of the code to assume it could do a token grant which then obviously blew up because ephemeral keycloak can only do password grants.
```
17:12:18 Running pytest ...
17:12:18 + echo 'Running pytest ...'
17:12:18 + /tmp/gvenv/bin/pytest --capture=no -m 'deployment_cloud or all' -v galaxy_ng/tests/integration
17:12:18 /tmp/gvenv/lib64/python3.10/site-packages/urllib3/connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'ee-0olmrio4-auth.apps.crc-eph.r9lp.p1.openshiftapps.com'. Adding certificate verification is strongly advised. See: …
```
> The urls for ephemeral environments have changed.

- .coveragerc
- .github/workflows/ci_full.yml
- MANIFEST.in
- dev/playbooks/RUNALL.sh
- dev/playbooks/build_container.yaml
- dev/playbooks/collections/ansible_collections/galaxy_ng/tools/plugins/action/local_run.py
- dev/playbooks/collections/ansible_collections/galaxy_ng/tools/plugins/filter/repr.py
- dev/playbooks/collections/ansible_collections/galaxy_ng/tools/roles/pulp_client/tasks/main.yml
- dev/playbooks/collections/ansible_collections/galaxy_ng/tools/roles/pulp_smash/tasks/main.yml
- dev/playbooks/docker/BUILD.sh
- dev/playbooks/docker/py311.patch
- dev/playbooks/docker/switch_python
- dev/playbooks/files/run_functional.sh
- dev/playbooks/files/run_units.sh
- dev/playbooks/files/smash-config.json
- dev/playbooks/run_functional_tests.yaml
- dev/playbooks/run_unit_tests.yaml
- dev/playbooks/start_container.yaml
- dev/playbooks/templates/Containerfile.j2
- dev/playbooks/templates/settings.py.j2
- dev/playbooks/vars/main.yaml
- dev/standalone-community/galaxy-importer.cfg
- galaxy_ng/tests/functional/api/test_container_repository_tags.py
- galaxy_ng/tests/unit/api/test_api_ui_my_synclists.py
- galaxy_ng/tests/unit/api/test_api_ui_user_viewsets.py
- galaxy_ng/tests/unit/app/utils/test_galaxy.py
This is a set of playbooks, roles, files and templates that are able to spawn a container almost identical to the one generated by https://github.com/pulp/plugin_template 's scripts and then run the various checks, unit tests and functional tests. All without needing to use the files layed out by https://github.com/pulp/plugin_template 
Key differences with these playbooks:
* can be run locally on any x86 linux or macos machine with docker
* set the python version on the container from the earliest step in the process
* can install projects in editable mode for live edit&debug loops
* coverage reporting on the unit tests
* we can edit and improve them without having to use the plugin template repo
> playbooks for CI checks, units and functional tests

- CHANGES/2836.bugfix
- galaxy_ng/app/management/commands/download-namespace-logos.py
- galaxy_ng/app/tasks/namespaces.py
- galaxy_ng/tests/integration/api/test_namespace_management.py
Make download_avatar task to accept .svg up to 3MB
```console
1 Namespaces missing avatar_sha256
nokia
Proceeding with namespace logo downloads
Process completed
There are no namespaces missing avatar_sha256!
```
Also it will now fail the task if logo iamge is > 3MB or provided url is an invalid logo.
Issue: AAH-2836
> fix: Accept SVG as avatar_url

- galaxy_ng/app/migrations/0017_populate_repos_and_remotes.py
Add /content/published to the default URL when setting up the default remotes.
This has been fix on #2032 but that PR not backported.
This PR changes the original migration, so fresh installs gets the new URL and existing systems are not affected
This must be backported to 4.9.z
No-Issue
Related: AAH-2836
> fix: Fresh installs must get the correct URL for rh-certified

- galaxy_ng/tests/integration/api/test_artifact_upload.py
- galaxy_ng/tests/integration/api/test_pulp_api.py
- galaxy_ng/tests/integration/api/test_synclist.py
- galaxy_ng/tests/integration/constants.py
Some improvements to make the stage tests pass
No-Issue
> fix stage tests

- galaxy_ng/tests/integration/api/test_load_data.py
- galaxy_ng/tests/integration/api/test_verify_data.py
- galaxy_ng/tests/integration/utils/iqe_utils.py
content signing is still not enabled in OCP pipelines. That's the reason why we need to skip signing collections and verifying they have been signed in LOAD DATA and VERIFY DATA stages
No-Issue
> skip if ocp

- .github/workflows/ci_automation_hub_collection.yml
- CHANGES/3064.misc
- dev_requirements.txt
- requirements/requirements.common.txt
- requirements/requirements.insights.txt
- requirements/requirements.standalone.txt
- setup.py
Issue: AAH-3064
```python
pulpcore==3.49.1
pulp-ansible==0.21.3
pulp-container==2.19.2
dynaconf==3.2.4
```
~~I have tried pulp_container 2.19, but there is a circular import happening on it.~~
> Bump all pulp_* dependencies

- galaxy_ng/app/api/v1/serializers.py
pulpcore changed Task kwargs to enc_kwargs, updating v1 serializers
(follows #2099)
Fixes:
```
pulp_1          | AttributeError: 'Task' object has no attribute 'kwargs'
pulp_1          | pulp [f8ef146e15464fab96da675ac0d5b750]: django.request:ERROR: Internal Server Error: /api/automation-hub/v1/imports/
pulp_1          | Traceback (most recent call last):
pulp_1          |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
pulp_1          |     response = get_response(request)
pulp_1          |                ^^^^^^^^^^^^^^^^^^^^^
pulp_1          |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
pulp_1          |     response = wrapped_callback(request, *callback_args, …
```
> api/v1/imports: change task.kwargs to enc_kwargs

- docker/bin/start-api
- docker/bin/start-api-reload
- docker/bin/start-content-app
In this pulpcore PR, the entrypoint for api and content containers as changed.
* https://github.com/pulp/pulpcore/pull/4249
In the changelog, they advise:
> Starting with this release, it is highly recommended to start the api and content processes by
the newly provided entrypoints (`pulpcore-api` and `pulpcore-content`) instead of calling
`gunicorn` directly.
I have removed the `--worker-class` flag as it is now handled automatically in the entrypoint script ([here](https://github.com/pulp/pulpcore/pull/4249/files#diff-f59f521cb004e091b299f33ba9750b5baf1247ad4c4017d5572d2fb6bfd0da5dR17)).
This PR is a best effort, as I don't know the galaxy_ng project as well.  Please feel free to close and replace with your own PR or request changes.  Thanks!
**PR Author & Reviewers**: Keep or remove …
> Use new entrypoint cmd per guidance from Pulp team

- .github/workflows/ci_full.yml
- dev/playbooks/collections/ansible_collections/galaxy_ng/tools/roles/pulp_client/files/generate.sh
- dev/playbooks/collections/ansible_collections/galaxy_ng/tools/roles/pulp_client/tasks/main.yml
Functional tests were failing because the VERSION string for the generated clients was an empty string which in turn causes pip to fail the install.
> Fix openapi client generation in the playbooks.

- galaxy_ng/tests/integration/community/test_community_api.py
background tasks for namespace and collection creation can take a while to settle.
> Try waiting longer for community collection tests.

- galaxy_ng/tests/integration/api/test_namespace_management.py
The initial create fires off multiple async but the test isn't waiting for all of them to finish before moving on with altering the namespace.
> edit logo test: add a sleep after the initial namespace create.

- galaxy_ng/app/api/ui/serializers/user.py
- galaxy_ng/app/dynaconf_hooks.py
When the DAB resource registry is enabled and the oci profile doesn't actually "install" social-core, this traceback is thrown ...
```
pulp-1          | Traceback (most recent call last):
pulp-1          |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
pulp-1          |     response = get_response(request)
pulp-1          |                ^^^^^^^^^^^^^^^^^^^^^
pulp-1          |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
pulp-1          |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
pulp-1          |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pulp-1          |   File …
```
> Fix traceback on user serializer with accessing social auth table.

- galaxy_ng/tests/integration/api/test_artifact_upload.py
ansible-lint no longer returns a warning on one of the warnings being tested against.
No-Issue
> Fix test_artifact_upload.py::test_ansible_lint_exception_AAH_2606

- galaxy_ng/app/dynaconf_hooks.py
Specifically in the case of downloading collections. 
Before:
```
$ ansible-galaxy collection download -p . awx.awx -s https://localhost/api/hub/content/community/ --api-key=<INSERT_KEY_HERE> --ignore-certs --no-cache
Process download dependency map
Starting collection download process to '/home/bmclaugh/Downloads/_tmp'
Downloading http://localhost:5001/api/hub/v3/plugin/ansible/content/community/collections/artifacts/awx-awx-24.0.0.tar.gz to /home/bmclaugh/.ansible/tmp/ansible-local-3030078ycyczlke/tmpzw38d1oq/awx-awx-24.0.0-if08m8a7
Downloading collection 'awx.awx:24.0.0' to '/home/bmclaugh/Downloads/'
ERROR! Failed to download collection tar from 'cmd_arg' due to the following unforeseen error: HTTP Error 404: Not Found. HTTP Error 404: Not Found
```
After:
```
$ ansible-galaxy …
```
> Use ANSIBLE_BASE_JWT_KEY to make Galaxy aware of Envoy

- requirements/requirements.common.txt
- requirements/requirements.insights.txt
- requirements/requirements.standalone.txt
- setup.py
Upgrading galaxy-importer version.
No-Issue
Includes:
https://github.com/ansible/galaxy-importer/pull/261
https://github.com/ansible/galaxy-importer/pull/265
https://issues.redhat.com/browse/AAH-3083
https://issues.redhat.com/browse/AAH-2805
https://issues.redhat.com/browse/AAH-3126
Replaces #2065.
> Bump galaxy-importer to 0.4.21

- galaxy_ng/tests/integration/api/test_collection_delete.py
- galaxy_ng/tests/integration/api/test_container_delete.py
- galaxy_ng/tests/integration/api/test_move.py
- galaxy_ng/tests/integration/api/test_namespace_management.py
- galaxy_ng/tests/integration/api/test_private_repositories.py
- galaxy_ng/tests/integration/api/test_remote_sync.py
- galaxy_ng/tests/integration/api/test_repositories.py
- galaxy_ng/tests/integration/api/test_x_repo_search.py
- galaxy_ng/tests/integration/utils/collections.py
- galaxy_ng/tests/integration/utils/iqe_utils.py
- galaxy_ng/tests/integration/utils/namespaces.py
- galaxy_ng/tests/integration/utils/tools.py
until now there have been two prefixes /api/hub and /api/galaxy. That's why the tests needed to implement a method to make everything homogeneous. Now this is not needed anymore since /api/galaxy prefix is defined everywhere
> remove prefix substitution

- galaxy_ng/tests/integration/community/test_role_import_exceptions.py
- integration_requirements.txt
AAP 2.5 is going to ship with core 2.16.x ... so it's probably long past due that we test with >2.12
> Use a more recent version of ansible-core in testing.

- galaxy_ng/tests/integration/api/test_auth.py
before hub 4.10, auth tests returned 403. Now it's 401. 
AAP 2.3 and 2.4 pipelines fail because of this.
> adapt auth tests to hub version

- CHANGES/3190.bugfix
- openshift/clowder/clowd-app.yaml
Parameterize importer resource requirements in the clowder config so that the CPU limits can be increased in stage and prod environments.
Issue: AAH-3190
> parameterize importer resource requirements

- galaxy_ng/tests/integration/api/test_v3_plugin_paths.py
missing "/" makes the server to respond with a redirection that ends up in an unauthenticated error
> add missing /

- galaxy_ng/tests/integration/constants.py
related to https://github.com/ansible/galaxykit/pull/114
> Add env overrides for integration test polling sleep times.

- galaxy_ng/app/access_control/access_policy.py
- galaxy_ng/app/access_control/statements/pulp.py
- galaxy_ng/app/access_control/statements/standalone.py
- galaxy_ng/app/api/ui/serializers/user.py
- galaxy_ng/app/settings.py
- galaxy_ng/tests/integration/api/test_disable_shared_resources.py
- galaxy_ng/tests/integration/api/test_groups.py
- galaxy_ng/tests/integration/api/test_ui_paths_gateway.py
- profiles/dab/pulp_config.env
- profiles/dab_jwt/pulp_config.env
> Add option to disable creating, update and deleting users and groups.

- galaxy_ng/app/management/commands/task-scheduler.py
- galaxy_ng/app/tasks/resource_sync.py
- galaxy_ng/tests/unit/app/management/commands/test_task_scheduler.py
No-Issue
Related: AAP-23723
```console
$ django-admin task-scheduler --help
usage: django-admin task-scheduler [-h] --id ID --path PATH --interval INTERVAL [--force]
[--version] [-v {0,1,2,3}] [--settings SETTINGS]
[--pythonpath PYTHONPATH] [--traceback] [--no-color]
[--force-color] [--skip-checks]
options:
-h, --help            show this help message and exit
--id ID               Unique str identifier for scheduled task e.g: make_sandwich
--path PATH           Importable path for the callable e.g: galaxy_ng.app.foo.bar
--interval INTERVAL   Interval in minutes
--force               Override existing scheduled task with the same identifier
```
```console
$ django-admin task-scheduler --id dab_sync --interval 15 --path "galaxy_ng.app.tasks.resource_sync.run"
dab_sync scheduled for every …
```
> feat: Add command to schedule resource sync task

- galaxy_ng/tests/integration/api/test_openapi.py
> skip if jira is open and hub from aap installation

- galaxy_ng/app/access_control/statements/roles.py
- galaxy_ng/tests/integration/dab/test_system_auditor.py
https://issues.redhat.com/browse/AAP-24730
replaces https://github.com/ansible/galaxy_ng/pull/2162
> System auditor v3.

- galaxy_ng/app/access_control/access_policy.py
- galaxy_ng/app/access_control/statements/pulp.py
- galaxy_ng/app/access_control/statements/standalone.py
- galaxy_ng/app/api/ui/serializers/user.py
- galaxy_ng/app/settings.py
- profiles/dab/pulp_config.env
- profiles/dab_jwt/pulp_config.env
No-Issue
The name `DIRECT_SHARED_RESOURCE_MANAGEMENT_ENABLED` was considered confusing, so renamed to `ALLOW_LOCAL_RESOURCE_MANAGEMENT`
realted to https://github.com/ansible/django-ansible-base/pull/456
> Rename local RESOURCE_MANAGEMENT settings flag

- galaxy_ng/app/dynaconf_hooks.py
- galaxy_ng/tests/unit/test_settings.py
> Load required settings from django-ansible-base if not set.

- galaxy_ng/app/dynaconf_hooks.py
- galaxy_ng/app/settings.py
This hook is too broad and conflicts with the intent of the alter_hostname_settings hook ...
https://github.com/ansible/galaxy_ng/blob/master/galaxy_ng/app/dynaconf_hooks.py#L714-L742
> Remove the JWT hook that overrides hostname and content origin.

- docker/entrypoint.sh
- galaxy_ng/app/tasks/resource_sync.py
- profiles/base/init.sh
Added a call to 
```bash
django-admin task-scheduler --id dab_sync --interval 15 --path "galaxy_ng.app.tasks.resource_sync.run"
```
on container entrypoint.sh, so the schedule is added on dev environment and also on all the container builds without the need for operators to call it.
No-Issue
> Schedule Sync on Container Entrypoint + Better logs

- galaxy_ng/app/dynaconf_hooks.py
- galaxy_ng/tests/integration/dab/test_url_resolution.py
The TOKEN_SERVER setting is also something that needs to not send the clients away from the original host they are connecting to.
https://issues.redhat.com/browse/AAP-24997
> Override the token server setting with crum also.

- dev/ephemeral/smoke_test.sh
The devshift ci jenkins nodes have been migrated to rhel 8 and these nodes use podman instead of docker.
This PR Adds the shared label to the volume mount in smoke_test.sh to support the rhel8 jenkins nodes.
No-Issue
> add support for rhel8 jenkins node in devshift ci

- galaxy_ng/tests/integration/dab/test_system_auditor.py
please approve if this test should be skipped when hub behind gw
> skip_role_test_gw

- galaxy_ng/tests/integration/api/test_move.py
- galaxy_ng/tests/integration/api/test_repositories.py
- galaxy_ng/tests/integration/api/test_x_repo_search.py
- galaxy_ng/tests/integration/conftest.py
- galaxy_ng/tests/integration/utils/iqe_utils.py
- galaxy_ng/tests/integration/utils/namespaces.py
```
Error
IndexError: list index out of range
Stacktrace
ansible_config = <class 'galaxy_ng.tests.integration.utils.iqe_utils.AnsibleConfigFixture'>
galaxy_client = <bound method GalaxyKitClient.gen_authorized_client of <galaxy_ng.tests.integration.utils.iqe_utils.GalaxyKitClient object at 0x7f87dc835a30>>
@pytest.mark.deployment_standalone
@pytest.mark.min_hub_version("4.7dev")
@pytest.mark.skipif(is_ocp_env(), reason="Content signing not enabled in AAP Operator")
def test_copy_associated_content(ansible_config, galaxy_client):
"""Tests whether a collection and associated content is copied from repo to repo"""
artifact = build_collection(
"skeleton",
config={
"namespace": USERNAME_PUBLISHER,
"tags": ["tools", "copytest"],
}
)
gc_admin = galaxy_client("admin")
resp = upload_artifact(None, …
```
> Skip collection signing and validation in related test.

- galaxy_ng/app/api/ui/views/settings.py
No-Issue
```console
$ time curl -s http://localhost:5001/api/galaxy/_ui/v1/settings/ 2>&1 > /dev/null
real	0m0.132s
user	0m0.012s
sys	0m0.005s
```
```console
$ time curl -s http://localhost:5001/api/galaxy/_ui/v1/settings/ 2>&1 > /dev/null
real	0m0.023s
user	0m0.000s
sys	0m0.005s
```
> fix(performance):Improve performance of /settings/ endpoint

- galaxy_ng/tests/integration/api/test_container_signing.py
No-Issue
Podman login and push fails with wrong registry parsed from url. 
```
E           subprocess.CalledProcessError: Command '['podman', 'login', '-u', 'foo', '-p', 'bar', 'https:', '--tls-verify=false']' returned non-zero exit status 125.
```
https://main-jenkins-csb-aap.apps.ocp-c1.prod.psi.redhat.com/blue/organizations/jenkins/AAPQA%2FNightly%2Fdevel%2Faapqaprov-integ-aap-devel-rhel-9-tls-external-database/detail/aapqaprov-integ-aap-devel-rhel-9-tls-external-database/45/tests/
> Use `container_registry` config for podman login and push

- galaxy_ng/app/api/ui/views/settings.py
- galaxy_ng/tests/integration/api/test_ui_paths.py
```
{
"GALAXY_ENABLE_UNAUTHENTICATED_COLLECTION_ACCESS": false,
"GALAXY_ENABLE_UNAUTHENTICATED_COLLECTION_DOWNLOAD": false,
"GALAXY_FEATURE_FLAGS": {
"legacy_roles": false,
"external_authentication": true,
"display_repositories": true,
"execution_environments": true,
"ai_deny_index": false,
"dab_resource_registry": true
},
"GALAXY_TOKEN_EXPIRATION": null,
"GALAXY_REQUIRE_CONTENT_APPROVAL": true,
"GALAXY_COLLECTION_SIGNING_SERVICE": "ansible-default",
"GALAXY_AUTO_SIGN_COLLECTIONS": true,
"GALAXY_SIGNATURE_UPLOAD_ENABLED": false,
"GALAXY_REQUIRE_SIGNATURE_FOR_APPROVAL": false,
"GALAXY_MINIMUM_PASSWORD_LENGTH": null,
"GALAXY_AUTH_LDAP_ENABLED": null,
"GALAXY_CONTAINER_SIGNING_SERVICE": "container-default",
"GALAXY_LDAP_MIRROR_ONLY_EXISTING_GROUPS": false,
"GALAXY_LDAP_DISABLE_REFERRALS": …
```
> Add more settings to the settings endpoint.

- setup.py
Pulp lower bound is too open and we need 3.2.6 to fix performance issue.
Requirements lock files are already updated.
No-Issue
> fix: Pin lower bound of dynaconf to 3.2.6

- galaxy_ng/app/migrations/_dab_rbac.py
- galaxy_ng/app/signals/handlers.py
- galaxy_ng/tests/integration/dab/test_dab_rbac.py
https://issues.redhat.com/browse/AAH-3364
After stack startup ...
```
$ curl -s -k -u admin:admin http://localhost:55001/api/galaxy/_ui/v2/role_definitions/  | jq '.results[].managed' | grep false | wc -l
0
$ curl -s -k -u admin:admin http://localhost:55001/api/galaxy/_ui/v2/role_definitions/  | jq '.results[].managed' | grep true | wc -l
35
```
> Set some defaults on the new roledefs from their pulp counterparts.

- galaxy_ng/app/migrations/_dab_rbac.py
- galaxy_ng/app/models/__init__.py
- galaxy_ng/app/signals/handlers.py
- galaxy_ng/tests/integration/dab/test_dab_rbac.py
All of this is needed so that a user can be assigned the galaxy.collection_namespaceowner roledef and to then be able to query _ui/v2/role_user_assignments
https://issues.redhat.com/browse/AAH-3361
> Fix roledef migration content types & register the Organization model

- galaxy_ng/app/api/ui_v2/filters.py
- galaxy_ng/app/api/ui_v2/serializers.py
- galaxy_ng/app/api/ui_v2/views.py
- galaxy_ng/tests/integration/dab/test_ui_v2.py
https://issues.redhat.com/browse/AAP-29429
> rewrite _ui/v2/users/ and add more test coverage

- galaxy_ng/tests/integration/dab/test_dab_rbac.py
https://issues.redhat.com/browse/AAH-3324
> Add test for changing repos via roledef as user or team.

- galaxy_ng/tests/integration/api/test_rbac_roles.py
- integration_requirements.txt
These tests take a long time and iterate through a lot of "parameters" without reporting anything.
> Use pytest-subtest on the rbac integration tests for more granular output

- galaxy_ng/tests/integration/api/test_ui_paths.py
- galaxy_ng/tests/integration/dab/test_dab_rbac.py
- galaxy_ng/tests/integration/dab/test_dab_rbac_contract.py
- galaxy_ng/tests/integration/dab/test_dab_rbac_pagination.py
- galaxy_ng/tests/integration/dab/test_ui_v2.py
No-Issue
Skip 2.5 GW and DAB tests.
List of failing tests in [2.4 jenkins pipeline](https://main-jenkins-csb-aap.apps.ocp-c1.prod.psi.redhat.com/blue/organizations/jenkins/AAPQA%2FRPM_Gating%2Fansible-automation-platform-2.4-rhel-9%2Fgeneric%2Finteg-aap-2.4_public-tls/detail/integ-aap-2.4_public-tls/91/tests/): 
```
test_api_ui_v1_settings
test_dab_user_platform_auditor_bidirectional_sync 
test_dab_team_platform_auditor_bidirectional_sync 
test_dab_user_assignment_filtering_as_user 
test_list_namespace_permissions 
test_role_definition_options 
test_create_custom_namespace_system_admin_role[dab] 
test_create_custom_namespace_system_admin_role[pulp] 
test_give_user_custom_role_system 
test_give_team_custom_role_system 
test_give_user_custom_role_object[dab-dab] …
```
> Skip 2.5 tests in 2.4 pipelines

- CHANGES/3358.misc
- galaxy_ng/app/settings.py
- galaxy_ng/app/signals/handlers.py
- galaxy_ng/tests/integration/dab/test_dab_rbac_contract.py
Testing for this is problematic. I will share my hacked tests for this. The first blurb is the one that really can't be tested by other means.
```python
from uuid import uuid4
from galaxy_ng.app.models import Team, Organization, User
from ansible_base.rbac.models import RoleDefinition
test_string = f'gateway_member_{str(uuid4())}'
member_rd = RoleDefinition.objects.filter(name='Team Member').first()
assert member_rd
org = Organization.objects.create(name=test_string)
team = Team.objects.create(name=test_string, organization=org)
user = User.objects.create(username=test_string)
member_rd.give_permission(user, team)
assert user in team.group.user_set.all()
```
This test could maybe be an integration test.
```python
from uuid import uuid4
from galaxy_ng.app.models import Team, Organization, …
```
> Sync to 2 different DAB team member roles

- galaxy_ng/tests/integration/api/test_disable_shared_resources.py
Issue: [AAP-29891](https://issues.redhat.com/browse/AAP-29891)
Skip failing tests in gw:
```
test_dab_groups_are_read_only[_ui/v1/groups/]
test_dab_groups_are_read_only[pulp/api/v3/groups/]
test_dab_cant_modify_group_memberships
test_dab_can_modify_roles
```
> Skip failing DAB tests in GW

- galaxy_ng/app/migrations/_dab_rbac.py
- galaxy_ng/tests/integration/dab/test_dab_rbac_contract.py
No-Issue
The data migration was not fully complete before.
Since the only shared roles we're truly supporting are the team member role, this should take care of that.
The integration tests aren't working for me anymore. I tested this with a custom script piped to `django-admin shell`
```python
from uuid import uuid4
from django.apps import apps
from django.db.models.signals import post_migrate
from galaxy_ng.app.migrations._dab_rbac import migrate_role_assignments
from galaxy_ng.app.models import Organization, Team, User
from galaxy_ng.app.signals.handlers import dab_rbac_signals
from ansible_base.rbac.models import RoleUserAssignment
test_string = f'gateway_member_{str(uuid4())}'
org = Organization.objects.create(name=test_string)
team = Team.objects.create(name=test_string, …
```
> Migrate group user list to role assignments

- dev/playbooks/docker/BUILD.sh
- dev/playbooks/docker/packages.patch
- dev/playbooks/docker/rootless.patch
- dev/playbooks/docker/xz.patch
The pulp oci containerfiles are broken for various reasons.
> Workaround for broken pulp ci container builds

- galaxy_ng/tests/integration/api/test_auth.py
- galaxy_ng/tests/integration/dab/test_dab_rbac_contract.py
- galaxy_ng/tests/integration/dab/test_ui_v2.py
No-Issue
Skip in GW:
- `test_ui_login_csrftoken`: [AAP-29887](https://issues.redhat.com/browse/AAP-29887)
- `test_team_member_sync_from_dab_to_pulp` 
Fix:
- `requests.exceptions.HTTPError: 401 Client Error: Unauthorized` for `test_ui_v2_teams`
> More test GW skipping

- dev/playbooks/run_unit_tests.yaml
```
+ sudo -u pulp -E env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin /usr/local/bin/pytest --cov-report term-missing:skip-covered --cov=galaxy_ng -v -r sx --color=yes -p no:pulpcore --pyargs galaxy_ng.tests.unit
/usr/local/lib/python3.11/site-packages/_pytest/config/__init__.py:331: PluggyTeardownRaisedWarning: A plugin raised an exception during an old-style hookwrapper teardown.
Plugin: helpconfig, Hook: pytest_cmdline_parse
ContextualVersionConflict: (packaging 24.1 (/usr/local/lib/python3.11/site-packages), Requirement.parse('packaging<24,>=20.0'), {'pulp-glue'})
For more information see https://pluggy.readthedocs.io/en/stable/api_reference.html#pluggy.PluggyTeardownRaisedWarning
config = pluginmanager.hook.pytest_cmdline_parse(
Traceback (most recent call …
```
> Add a workaround for pulp-glue&packaging conflicts in unit tests.

- .github/workflows/ci_full.yml
- .gitignore
- dev/playbooks/files/run_units.sh
This PR adds storing Hub unit test results in jUnit XML file when the test are running and then uploading them to the platform readiness dashboard.
Issue: [issues.redhat.com/browse/AAP-29787](https://issues.redhat.com/browse/AAP-29787)
Documentation: [handbook.eng.ansible.com/docs/Testing/xunit-junit](https://handbook.eng.ansible.com/docs/Testing/xunit-junit)
copy-pasted from https://github.com/ansible/aap-gateway/pull/527
> Add CI upload junit xml test results

- README.md
- docs/community/api_v3.md
- docs/community/devstack.md
- docs/community/overview.md
- docs/usage_guide/execution_environments.md
As a part of the [Consolidating Ansible discussion platforms initiative](https://forum.ansible.com/t/proposal-consolidating-ansible-discussion-platforms/6812), this PR adds the communication section template defined by the community to the README and the docsite. Similar PRs are now being raised across all the Ansible ecosystem projects.
Thanks!
Issue: AAP-27579
n/a
> Add communication details

- galaxy_ng/tests/integration/cli/test_cli_flow.py
- galaxy_ng/tests/integration/cli/test_dependencies.py
Issue: [AAP-29882](https://issues.redhat.com/browse/AAP-29882)
Will not run in GW after https://gitlab.cee.redhat.com/aap-ci/aap-jenkins-shared-library/-/merge_requests/1899 is merged
> Skip `ansible-galaxy collection install` in GW

- galaxy_ng/app/dynaconf_hooks.py
- galaxy_ng/tests/unit/app/test_dynaconf_hooks.py
- profiles/keycloak/pulp_config.env
https://issues.redhat.com/browse/AAP-31680
> Merge unique auth classes in the keycloak dynaconf hook.

- galaxy_ng/app/migrations/_dab_rbac.py
https://issues.redhat.com/browse/AAP-31417
> [RBAC] failed grouprole permission migrations fix

- galaxy_ng/app/dynaconf_hooks.py
- galaxy_ng/tests/unit/app/test_dynaconf_hooks.py
https://issues.redhat.com/browse/AAP-32146
> Force galaxy session auth as the first auth class.

- .github/workflows/ci_automation_hub_collection.yml
- dev/galaxy_collection_plays/content.yml
- dev/galaxy_collection_plays/ee.yml
- dev/galaxy_collection_plays/galaxy.yml.j2
- dev/galaxy_collection_plays/repo.yml
- dev/galaxy_collection_plays/user.yml
- dev/galaxy_collection_plays/vars.yml
Modules were moved from galaxy_collection to ansible-collections/ansible_hub.  Updating the CI workflow to reflect the change.
No-Issue
> Update CI workflow for collection testing

- galaxy_ng/tests/integration/api/test_groups.py
- galaxy_ng/tests/integration/conftest.py
- galaxy_ng/tests/integration/dab/test_dab_rbac.py
No-Issue 
Skip Hub tests if `ALLOW_LOCAL_RESOURCE_MANAGEMENT` is False
```
galaxy_ng.tests.integration.api.test_groups.test_gw_group_role_listing[test_data0]
galaxy_ng.tests.integration.api.test_groups.test_gw_group_role_listing[test_data1]
galaxy_ng.tests.integration.dab.test_dab_rbac.test_dab_rbac_repository_owner_by_user_or_team[False]
galaxy_ng.tests.integration.dab.test_dab_rbac.test_dab_rbac_repository_owner_by_user_or_team[True]
galaxy_ng.tests.integration.dab.test_dab_rbac.test_dab_rbac_namespace_owner_by_user_or_team[False]
galaxy_ng.tests.integration.dab.test_dab_rbac.test_dab_rbac_namespace_owner_by_user_or_team[True]
```
> More tests skip if  `ALLOW_LOCAL_RESOURCE_MANAGEMENT=False`

- aap_compose_dev.yaml
Changes error:
```
$ docker exec -it galaxy_ng-api-1 django-admin resource_sync
----- RESOURCE SYNC STARTED -----
>>> shared.organization
2024-09-24 20:06:58,145 INFO ansible_base.resources_api.rest_client: Making get request to https://aap-gw-proxy-1:9080/api/gateway/v1/service-index/metadata/.
Traceback (most recent call last):
File "/venv/lib64/python3.11/site-packages/urllib3/connection.py", line 196, in _new_conn
sock = connection.create_connection(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/venv/lib64/python3.11/site-packages/urllib3/util/connection.py", line 60, in create_connection
for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib64/python3.11/socket.py", line 962, in getaddrinfo
for res in …
```
> Add back service-mesh network to have reverse sync work

- galaxy_ng/app/dynaconf_hooks.py
- galaxy_ng/tests/unit/app/test_dynaconf_hooks.py
This variable name better matches the related keycloak setting and should be less cognitive load on sysadmins.
https://www.keycloak.org/server/all-config
> Keycloak prefix setting rename

- .gitleaks.toml
The keys are for development and testing only
> Update gitlaks to indicate the new keys are safe to expose

- galaxy_ng/tests/integration/api/test_artifact_download.py
- galaxy_ng/tests/integration/api/test_artifact_upload.py
- galaxy_ng/tests/integration/api/test_collection_delete.py
- galaxy_ng/tests/integration/api/test_collection_signing.py
- galaxy_ng/tests/integration/api/test_container_push_update.py
- galaxy_ng/tests/integration/api/test_cross_repository_search.py
- galaxy_ng/tests/integration/api/test_move.py
- galaxy_ng/tests/integration/api/test_ui_paths_gateway.py
- galaxy_ng/tests/integration/api/test_x_repo_search.py
- galaxy_ng/tests/integration/dab/test_dab_rbac.py
Related issue: [AAP-32015](https://issues.redhat.com/browse/AAP-32015)
Mark signing tests  with `skip_in_gw` as they fail in `rpm-b` topology.
lint-po failed with
```
1s
Run pip3 install lint-po
error: externally-managed-environment
× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
python3-xyz, where xyz is the package you are trying to
install.
If you wish to install a non-Debian-packaged Python package,
create a virtual environment using python3 -m venv path/to/venv.
Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
sure you have python3-full installed.
If you wish to install a non-Debian packaged Python application,
it may be easiest to use pipx install xyz, which will manage a
virtual environment for you. Make sure you …
```
> Skip signing tests in gw

- .gitignore
- dev/compose/README.md
- dev/compose/aap.yaml
- dev/compose/bin/reloader
- If DEV_SOURCE_PATH is not defined run without reloader to save resources
- Fixed reloader to actually take the changes, it was missing `/app` mount point
- Added troubleshooting section to README
TIL:
If you leave an undefined variable on compose yaml, docker compose will try to read from external environment, if not found it will just leave as undefined, so `DEV_SOURCE_PATH: ${DEV_SOURCE_PATH}` is not required, we can just do `DEV_SOURCE_PATH:`
> dev: if DEV_SOURCE_PATH is undefined run without reloader.

- .gitignore
- dev/compose/Dockerfile.dev
- dev/compose/aap.yaml
Makes compose restarts (without rebuild) faster.
- Adds Dockerfile.dev as extension on top of Dockerfile.rhel8
- Helper service becomes unnecessary as the Dockerfile copies files
- GPG keys imported only once
- Saves time installing dev/debugging tools once
> dev: Move cmds from helper container to a extended Dockerfile

- requirements/requirements.common.txt
- requirements/requirements.insights.txt
- requirements/requirements.standalone.txt
- setup.py
https://issues.redhat.com/browse/AAP-33509
> Bump galaxy-importer to 0.4.26

- galaxy_ng/tests/integration/utils/iqe_utils.py
```
(Epdb) rr.text
'{"errors":[{"status":"400","code":"invalid","title":"Invalid input.","detail":"Namespace github_qe_test_user cannot be deleted because there are still collections associated with it."}]}'
```
> Recursively delete the namespace in stage tests.

- .gitignore
- dev/compose/README.md
- docs/dev/integration_tests.md
- galaxy_ng/tests/integration/README.md
- galaxy_ng/tests/unit/README.md
- lint_requirements.txt
- setup.py
Small update to add instructions on how to run integration and unit tests with docker compose. 
Issue: [AAP-35973](https://issues.redhat.com/browse/AAP-35973)
> Add docs to run integration and unit tests with docker compose

- openshift/clowder/clowd-app.yaml
Moves migrations out of the init container on the API pod to a separate pod
The recent deployment of crc-2024-11-25 has introduced a lot of post-migration hooks that cause migrations to take at least an hour even if there are no migrations to apply. Since migrations are currently handled in the init container of the API pods this causes the scaling of the API to occur very slowly.
Using a Job or ClowdJobInvocation is not feasible, because the AppSRE tooling reconciles Jobs after other resource types. This is useful when a Job is utilized to run integration tests after a deployment, but makes it impossible for migrations to run in a Job before the other resources roll out.
> crc: run migrations in a separate container

- requirements/requirements.common.txt
- requirements/requirements.insights.txt
- requirements/requirements.standalone.txt
- setup.py
Bumping pulp_ansible version to fix FK bug found during UI tests.
Issue: [AAP-30156](https://issues.redhat.com/browse/AAP-30156)
This PR should be merged only after all pipelines run green, including UI tests.
> Bump pulp_ansible to 0.23.1

- galaxy_ng/tests/integration/api/test_load_data.py
- galaxy_ng/tests/integration/api/test_verify_data.py
Issue: [AAH-37593](https://issues.redhat.com/browse/AAP-37593)
Skip `test_load_repositories` in 4.6, repository management was introduced in 4.7+.
Changes tested on https://jenkins-csb-aap-main.dno.corp.redhat.com/job/AAPQA/job/Sandbox/job/christian/job/upgrade-from-2.3_released-to-2.4_public-minor/
> Skip test load repositories in 2.3 to 2.4 upgrade

- profiles/base/Dockerfile
`test_ansible_lint_exception_AAH_2606` failing with creating ~/.ansible/roles and permission issues in ldap and keycloak profile.
```
Importing with galaxy-importer 0.4.27
Getting doc strings via ansible-doc
Finding content inside collection
Loading role docker_role
Linting collection via ansible-lint...
Traceback (most recent call last):
File "/usr/lib64/python3.11/pathlib.py", line 1116, in mkdir
os.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: \'/.ansible/roles\'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/bin/ansible-lint", line 8, in <module>
sys.exit(_run_cli_entrypoint())
^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/ansiblelint/__main__.py", line 408, in …
```
> oci-env LDAP and Keycloak test fix 

- dev/compose/README.md
What is this PR doing:
This PR adds documentation for setting up a development environment using Vagrant. Since Fedora uses Podman by default, this guide provides instructions on configuring a Vagrant-based VM to run Docker, ensuring a consistent development environment while avoiding conflicts with the host system's package management.
Issue: No-Issue
Reviewers must know:
It includes instructions for setting up and running a Vagrant VM, installing dependencies, and ensuring Docker is properly configured.
No code changes are introduced, only documentation.
> docs: add Vagrant-based development environment setup guide

- dev/compose/README.md
- dev/compose/ldap.yaml
This PR introduces a new  Docker Compose configuration file, ldap.yaml ( LDAP Profile ), to the galaxy_ng/dev/compose directory.
Issue: AAP-32587 -  Add docker-compose file for LDAP profile 
Please see: https://issues.redhat.com/browse/AAP-32587
- **Testing Steps**:  
From the `galaxy_ng` directory, run:  
```
docker compose -f dev/compose/ldap.yaml up --build 
```  
Verify that the API is accessible at [http://localhost:5001/api/galaxy/v3/swagger-ui/](http://localhost:5001/api/galaxy/v3/swagger-ui/).  
Confirm the LDAP service is running by connecting to `ldap://localhost:10389`.
```
ldapsearch -x -H ldap://localhost:10389 -D "cn=admin,dc=planetexpress,dc=com" -w GoodNewsEveryone -b "dc=planetexpress,dc=com"
```  
- **Additional Notes**:  
- The configuration is designed for local …
> Issue: AAP-32587 - Add docker-compose file for LDAP

- dev/compose/README.md
- dev/compose/keycloak-utils/keycloak-change-user-password.yaml
- dev/compose/keycloak-utils/keycloak-client.yaml
- dev/compose/keycloak-utils/keycloak-playbook.yaml
- dev/compose/keycloak-utils/keycloak-realm.yaml
- dev/compose/keycloak.yaml
What is this PR doing:
This PR introduces a new Docker Compose configuration file, keycloak.yaml (Keycloak Profile), to the galaxy_ng/dev/compose directory. Implement Keycloak authentication with LDAP integration for Ansible Automation Hub, enabling centralized user management and single sign-on capabilities across the platform.
Issue: AAP-32586 - Add docker-compose file for Keycloak profile
Please see: https://issues.redhat.com/browse/AAP-32586
> Add docker-compose file for keycloak profile [4.9]

- .github/workflows/i18n.yml
Automatic updating translation files fail on
```
Run sudo apt-get install -y libsasl2-dev libldap2-dev libssl-dev build-essential gettext python-setuptools
sudo apt-get install -y libsasl[2](https://github.com/ansible/galaxy_ng/actions/runs/13601616704/job/38028165394#step:5:2)-dev libldap2-dev libssl-dev build-essential gettext python-setuptools
shell: /usr/bin/bash -e {0}
Reading package lists...
Building dependency tree...
Reading state information...
Package python-setuptools is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
E: Package 'python-setuptools' has no installation candidate
Error: Process completed with exit code …
```
> Fix automatic updating translation files

- galaxy_ng/app/models/organization.py
When Organization is deleted, referenced Teams are deleted as CASCADE. This does not trigger signals for Team model. Therefore before deleting an Organization we need to manually call delete() on each of the referenced teams.
Issue: AAP-41177
> AAP-41177: Fix organization deletion

- Dockerfile.rhel8
Error: `skopeo: command not found`
```
manager-1       | Traceback (most recent call last):
manager-1       |   File "/venv/bin/pulpcore-manager", line 8, in <module>
manager-1       |     sys.exit(manage())
manager-1       |              ^^^^^^^^
manager-1       |   File "/venv/lib64/python3.11/site-packages/pulpcore/app/manage.py", line 11, in manage
manager-1       |     execute_from_command_line(sys.argv)
manager-1       |   File "/venv/lib64/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
manager-1       |     utility.execute()
manager-1       |   File "/venv/lib64/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
manager-1       |     self.fetch_command(subcommand).run_from_argv(self.argv) …
```
> [stable-4.9] Backport skopeo to `Dockerfile.rhel8`

- docs/config/options.md
The GALAXY_ENABLE_API_ACCESS_LOG option is documented twice.
No-Issue
> Docs: remove duplicate option GALAXY_ENABLE_API_ACCESS_LOG

- galaxy_ng/app/migrations/0056_set_retain_repo_versions_to_validated_repo.py
Issue: [AAP-41840](https://issues.redhat.com/browse/AAP-41840)
The migration file [0032_add_validated_repo.py](https://github.com/jerabekjiri/galaxy_ng/blob/master/galaxy_ng/app/migrations/0032_add_validated_repo.py), which creates the `validated` repository, runs after [0022_enforce_retain_repo_versions.py](https://github.com/jerabekjiri/galaxy_ng/blob/master/galaxy_ng/app/migrations/0022_enforce_retain_repo_versions.py), causing `validated` repo to have a default value `None`.
> Set `retain_repo_versions: 1` to `validated` repository

- galaxy_ng/app/migrations/0046_set_retain_repo_versions_to_validated_repo.py
Manual backport of PR https://github.com/ansible/galaxy_ng/pull/2461
Issue: [AAP-41840](https://issues.redhat.com/browse/AAP-41840)
> [stable-4.9] Set `retain_repo_versions: 1` to `validated` repository

- .github/workflows/ci_full.yml
- MANIFEST.in
- dev/compose/aap.yaml
- galaxy_ng/tests/unit/README.md
- galaxy_ng/tests/unit/api/base.py
- galaxy_ng/tests/unit/api/rh_auth.py
- galaxy_ng/tests/unit/api/test_localization.py
- galaxy_ng/tests/unit/test_models.py
- tox.ini
- unittest_requirements.txt
> [stable-4.9] Adding tox

- galaxy_ng/app/settings.py
gunicorn sends a signal 6 when it is about to timeout a request This middleware handles that request and logs a traceback.
this aids in debugging infrastructure issues that may be causing requests to timeout.
Issue: https://issues.redhat.com/browse/AAP-29982 (caused by https://issues.redhat.com/browse/AAP-27692 )
To test manually, change gunicorn timeout to much lower value and add sleep in a view
See django-ansible-base notes https://github.com/ansible/django-ansible-base/blob/2af5f34dd4887eeba65f48e01e488745e90f8f04/docs/logging.md?plain=1#L56-L70
**Reviewers**: Look for sound code, no [code …
> enable middleware to log traceback on timeout

- galaxy_ng/app/settings.py
Issue: AAP-29982 enable middleware to log traceback on timeout
gunicorn sends a signal 6 when it is about to timeout a request This middleware handles that request and logs a traceback.
this aids in debugging infrastructure issues that may be causing requests to timeout.
(cherry picked from commit 414a532b90fb2e60ff1f28b3b81a382fa0ad9771)
> [backport 4.10] enable middleware to log traceback on timeout (#2254)

- setup.py
RPM Builds are made based on what is on setup.py
to enforce 0.4.29 we need lower bound to bump.
For cloud deployments and Dev env the pin comes
from the requirements files.
> fix: Bump lower bound galaxy_importer on setup.py

- requirements/requirements.common.txt
- requirements/requirements.insights.txt
- requirements/requirements.standalone.txt
- setup.py
Reverts ansible/galaxy_ng#2482
The PR must be merged only after April 17 to get included on May 7 release.
> Revert "backport stable4.10: Bump galaxy-importer to 0.4.29"

- README.md
From this
[![Quality Gate Status](https://sonarcloud.io/api/project_badges/measure?project=ansible_galaxy_ng&metric=alert_status)](https://sonarcloud.io/summary/new_code?id=ansible_galaxy_ng)
To this
[![Maintainability Rating](https://sonarcloud.io/api/project_badges/measure?project=ansible_galaxy_ng&metric=sqale_rating)](https://sonarcloud.io/summary/new_code?id=ansible_galaxy_ng)
Reason: It will take time for us to add code coverage to reach 80% set in the sonar way, not sure this will ever be an effort, the red alert is already reised on the sonar dashboard.
The Maintanability badge will become yellow (B) or red (C) if we ever introduce higher code complexity or code smells.
> chore: Use a different sonar cloud badge on readme

- galaxy_ng/tests/integration/utils/client_ansible_lib.py
Modifies integration tests to NOT use password auth in CRC stage.
Issue: AAP-42264
> tests fix: do not use ephemeral workaround in crc stage

- dev/compose/bin/devinstall
After installing the editable dep, permissions must be fixed.
Dynaconf is still using `setup.py` on 3.2.x, so be able to install it as editable the new pip requires a parameter.
> fix(dev): Set permissions and compat mode for devinstall

- Dockerfile
ref: https://github.com/pypa/setuptools/issues/3649
now:
```
In [1]: from importlib.metadata import entry_points
In [2]: [e.name for e in entry_points(group="pulpcore.plugin") if "galaxy_ng" in e.name]
Out[2]: ['galaxy_ng']
```
before:
```
In [1]: from importlib.metadata import entry_points
In [2]: [e.name for e in entry_points(group="pulpcore.plugin") if "galaxy_ng" in e.name]
Out[2]: ['galaxy_ng', 'galaxy_ng']
```
> Fix duplicated entry_points

- .tekton/automation-hub-galaxy-ng-master-pull-request.yaml
- .tekton/automation-hub-galaxy-ng-master-push.yaml
adds `sast-unicode-check` and `sast-unicode-check` to konflux pipelines to fix enterprise contract errors
> add sast check tasks to konflux pipelines

- galaxy-operator/bin/readyz.py
When readiness script is called by other scripts, it stops checking the APIs health
> Readiness probe: removing the dependency on script name

- galaxy-operator/bin/readyz.py
When readiness script is called by other scripts, it stops checking the APIs health
(cherry picked from commit f9b74e1ca3a8a161ae83381d66e3a6baf5d7198f)
> Readiness probe: removing the dependency on script name (#2570)

- dev/compose/aap.yaml
- dev/compose/certified-sync.yaml
- dev/compose/community.yaml
- dev/compose/standalone.yaml
- galaxy_ng/app/access_control/access_policy.py
- galaxy_ng/app/api/ui/v1/serializers/user.py
- galaxy_ng/app/api/ui/v1/views/settings.py
- galaxy_ng/app/api/ui/v2/permissions.py
- galaxy_ng/app/dynaconf_hooks.py
- galaxy_ng/app/settings.py
- galaxy_ng/tests/integration/aap/test_aap_user_management.py
- galaxy_ng/tests/integration/api/test_groups.py
- galaxy_ng/tests/integration/api/test_load_data.py
- galaxy_ng/tests/integration/api/test_ui_paths.py
- galaxy_ng/tests/integration/conftest.py
- galaxy_ng/tests/integration/dab/test_dab_rbac.py
- galaxy_ng/tests/integration/dab/test_dab_rbac_contract.py
- galaxy_ng/tests/integration/dab/test_disable_shared_resources.py
- galaxy_ng/tests/integration/dab/test_ui_v2.py
Issue: AAP-48071
This PR Replaces the usage of `ALLOW_LOCAL_RESOURCE_MANAGEMENT` flag with the condition based on `RESOURCE_SERVER__URL` being configured.
It adds a new transient setting resolved at the hooking level `IS_CONNECTED_TO_RESOURCE_SERVER` that will resolve to `True` if `RESOURCE_SERVER__URL` is configured, otherwise `False`.
When `IS_CONNECTED_TO_RESOURCE_SERVER` is True, then local resource management is considered disabled.
> fix: remove ALLOW_LOCAL_RESOURCE_MANAGEMENT setting

- requirements/requirements.insights.txt
- requirements/requirements.standalone.txt
- setup.py
Changes the DAB dependency to reference the full commit hash instead of the release tag. 
This is required for the downstream builds to cache the external dependency. For more info see: https://github.com/hermetoproject/hermeto/blob/main/docs/pip.md#external-dependencies
Issue: AAP-49734
> modify dab source to use full commit hash

- galaxy_ng/app/settings.py
- galaxy_ng/tests/integration/api/test_aiindex.py
- galaxy_ng/tests/integration/api/test_ui_paths.py
Makes `sessionId` secure via galaxy_ng's settings.py and allows for it to be overridden by an environment variable `SESSION_COOKIE_SECURE`.
Issue: AAP-47264
> Make sessionId secure and able to be overridden
