README.md
closes #51
Depends on having https://github.com/ansible/galaxy_ng/pull/56 merged
=> Documenting how to use pulplift

README.md
=> Updating readme to include pulp-container

setup.py
=> Fix missing django-storages dependency

.dockerignore, .travis.yml, Dockerfile, MANIFEST.IN, galaxy_ng/app/common/version.py, galaxy_ng/version.py, setup.py
=> Include UI as static files during build package build.

CONTRIBUTING.rst, README.md
- Moving all the development environment setup instructions to the project Wiki
- Adding end-user install instructions to the README
=> README and CONTRIBUTING updates

Dockerfile, cloudwatch_requirements.txt, docker/bin/start-api, docker/bin/start-api-reload, galaxy_ng/contrib/cloudwatch.py
=> Implement CloudWatch gunicorn logger

release_requirements.txt
Needed to properly display descriptions of collection content
=> Bump galaxy-importer version

MANIFEST.in, setup.py
* Download UI distribution to temporary file.
* Extract UI files to the build directory.
=> Refactor package build script

CHANGES/110.bugfix, release_requirements.txt
=> Bump ansible version to fix container uid issue

.github/CODEOWNERS
* Add @chouseknecht as global code owner
=> Update GitHub code owners

CHANGES/108.bugfix, galaxy_ng/app/api/views.py
=> Fix authorization checks for root API views

CHANGES/113.bugfix, galaxy_ng/app/api/v3/viewsets.py
Issue: #113
Signed-off-by: Alexander Saprykin <cutwatercore@gmail.com>
=> Fix override urls for collection version endpoint

Dockerfile, docker/entrypoint.sh
Ping @cutwater - here's the idea we chatted about.
=> Allow for running custom init scripts via volume mounted dir

MANIFEST.in, galaxy_ng/app/settings.py, galaxy_ng/app/urls.py, galaxy_ng/app/webserver_snippets/apache.conf, galaxy_ng/app/webserver_snippets/nginx.conf, galaxy_ng/ui/urls.py
- galaxy_ng/settings.py to set STATIC_URL = "/static/"
- Add a new galaxy_ng view that 302 redirects / to /ui/
- proxy /ui* to /static/galaxy_ng/index.html
=> Introducing UI config

release_requirements.txt
=> Update galaxy-importer to latest

README.md
https://github.com/ansible/galaxy_ng/pull/125
=> Updating README with user install

galaxy_ng/app/management/commands/create-group.py, galaxy_ng/tests/unit/app/management/commands/test_create_group.py
Simple Django management command for creating security group(s) and assigning to users. Will be used during post-install configuration role to configure security.
The following example creates 2 groups, *system:foo* and *system:bar*, and assigns them to *userb*:
```
$ ./compose run --rm api manage create-group system:foo system:bar --users userb
```
=> Add create-group management command

galaxy_ng/__init__.py
Bump version number for new release
=> Release: Add full support for authentication.

galaxy_ng/app/api/urls.py, galaxy_ng/app/api/v3/serializers.py, galaxy_ng/app/api/v3/urls.py, galaxy_ng/app/api/v3/viewsets.py, galaxy_ng/app/api/views.py, galaxy_ng/app/models/collectionimport.py, galaxy_ng/app/settings.py
=> Revert "Use pulp viewsets for 'v3' and add per repo/distro v3 style endpoints"

galaxy_ng/app/api/urls.py, galaxy_ng/app/api/v3/serializers.py, galaxy_ng/app/api/v3/urls.py, galaxy_ng/app/api/v3/viewsets.py, galaxy_ng/app/api/views.py, galaxy_ng/app/models/collectionimport.py, galaxy_ng/app/settings.py, galaxy_ng/tests/unit/api/test_api_ui_auth_views.py, galaxy_ng/tests/unit/api/test_api_ui_user_viewsets.py
Re open of https://github.com/ansible/galaxy_ng/pull/84
=> Use pulp viewsets (#84 part deux)

.flake8, .travis/before_install.sh, .travis/cherrypick.py, setup.py
=> Enable flake8 checks at Travis CI

openapi/ui_openapi.yaml
=> Add openapi defs for /_ui/synclists (#45)

galaxy_ng/app/api/base.py, galaxy_ng/app/api/ui/viewsets/collection.py, galaxy_ng/app/api/v3/viewsets/collection.py, galaxy_ng/tests/unit/api/test_api_ui_auth_views.py
=> Revert "Fix unit tests failing when run in non-standalone mode"

.travis/custom_check_pull_request.py, .travis/pre_before_install.sh, CHANGES/205.misc
=> Travis CI: Validate pull request commit messages

CHANGES/180.feature, galaxy_ng/app/api/base.py, galaxy_ng/app/api/ui/serializers/__init__.py, galaxy_ng/app/api/ui/serializers/collection.py, galaxy_ng/app/api/ui/urls.py, galaxy_ng/app/api/ui/viewsets/__init__.py, galaxy_ng/app/api/ui/viewsets/my_namespace.py, galaxy_ng/app/api/ui/viewsets/namespace.py, galaxy_ng/app/api/urls.py, galaxy_ng/app/api/v3/serializers/__init__.py, galaxy_ng/app/api/v3/serializers/collection.py, galaxy_ng/app/api/v3/serializers/group.py, galaxy_ng/app/api/v3/serializers/namespace.py, galaxy_ng/app/api/v3/urls.py, galaxy_ng/app/api/v3/viewsets/__init__.py, galaxy_ng/app/api/v3/viewsets/namespace.py, galaxy_ng/tests/unit/api/test_api_v3_namespace_viewsets.py, openapi/openapi.yaml
WIP moving of /_ui/namespaces/ endpoints to /v3/namespaces/.
Currently contains https://github.com/ansible/galaxy_ng/pull/192 as well.
Issue: #180 
Issue: #171
=> Add a  /v3/namespaces/ #180 #171

README.md
- Remove `pulp_source_dir`
- Set `galaxy_require_content_approval` to False
=> Update example playbook with latest changes

docker/bin/start-worker
=> Use persistent name for pulp workers

README.md
Fix: https://github.com/ansible/galaxy_ng/issues/226
=> README: Fix example playbook to avoid race condition

.flake8, CHANGES/276.misc, galaxy_ng/tests/unit/api/test_api_ui_collectionversion_viewsets.py, galaxy_ng/tests/unit/api/test_api_ui_my_synclists.py, galaxy_ng/tests/unit/api/test_api_ui_synclists.py, galaxy_ng/tests/unit/api/test_api_v3_namespace_viewsets.py, galaxy_ng/tests/unit/app/management/commands/test_create_group.py, galaxy_ng/tests/unit/app/test_tasks.py
Set flake8 to run on tests and fix issues. Keep skipping `tests/functional/` as they are boilerplate code.
=> Set flake8 to run on tests and fix issues

CHANGES/277.bugfix, galaxy_ng/app/api/ui/serializers/namespace.py
=> Make namespace links writeable

CHANGES.rst, CHANGES/275.feature, CHANGES/288.misc, galaxy_ng/__init__.py
=> Release 4.2.0b10

requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, setup.py
=> Update project requirements

requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt
=> Update galaxy-importer to 0.2.8rc1

.travis/Containerfile.j2, .travis/before_install.sh, .travis/before_script.sh, .travis/build_container.yaml, .travis/install.sh, .travis/script.sh, .travis/start_container.yaml, galaxy_ng/app/api/ui/viewsets/collection.py, galaxy_ng/app/api/v3/viewsets/namespace.py, setup.py
* Updating and fixing the CI
- Making build errors easier to see
- Removing pulpcore upper bound
* OpenAPI v3 with drf-spectacular
No-Issue
(cherry picked from commit 2f0d1dbfcdc23d0f61fa442fdaddcb5c15d4d57d)
=> Updating and fixing the CI (#322)

CHANGES/330.bugfix, requirements/requirements.common.txt, requirements/requirements.insights.in, requirements/requirements.insights.txt, requirements/requirements.standalone.in, requirements/requirements.standalone.txt, requirements/requirements.txt, setup.py
=> Set up galaxy to work with pulp@master.

requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, setup.py
Add missing dependency `drf-spectacular`.
=> Fix missing dependency

galaxy_ng/tests/functional/api/test_crud_content_unit.py, requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt
=> Update galaxy-importer to 0.2.8rc9

CHANGES/333.bugfix, Dockerfile, dev/Dockerfile.base, dev/docker-compose.yml, galaxy_ng/app/api/v3/viewsets/collection.py, galaxy_ng/app/tasks/publishing.py, galaxy_ng/tests/unit/app/test_tasks.py
Changes to use PulpTemporaryFile instead of Artifact as per:
https://pulp.plan.io/issues/6718
https://github.com/pulp/pulp_ansible/pull/335/files
https://github.com/pulp/pulpcore/pull/793/files
Issue: #330
Issue: #333
=> Use PulpTemporaryFile

requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt
=> Update galaxy-importer to 0.2.8rc10

.travis.yml, .travis/generate_python_manifest.py, .travis/post_script.sh, .travis/update_manifest.sh, CHANGES/349.misc
Closes-Issue: #349
Backport: #379 
(cherry picked from commit 75e16d150205df7eb267a7bb19ce7c2425d5b201)
=> Generate security manifest (#379)

requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, requirements/requirements.txt
=> Update galaxy-importer to 0.2.8rc11

CHANGES/304.feature, galaxy_ng/app/access_control/access_policy.py, galaxy_ng/app/access_control/statements/insights.py, galaxy_ng/app/access_control/statements/standalone.py, galaxy_ng/app/api/ui/urls.py, galaxy_ng/app/api/ui/viewsets/__init__.py, galaxy_ng/app/api/ui/viewsets/group.py, galaxy_ng/app/api/ui/viewsets/user.py
=> Expose the pulp group API.

.travis/install.sh, .travis/settings.py.j2, .travis/start_container.yaml, setup.py, template_config.yml
=> Pin pulpcore and update travis

CHANGES/389.feature, galaxy_ng/app/management/commands/assign-permission.py, galaxy_ng/tests/unit/app/management/commands/test_assign_permission.py
=> Add assign-permission management command

CHANGES/372.feature, galaxy_ng/app/api/v3/viewsets/collection.py
=> Add RBAC permisisons for publishing content

CHANGES/404.bugfix, galaxy_ng/app/models/collectionsync.py, galaxy_ng/tests/unit/test_models.py
=> Create namespaces on content sync via django signal

.travis/before_install.sh, requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, requirements/requirements.txt, setup.py
Set `pulp_ansible` dependency to master until `0.3.0 `is released
=> Set pulp_ansible to master and update all requirement files

galaxy_ng/app/api/ui/serializers/collection.py, galaxy_ng/tests/unit/api/test_api_ui_collection_viewsets.py
```json
❯ http :5001/api/automation-hub/_ui/v1/remotes/
HTTP/1.1 200 OK
X-Powered-By: Express
allow: GET, POST, HEAD, OPTIONS
connection: close
content-length: 3753
content-type: application/json
date: Wed, 02 Sep 2020 21:56:45 GMT
server: gunicorn/20.0.4
vary: Accept, Cookie
x-frame-options: SAMEORIGIN
{
"data": [
{
"auth_url": null,
"created_at": "2020-08-31T20:17:34.456349Z",
"last_sync_task": null,
"name": "community",
"policy": "immediate",
"repositories": [
{
"created_at": "2020-08-31T20:19:33.386483Z",
"description": null,
"distributions": [
{
"base_path": "community",
"content_guard": null,
"name": "community"
}
],
"last_sync_task": null,
"name": "community-repo",
"next_version": 1,
"updated_at": "2020-08-31T20:19:33.388732Z"
}
],
"requirements_file": …
```
=> Add `repositories[]>distributions[]` to `ui/remotes` endpoint

CHANGES/362.feature, Dockerfile.rhel8
=> Build container image based on RHEL8

CHANGES/362.feature, Dockerfile.rhel8
Backport: #417 
Backport: #420
=> Build container image based on RHEL8 

.travis/before_install.sh, requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, requirements/requirements.txt, setup.py
=> Update pulp_ansible to 0.3.0

CHANGES/397.feature, galaxy_ng/app/access_control/access_policy.py, galaxy_ng/app/access_control/statements/insights.py, galaxy_ng/app/access_control/statements/standalone.py, galaxy_ng/app/api/ui/serializers/__init__.py, galaxy_ng/app/api/ui/serializers/distribution.py, galaxy_ng/app/api/ui/urls.py, galaxy_ng/app/api/ui/viewsets/__init__.py, galaxy_ng/app/api/ui/viewsets/distribution.py, galaxy_ng/tests/unit/api/test_api_ui_distributions.py
Sample distribution list: 
```
{
"meta": {
"count": 3
},
"links": {
"first": "/api/automation-hub/_ui/v1/distributions/?limit=10&offset=0",
"next": null,
"last": "/api/automation-hub/_ui/v1/distributions/?limit=10&offset=0"
},
"data": [
{
"pulp_id": "64bbf7a5-841a-4b0b-a17b-70cc1e6eea16",
"name": "automation-hub",
"base_path": "automation-hub",
"repository": {
"name": "automation-hub",
"description": "Default repository, the source of downloads",
"pulp_id": "20ab43ad-24ee-4868-8127-88a9ab590317",
"pulp_last_updated": "2020-08-24T17:21:50.572508Z",
"content": [
"2114d1e0-1edb-4d5f-bdd1-c400862c4032"
],
"content_count": 1
}
},
{
"pulp_id": "37d96e76-c99e-4797-abe3-3a4894a9a5d3",
"name": "staging",
"base_path": "staging",
"repository": {
"name": "staging",
"description": …
```
=> Add ui distributions endpoints

CHANGES/445.bugfix, galaxy_ng/app/api/ui/viewsets/collection.py, galaxy_ng/app/api/ui/viewsets/distribution.py
=> Order remotes and distributions by name.

CHANGES/449.misc, galaxy_ng/app/api/v3/viewsets/collection.py
=> Fix move_content error when code does not start curate task

CHANGES/457.misc, galaxy_ng/app/api/ui/viewsets/collection.py
=> Fix api ui collection list endpoint keywords param database error

CHANGES/464.feature, galaxy_ng/app/common/pulp.py
=> Configuration: Allow one to specify the protocol one wants to use

CHANGES/474.misc, galaxy_ng/app/settings.py
=> Add ALLOWED_CONTENT_CHECKSUMS to support FIPS compliance.

setup.py
=> Make setup.py name configurable via environment variable.

.travis/before_install.sh, CHANGES/441.fix, requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, setup.py
=> Upgrade to pulp_ansible 0.4.1

.travis/custom_check_pull_request.py, CHANGES/44.misc, pyproject.toml
Change custom_check_pull_request to point to Jira issues.
https://issues.redhat.com/rest/api/latest/issue/AAH-44
https://issues.redhat.com/browse/AAH-44
Issue: AAH-44
=> Fix travis check_pull_request issue message script

.github/ISSUE_TEMPLATE/config.yml, .github/workflows/lock-closed-issue.yml, .github/workflows/main.yml
Auto close issue and point user to Jira
No-Issue
=> Add github action to auto close issues

galaxy_ng/app/migrations/0004_rbac.py
=> Fix missing dependency in migration

galaxy_ng/app/api/base.py, galaxy_ng/app/api/ui/viewsets/collection.py
No-Issue
Also adds check to LocalSettingsMixin to ensure permission_classes
is implemented
=> Add permissions to ui collections endpoint

galaxy_ng/app/api/ui/viewsets/root.py, galaxy_ng/app/api/v3/viewsets/collection.py, galaxy_ng/app/api/views.py
No-Issue
Related to https://github.com/ansible/galaxy_ng/pull/524
=> Update api views with missing permission classes

.travis/before_install.sh, CHANGES/34.misc, requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, setup.py
Closes-Issue: AAH-34
https://issues.redhat.com/browse/AAH-34
Fix v3 collection list showing wrong count on empty repo
=> Upgrade to pulp_ansible 0.4.2

galaxy_ng/app/api/ui/viewsets/root.py, galaxy_ng/app/api/views.py
Adds explicit permission that was previously inherited
Related to #524, #527
No-Issue
=> Add explict IsAuthenticated permission to root endpoints

CHANGES/90.misc, galaxy_ng/app/api/ui/serializers/collection.py, galaxy_ng/app/api/ui/viewsets/collection.py
Supports version dropdown on collection detail page.
https://issues.redhat.com/browse/AAH-90
Issue: AAH-90
=> Fix version query param on ui api collection detail endpoint

CHANGES/26.misc, galaxy_ng/app/migrations/0012_move_collections_by_certification.py
=> Add migration to move collections by certification field

galaxy_ng/app/migrations/0012_partner_engineer_group_migrations.py, galaxy_ng/app/migrations/0013_partner_engineer_group_migrations.py
=> Create migration to add relevant permissions to partner engineer group.

CHANGES/105.misc, galaxy_ng/app/api/v3/serializers/namespace.py
=> Set namespace name validation to match the importer.

requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt
=> Update galaxy-importer to 0.2.9

.travis/before_install.sh, requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, setup.py
=> Upgrade to pulp_ansible 0.4.3

galaxy_ng/app/api/v3/serializers/collection.py, galaxy_ng/app/api/v3/viewsets/collection.py, galaxy_ng/app/tasks/publishing.py, galaxy_ng/tests/unit/app/test_tasks.py
https://issues.redhat.com/browse/AAH-118
dependent on https://github.com/pulp/pulp_ansible/pull/407
=> Fix the passing along of filename data

CHANGES/131.misc, CHANGES/89.bugfix, requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, setup.py
https://issues.redhat.com/browse/AAH-89
https://issues.redhat.com/browse/AAH-131
Issue: AAH-89
Issue: AAH-131
=> Upgrade to galaxy-importer 0.2.11

galaxy_ng/app/api/v3/serializers/sync.py
=> Fix issue where repos were returning the first sync task, not the last.

galaxy_ng/app/api/ui/serializers/user.py, galaxy_ng/tests/unit/api/base.py, galaxy_ng/tests/unit/api/test_api_ui_user_viewsets.py
=> Ensure users can't create new users with elevated permissions.

requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, requirements/requirements.txt, setup.py
* Pin pulp_ansible to a z-stream release - Helps to ensure future updates to pulp_ansible will be pinned to a z-stream, otherwise when a new pulp_ansible z-stream releases, it will automatically get included in an on-prem automation-hub installation
* Update all deps in requirements files via pip-compile
No-Issue
=> Pin pulp_ansible in setup.py and update deps in requirements

.travis/before_install.sh, requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, setup.py
=> Upgrade pulp_ansible to 0.5.1 (#561)

galaxy_ng/app/api/v3/serializers/collection.py, galaxy_ng/app/api/v3/viewsets/collection.py, galaxy_ng/app/tasks/publishing.py, galaxy_ng/tests/unit/app/test_tasks.py
No-Issue
(cherry picked from commit c928b05360dd6cc9426dfcd474ce94c01429d13f)
=> Fix the passing along of filename data (#573)

.travis/before_install.sh, requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, setup.py
=> Upgrade to pulp_ansible 0.5.2

.travis/before_install.sh, CHANGES/176.misc, requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, setup.py
=> Upgrade to pulp_ansible 0.5.3

requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, requirements/requirements.txt, setup.py
=> Update galaxy-importer to 0.2.12

.travis/before_install.sh, requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, setup.py
=> Update pulp_ansible requirement to 0.5.4

CHANGES/203.bugfix, galaxy_ng/app/api/utils.py
=> Fix error filename format on parse_collection_filename

galaxy_ng/app/api/ui/serializers/user.py
Fix standalone UserAccessPolicy to require is_current_user
Add has_groups_param_obj_perms condition to UserAccessPolicy
=> Don't allow user to modify other users groups aah148

CHANGES.rst, CHANGES/132.bugfix, CHANGES/139.misc, CHANGES/152.bugfix, CHANGES/166.bugfix, CHANGES/176.misc, CHANGES/195.bugfix, CHANGES/203.bugfix, galaxy_ng/__init__.py
=> Release 4.2.1

CHANGES/220.bugfix, requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, requirements/requirements.txt, setup.py
=> Fix the galaxy-importer check for max size of docs files

.travis/script.sh, CHANGES/57.feature, galaxy_ng/app/api/v3/serializers/collection.py, galaxy_ng/app/api/v3/serializers/task.py, galaxy_ng/app/common/openapi.py, galaxy_ng/app/settings.py, galaxy_ng/app/urls.py
WIP for getting a openapi spec we can use with c.r.c
Issue: AAH-57
=> Open API Updates AAH-57

.github/CODEOWNERS
=> Remove CODEOWNERS to stop automatic review request.

CHANGES/295.misc, requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, requirements/requirements.txt, setup.py
=> Update galaxy-importer to 0.2.14

CHANGES/295.misc, requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, requirements/requirements.txt, setup.py
Issue: AAH-295
(cherry picked from commit f1e7011864da5b0ccf5a6c91959214fe100c05fa)
=> Update galaxy-importer to 0.2.14 (#625)

.travis/before_install.sh, CHANGES/318.misc, requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, setup.py
=> Update pulp-ansible and django deps in stable-4.2

CHANGES/299.misc, requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, requirements/requirements.txt, setup.py
=> Update django dependency

requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, requirements/requirements.txt, setup.py
* Upgrade galaxy-importer to latest in setup.py
* Upgrade all packages dependencies via `pip-compile --upgrade`
Related:
* pygments dep issue: https://bugzilla.redhat.com/show_bug.cgi?id=1922136
* cryptography dep issue: https://bugzilla.redhat.com/show_bug.cgi?id=1926226 AAH-331
* bleach issue https://bugzilla.redhat.com/show_bug.cgi?id=1827491 AAH-327 AAH-328
=> Update project dependencies to latest

build_deploy.sh, pr_check.sh
These scripts are part of the new CI pipeline and are needed
to build and push container images to Quay.
=> Add build_deploy.sh and pr_check.sh scripts

.travis/before_install.sh, CHANGES/224.feature, galaxy_ng/app/api/v3/serializers/__init__.py, galaxy_ng/app/api/v3/serializers/collection.py, galaxy_ng/app/api/v3/urls.py, galaxy_ng/app/api/v3/viewsets/__init__.py, galaxy_ng/app/api/v3/viewsets/collection.py, galaxy_ng/tests/unit/api/test_api_v3_collections.py, requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, setup.py
Issue: AAH-224
- Added v3/collections/all for UnpaginatedCollections
- Added v3/collection_versions/all for UnpaginatedCollectionVersions
- Added v3/ for RepoMetadata
=> Add Unpaginated Collection and Metadata endpoints for better sync performance

.travis/before_install.sh, CHANGES/407.bugfix, galaxy_ng/__init__.py, requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, requirements/requirements.txt, setup.py
- Upgrades to pulp_ansible 0.5.8
- Bumps version to 4.2.3b1
=> Upgrade to pulp_ansible 0.5.8

CHANGES/145.feature, openshift/database-migration.yaml
=> Add OpenShift job template to run migrations

.travis.yml, .travis/Containerfile.j2, .travis/before_install.sh, .travis/filter/repr.py, .travis/settings.py.j2, .travis/start_container.yaml, .travis/utils.sh
=> Updating CI based on plugin-template

openshift/database-migration.yaml
=> Fix openshift job template

openshift/database-migration.yaml
=> Fix openshift database migration job

requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, setup.py
Update using 'make requirements'
No-Issue
=> Update to latest galaxy-importer and update all python deps

CHANGES/433.misc, galaxy_ng/app/api/ui/serializers/execution_environment.py
=> Add last_sync_task and pulp_labels to e-e/repositories/

requirements/requirements.dev.txt
ref: https://github.com/ipython/ipython/issues/12740#issuecomment-751273584
solution: pin jedi to 0.17.2
No-Issue
=> [dev env] Auto complete broken on django shell with ipython

CHANGES/483.misc, requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, setup.py
=> Upgrade pulp-container to 2.5.0

requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, setup.py
=> Update pulp-container req to 2.5.1

openshift/database-migration.yaml
=> Add missing S3 credentials to database migration job

CHANGES/500.feature, galaxy_ng/app/api/ui/serializers/user.py, galaxy_ng/tests/unit/api/test_api_ui_user_viewsets.py
=> Allow creating super users.

CHANGES/498.bugfix, requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, requirements/requirements.txt
- aiohttp -> 3.7.4
- pulpcore -> 3.7.5
- allow pyyaml update
- pyyaml -> 5.4
- urllib3 -> 1.26.4
- requests -> 2.25.1
- boto3 -> 1.17.48
- botocore -> 1.20.48
Issue: AAH-498
=> Update deps with security updates

CHANGES/298.feature, galaxy_ng/app/api/ui/urls.py, galaxy_ng/app/api/ui/views/__init__.py, galaxy_ng/app/api/ui/views/feature_flags.py, galaxy_ng/app/settings.py, galaxy_ng/tests/unit/api/test_api_ui_feature_flags.py
* Add feature flag dictionary to settings.py
* Add _ui/v1/feature-flags/ to display feature flag setting, i.e.:
* `{"execution_environments":true}`
* Conditionally add execution environment routes based on feature flag
AAH-298
=> Add feature flag to enable/disable execution environments

.github/workflows/galaxy_custom_ci.yml, .github/workflows/scripts/check_commits.py, .github/workflows/scripts/check_commits.sh, .travis/before_install.sh, .travis/pre_before_install.sh
On a merge, check that all commits link to JIRA issue (today they are not checked).
On a PR, check that at least one commit links to JIRA issue (today it checks every commit).
=> Update commit checks for link to JIRA issue

requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, setup.py
=> Update pulp_container dep to 2.5.2

.compose.env.example, CHANGES/424.misc, docker/entrypoint.sh
=> Make waiting-for-migrations script call optional

CHANGES/428.bugfix, galaxy_ng/app/api/utils.py
=> Improve errors for max length violations in collection filename import

Makefile
=> Fix PIP_COMPILE_UPDATE_SPEC for 'make requirements'

.travis/before_install.sh, CHANGES/563.misc, requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, setup.py
=> Update pulpcore dep to 3.11.1

.travis/before_install.sh, CHANGES/570.misc, requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, setup.py
=> Update pulp_ansible dep to 0.7.3

CHANGES/576.misc, requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt
=> Update all deps

CHANGES/588.feature, requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, setup.py
Update to `galaxy-importer==0.3.2` and run `make requirements`
Issue: AAH-588
=> Update to galaxy-importer version that uses ansible-core 2.11

setup.py
=> Backport 746

dev/Dockerfile.base
Signed-off-by: Julen Landa Alustiza <jlanda@redhat.com>
=> dev: use centos image from quay

CHANGES/583.bugfix, requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, requirements/requirements.txt
=> Fix "CVE-2021-32052 django: header injection" by moving to django 2.2.23

.travis/before_install.sh, CHANGES/647.misc, requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, setup.py
=> Update pulpcore req to 3.11.2  AAH-647

CHANGES/382.feature, CHANGES/581.feature, Dockerfile.rhel8, docker/entrypoint.sh, docker/etc/settings.py, openshift/clowder/clowd-app.yaml, openshift/clowder/clowd-environment.yaml, requirements/requirements.insights.in, requirements/requirements.insights.txt
* Update `settings.py` with Redis config provided by Clowder
* Create templates for remaining Automation Hub services, for deploying via Clowder
Issue: 581
Issue: 382
=> Clowder configuration for ephemeral environments

requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, setup.py
- Pin click to version 7 to prevent CI from updating
- Pin ansible to 2.10.x
- Update dependencies to latest
=> Update 4.2 requirements.

CHANGES/661.bugfix, galaxy_ng/app/api/v3/serializers/collection.py, galaxy_ng/app/webserver_snippets/apache.conf, galaxy_ng/app/webserver_snippets/nginx.conf
Backport: #781 
Issue: AAH-661
(cherry picked from commit 8d93c60a9ac72b12ab411b6b824627d35966bc3d)
=> Backport 781 - Update collection download urls

CHANGES.rst, CHANGES/583.bugfix, CHANGES/661.bugfix, galaxy_ng/__init__.py
=> Release 4.2.4

openshift/clowder/clowd-app.yaml
=> Clowder: Set k8s access level for pulp-worker

README.md
See https://github.com/ansible/community/issues/613
=> Update irc server

docker/bin/start-content-app
=> Make pulp-content-app port configurable

CHANGES/743.feature, galaxy_ng/app/api/utils.py, galaxy_ng/app/api/v3/viewsets/collection.py, galaxy_ng/app/settings.py
=> Add unix socket support to collection version download view

CHANGES/743.feature, galaxy_ng/app/api/utils.py, galaxy_ng/app/api/v3/viewsets/collection.py, galaxy_ng/app/settings.py
Issue: AAH-743
(cherry picked from commit 9918e8fa3e29dc2c3d8c69fffc0591c934b8f286)
=> Add unix socket support to collection version download view (#826)

pr_check.sh
Update bonfire call in the `pr_check.sh` script, add components to the
`--no-remove-resources` parameters.
No-Issue
=> Update bonfire call due to change in new release

ROADMAP.rst
=> Fix roadmap link to work for jira sessions logged in or out

openshift/clowder/clowd-app.yaml
Required PR: https://github.com/ansible/galaxy_ng/pull/821
No-Issue
=> Remove pulp 'resource-manager' from clowd-app.yaml

CHANGES/781.bugfix, docker/etc/settings.py
=> Fix typo in AWS S3 configuration for Clowder

.travis.yml, .travis/Containerfile.j2, CHANGES/603.misc, dev/Dockerfile.base
Upgrades the dev environment to Python 3.8 and the base image to ubi8:8.2.
Issue: AAH-603
=> Upgrade dev environment 

Dockerfile.rhel8
=> Update python to 3.8 in container image

dev/Dockerfile.base
=> Make dev environment base image consistent with Dockerfile.rhel8

.travis.yml, .travis/Containerfile.j2
Support pulp oci py3.8 update
https://github.com/pulp/pulp-oci-images/pull/100
No-Issue
=> Update travis to py3.8 to support pulp oci images

requirements/requirements.insights.txt
=> Update to botocore 1.20.69

.travis.yml, .travis/Containerfile.j2, .travis/before_install.sh
* Containerfile.j2 updates from cc7f213
* Pin travis pulpcore version
* Update travis to py3.8 to support pulp oci image
=> Update travis config to fix CI issues

Makefile
No-Issue
(cherry picked from commit 746441801969af9057d46e4e34f3bd76a71afa96)
=> Add make endpoint that updates requirements without using pip (#850)

.github/CODEOWNERS
No-Issue
(cherry picked from commit 1f6eb3f4a90d5acb8da9bd0b54856a7ae2b5915c)
=> Remove CODEOWNERS to stop automatic review request. (#624)

CHANGES/815.bugfix, openshift/clowder/clowd-app.yaml, pr_check.sh
=> Fix missing ansible-importer configuration

CHANGES/815.bugfix, docker/etc/settings.py, openshift/clowder/clowd-app.yaml, pr_check.sh
=> Fix missing ansible-importer configuration (#864)

openshift/clowder/clowd-app.yaml
=> Clowder: Configure nginx container

openshift/clowder/clowd-app.yaml
=> Clowder: Parametrize minReplicas for ClowdApp

docker/etc/settings.py
=> Clowder: Fix S3 credentials in settings

MANIFEST.in, pyproject.toml
ref: https://www.reddit.com/r/Python/comments/40s8qw/simplify_your_manifestin_commands/
No-Issue
=> Simplify MANIFEST.in for static files

docker/etc/settings.py
No-Issue
(cherry picked from commit 81719fddfa1b75ca38391671acef471e2aa6cafd)
=> Clowder: Fix S3 credentials in settings (#877)

CHANGES/837.misc, galaxy_ng/app/api/ui/serializers/execution_environment.py, galaxy_ng/app/api/v3/serializers/sync.py, galaxy_ng/app/api/v3/serializers/task.py, galaxy_ng/app/api/v3/views/sync.py, galaxy_ng/app/api/v3/viewsets/collection.py, galaxy_ng/app/tasks/synclist.py, galaxy_ng/tests/unit/api/test_api_ui_my_synclists.py, galaxy_ng/tests/unit/api/test_api_ui_synclists.py
=> Replace pulp_id with pk on pulp tasks.

openshift/clowder/clowd-app.yaml
=> Clowder: Fix REDIS_SSL placeholder

docker/etc/settings.py
(cherry picked from commit 90043496bcc1abb8ef470811f17390eb7ca58ea7)
=> Clowder: Fix tls support for S3 service (#876)

docker/etc/settings.py, galaxy_ng/contrib/cloudwatch.py
=> WIP: Clowder: CloudWatch logging

openshift/clowder/clowd-app.yaml
=> Update openshift galaxy-importer config map with new setting

requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, setup.py
=> Temporary: Update pulpcore debugging, add 2nd entrypoint

requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, setup.py
=> Temporary: continue debugging, move conditional import to top

Makefile
=> Rename make requirements commands and have them be consistent

Makefile
=> Rename make requirements commands and have them be consistent (#932)

.compose.env.example, dev/standalone-keycloak/docker-compose.yml
=> Allow configuration of KEYCLOAK_HOST_LOOPBACK env var

CHANGES/902.feature, galaxy_ng/app/api/ui/viewsets/collection.py, galaxy_ng/tests/unit/api/test_api_ui_collection_viewsets.py
=> Add dependency filter to ui collection versions endpoint

template_config.yml
=> Disable single_commit_check

CHANGES/897.feature, galaxy_ng/app/api/ui/viewsets/execution_environment.py
Issue: AAH-897
This pr adds filtering to the container registries endpoint.
=> add filtering to container registries endpoint

CHANGES/906.feature, galaxy_ng/app/api/ui/serializers/__init__.py, galaxy_ng/app/api/ui/serializers/execution_environment.py, galaxy_ng/app/api/ui/urls.py, galaxy_ng/app/api/ui/viewsets/__init__.py, galaxy_ng/app/api/ui/viewsets/execution_environment.py
Adds `/api/galaxy/_ui/v1/execution-environments/<repository>/_content/tags/` endpoint that lists the tags in a container repository along with the container manifest that each tag corresponds to.
- name
- icontains
- exact
- starts_with
- contains
- tagged_manifest__digest
- icontains
- exact
- starts_with
- contains
- pulp_created
- name
```
{
"meta": {
"count": 1
},
"links": {
"first": "/api/automation-hub/_ui/v1/execution-environments/repositories/alpine/_content/tags/?limit=10&offset=0&tagged_manifest__digest__icontains=sha256%3Abe9bdc0ef8e96dbc428dc189b31e2e3b05523d96d12ed627c37aa2936653258c",
"next": null,
"last": "/api/automation-hub/_ui/v1/execution-environments/repositories/alpine/_content/tags/?limit=10&offset=0&tagged_manifest__digest__icontains=sha256%3Abe9bdc …
```
=> Add container tags endpoint

.ci/scripts/check_pulpcore_imports.sh, CHANGES/710.feature, galaxy_ng/app/access_control/statements/insights.py, galaxy_ng/app/access_control/statements/standalone.py, galaxy_ng/app/api/v3/urls.py, galaxy_ng/app/api/v3/viewsets/collection.py, galaxy_ng/app/api/v3/viewsets/namespace.py, galaxy_ng/app/tasks/__init__.py, galaxy_ng/app/tasks/deletion.py, galaxy_ng/tests/unit/api/test_api_v3_collections.py, template_config.yml
Allow DELETE requests on collection version endpoint.
Continuing from #939
Issue: AAH-710
=> Support deleting a collection version

.compose.env.example, dev/docker-compose.yml, galaxy_ng/app/common/openapi.py, galaxy_ng/app/dynaconf_hooks.py
Add this to the `.compose.env`
```bash
PULP_GALAXY_ENABLE_CORS=true
PULP_GALAXY_CORS_ALLOWED_ORIGINS="*"
PULP_GALAXY_CORS_ALLOWED_HEADERS="*"
```
re-run the containers
```bash
./compose down
./compose up
```
Access the swagger UI on http://0.0.0.0:8003 or http://localhost:8003/
https://user-images.githubusercontent.com/458654/133476974-7653ba49-dd26-4420-9b69-8abe52bfe5c5.png
=> Add Swagger UI to the dev environment compose.

CHANGES/711.feature, galaxy_ng/app/access_control/statements/insights.py, galaxy_ng/app/access_control/statements/standalone.py, galaxy_ng/app/api/v3/urls.py, galaxy_ng/app/api/v3/viewsets/collection.py, galaxy_ng/app/tasks/__init__.py, galaxy_ng/app/tasks/deletion.py, galaxy_ng/tests/unit/api/base.py, galaxy_ng/tests/unit/api/test_api_v3_collections.py
Allow DELETE requests on collection endpoint.
Rebased off of #962 
Issue: AAH-711
=> Support deleting a collection

CHANGES/438.feature, galaxy_ng/app/access_control/access_policy.py, galaxy_ng/app/access_control/statements/standalone.py, galaxy_ng/app/api/ui/urls.py, galaxy_ng/app/api/ui/views/__init__.py, galaxy_ng/app/api/ui/views/sync.py
Issue: AAH-438
Create remote sync api endpoint.
=> remote sync endpoint

CHANGES/945.feature, galaxy_ng/app/access_control/statements/standalone.py, galaxy_ng/app/api/ui/serializers/execution_environment.py, galaxy_ng/app/api/ui/urls.py, galaxy_ng/app/api/ui/views/__init__.py, galaxy_ng/app/api/ui/views/sync.py, galaxy_ng/app/tasks/__init__.py, galaxy_ng/app/tasks/registry_sync.py
=> Add api endpoint to sync all remotes in a container registry.

CHANGES/940.bugfix, galaxy_ng/app/access_control/statements/pulp_container.py
drf-access-policy>=1.0.0 requires use of condition_expression when
using boolean logic in access statements
AAH-940
=> Fix container pull error to make compatible with drf-access-policy

CHANGES/918.bugfix, requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, setup.py
The new release adds ip address to logging
Issue: AAH-918
=> Update django-automated-logging version

galaxy_ng/app/viewsets.py
=> Fix the need to redeclare viewsets using PEP0562

galaxy_ng/app/api/ui/viewsets/collection.py
=> Add partial match filters to collection versions endpoint.

CHANGES/931.feature, galaxy_ng/app/access_control/statements/standalone.py, galaxy_ng/app/api/ui/serializers/execution_environment.py, galaxy_ng/app/api/ui/urls.py, galaxy_ng/app/api/ui/views/index_execution_environments.py, galaxy_ng/tests/unit/api/test_api_ui_container_registry_remote.py, galaxy_ng/tests/unit/api/test_api_ui_container_remote.py
=> Allow deletion of ContainerRegistryRemote

CHANGES/964.features, galaxy_ng/app/api/ui/serializers/execution_environment.py, galaxy_ng/app/api/ui/viewsets/execution_environment.py
Issue: https://issues.redhat.com/browse/AAH-964
=> Add manifest list information to the container images api

galaxy_ng/app/access_control/access_policy.py, galaxy_ng/app/access_control/statements/standalone.py, galaxy_ng/app/api/ui/views/sync.py
=> Fix permission check on container sync endpoint.

openshift/clowder/clowd-app.yaml
=> Clowder: Add database migrations job (#847)

CHANGES/1095.bugfix, galaxy_ng/app/api/ui/viewsets/execution_environment.py
=> Fix container deletion for remote repos

openshift/clowder/clowd-app.yaml
=> Clowder: reduce db-migration memory limit to request ration

openshift/clowder/clowd-app.yaml
=> Clowder: reduce db-migration memory limit to request ratio (#1048)

openshift/clowder/clowd-app.yaml
=> Clowder: convert db-migration to init-container (#1050)

CHANGES/946.misc, requirements/requirements.insights.txt, setup.py
=> Update to galaxy-importer==0.4.2 which uses ansible-core 2.12

galaxy_ng/tests/functional/api/test_container_sync_and_manifest_lists.py, galaxy_ng/tests/functional/utils.py
Jira issue: https://issues.redhat.com/browse/AAH-964
=> Add functional tests for manifest lists

.travis/before_install.sh, CHANGES/840.bugfix, requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, setup.py
=> 4.3 - Update pulp_ansible to 0.7.4

.travis/before_install.sh, requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, setup.py
=> 4.2 - Update pulp_ansible to 0.5.9

openshift/clowder/clowd-app.yaml
=> change IMPORTER_IMAGE_TAG to string parameter

.travis/before_install.sh, CHANGES/910.bugfix, requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, setup.py
=> Update pulpcore and pulp ansible

CHANGES.rst, CHANGES/910.bugfix, galaxy_ng/__init__.py
=> Release 4.2.7

CHANGES/1162.bugfix, galaxy_ng/app/api/v3/viewsets/collection.py
=> Fix the response for collection downloads in insights mode

CHANGES/1200.bugfix, galaxy_ng/app/api/views.py
=> Look up distro by base path instead of name on API root

galaxy_ng/tests/functional/api/test_container_repository_tags.py, galaxy_ng/tests/functional/utils.py
=> Enable Azure test

CHANGES/1042.misc, Dockerfile.rhel8, galaxy_ng/tests/functional/api/test_container_repository_tags.py, galaxy_ng/tests/functional/utils.py
=> Remove all vim packages

.ci/scripts/validate_commit_message_custom.py, CHANGES/1106.misc
=> Skip checking commit messages from dependabot (ui repo)

CHANGES.rst, CHANGES/1015.misc, CHANGES/1094.bugfix, CHANGES/1188.bugfix, CHANGES/1200.bugfix, CHANGES/804.misc, galaxy_ng/__init__.py, galaxy_ng/app/__init__.py, setup.cfg, setup.py
Previous: [4.4.0](https://github.com/ansible/galaxy_ng/pull/1059)
No-Issue
[API PRs](https://github.com/ansible/galaxy_ng/pulls?q=is%3Apr+base%3Astable-4.4+is%3Amerged+-author%3Aapp%2Fdependabot+merged%3A2021-11-19..2022-01-06)
[UI PRs](https://github.com/ansible/ansible-hub-ui/pulls?q=is%3Apr+base%3Astable-4.4+is%3Amerged+-author%3Aapp%2Fdependabot+merged%3A2021-11-19..2022-01-06)
=> Release 4.4.1

CHANGES/1038.misc, docker/etc/settings.py
=> Enable ssl for rds connectivity

galaxy_ng/app/api/v3/viewsets/collection.py, galaxy_ng/app/tasks/publishing.py, galaxy_ng/tests/functional/cli/test_collection_upload.py, galaxy_ng/tests/unit/app/test_tasks.py
=> Add username to audit log when uploading collections

galaxy_ng/app/access_control/statements/pulp_container.py
Ref: https://github.com/pulp/pulpcore/pull/1627
=> Rename `permissions_assignment` to `creation_hooks`

galaxy_ng/app/api/v3/viewsets/collection.py
=> Fix dispatch args and kwargs in the move api

pr_check.sh
=> Configure minio routes and settings for ephemeral stacks

dev/common/RUN_INTEGRATION.sh, galaxy_ng/tests/integration/api/test_namespace_management.py, galaxy_ng/tests/integration/conftest.py, galaxy_ng/tests/integration/utils.py
https://issues.redhat.com/browse/AAH-1303
=> Add integration tests for namespace create+delete for _ui/v1 and v3

.github/pull_request_template.md, CHANGES/1219.misc
=> Add pull request template

galaxy_ng/tests/integration/api/test_move.py, galaxy_ng/tests/integration/conftest.py
Add integration tests for the move api.
https://issues.redhat.com/browse/AAH-1268
=> Add integration tests for the move api.

galaxy_ng/tests/integration/api/test_artifact_upload.py, galaxy_ng/tests/integration/api/test_namespace_management.py, galaxy_ng/tests/integration/cli/test_cli_flow.py, galaxy_ng/tests/integration/cli/test_dependencies.py, galaxy_ng/tests/integration/conftest.py, galaxy_ng/tests/integration/utils.py
=> Re-enable cli integration tests

galaxy_ng/tests/integration/api/test_collection_delete.py, galaxy_ng/tests/integration/conftest.py, galaxy_ng/tests/integration/utils.py
Tests for collection/version deletion
=> Tests for collection/version deletion

galaxy_ng/tests/integration/api/test_synclist.py, galaxy_ng/tests/integration/conftest.py
Add integration tests for synclist objects and curating a synclist repo
=> Add integration tests for synclists 

CHANGES.rst, CHANGES/1018.bugfix, CHANGES/1202.bugfix, CHANGES/1243.bugfix, CHANGES/1254.bugfix, galaxy_ng/__init__.py, galaxy_ng/app/__init__.py, setup.cfg, setup.py
Previous: [4.4.1](https://github.com/ansible/galaxy_ng/pull/1094)
UI changelog PR https://github.com/ansible/ansible-hub-ui/pull/1708
[API PRs](https://github.com/ansible/galaxy_ng/pulls?q=is%3Apr+base%3Astable-4.4+is%3Amerged+-author%3Aapp%2Fdependabot+merged%3A2022-01-06..2022-02-28)
[UI PRs](https://github.com/ansible/ansible-hub-ui/pulls?q=is%3Apr+base%3Astable-4.4+is%3Amerged+-author%3Aapp%2Fdependabot+merged%3A2022-01-06..2022-02-28)
=> Release 4.4.2

requirements/requirements.insights.txt, requirements/requirements.standalone.txt
=> Temp `stable` update pulpcore 3.17 commit to harden tasks

.ci/scripts/check_pulpcore_imports.sh, dev/ephemeral/smoke_test.sh, galaxy_ng/app/settings.py, galaxy_ng/openapi/__init__.py, galaxy_ng/tests/integration/api/test_openapi.py, galaxy_ng/tests/integration/conftest.py, integration_requirements.txt, template_config.yml
https://issues.redhat.com/browse/AAH-1169
=> fix openapi spec

CHANGES/1389.bugfix, galaxy_ng/app/api/ui/viewsets/execution_environment.py, galaxy_ng/app/tasks/deletion.py
Issue: AAH-1389
(cherry picked from commit 947e7d38a429c314da05f675742b5671506515d7)
=> 4.4 Prevent artifact removal from latest version when deleting images

.github/workflows/scripts/before_install.sh, .github/workflows/scripts/install.sh, CHANGES/1373.bugfix, requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, setup.py, template_config.yml
Updating dependencies and CI for the latest pulp_container release (2.10.2)
Issue: AAH-1373
=> Update pulp_container dependency

CHANGES.rst, CHANGES/1373.bugfix, CHANGES/1384.bugfix, CHANGES/1389.bugfix, CHANGES/1400.bugfix, CHANGES/1411.bugfix, galaxy_ng/__init__.py, galaxy_ng/app/__init__.py, setup.cfg, setup.py
=> Release 4.4.3

.ci/scripts/validate_commit_message_custom.py
https://github.com/ansible/automation-hub-deploy/runs/5651913617?check_suite_focus=true#step:3:26
```
Run curl https://raw.githubusercontent.com/ansible/galaxy_ng/master/.ci/scripts/validate_commit_message_custom.py | python
curl https://raw.githubusercontent.com/ansible/galaxy_ng/master/.ci/scripts/validate_commit_message_custom.py | python
shell: /usr/bin/bash -e {0}
env:
PY_COLORS: 1
ANSIBLE_FORCE_COLOR: 1
GITHUB_PULL_REQUEST: 6
GITHUB_PULL_REQUEST_BODY: No-Issue
GITHUB_BRANCH: img/check_image_build
GITHUB_REPO_SLUG: ansible/automation-hub-deploy
GITHUB_TOKEN: ***
GITHUB_CONTEXT: https://api.github.com/repos/ansible/automation-hub-deploy/pulls/6/commits
GITHUB_PR_COMMITS_URL: https://api.github.com/repos/ansible/automation-hub-deploy/pulls/6/commits
START_COMMIT: …
```
=> Use the auth token if available for github api calls

galaxy_ng/app/api/ui/serializers/collection.py
Fixes: https://github.com/ansible/galaxy_ng/pull/1182#pullrequestreview-920451631
=> Fix related fields on ui collections view

docker/entrypoint.sh
Disabling this until the RBAC work is completed.
No-Issue
=> Disable maintain-pe-group management command

CHANGES/1360.misc, Dockerfile.rhel8, build_deploy.sh, galaxy_ng/app/api/views.py
Issue: AAH-1360
Add git commit to api root, populated via crc pipeline
=> Add git commit to api root, populated via crc pipeline

dev/ephemeral/smoke_test.sh, galaxy_ng/contrib/cloudwatch.py
* update watchtower config to support the update from v1.0.6 to v3.0.0 [(#1204)](https://github.com/ansible/galaxy_ng/pull/1204)
* add bonfire and sh python modules to smoke test to aid in troubleshooting pr-checks
No-Issue
=> update watchtower config for v3

CHANGES/1092.misc, CHANGES/1093.misc, galaxy_ng/app/access_control/fields.py, galaxy_ng/app/access_control/mixins.py, galaxy_ng/app/access_control/statements/__init__.py, galaxy_ng/app/access_control/statements/roles.py, galaxy_ng/app/api/ui/serializers/execution_environment.py, galaxy_ng/app/api/ui/viewsets/distribution.py, galaxy_ng/app/api/ui/viewsets/execution_environment.py, galaxy_ng/app/api/ui/viewsets/my_namespace.py, galaxy_ng/app/api/ui/viewsets/my_synclist.py, galaxy_ng/app/auth/auth.py, galaxy_ng/app/management/commands/maintain-pe-group.py, galaxy_ng/app/models/auth.py, galaxy_ng/app/signals/handlers.py, galaxy_ng/app/viewsets.py, galaxy_ng/tests/integration/api/test_locked_roles.py, galaxy_ng/tests/integration/conftest.py, galaxy_ng/tests/unit/api/base.py, galaxy_ng/tests/unit/api/synclist_base.py, galaxy_ng/tests/unit/api/test_api_ui_container_remote.py, galaxy_ng/tests/unit/api/test_api_ui_distributions.py, galaxy_ng/tests/unit/api/test_api_ui_my_synclists.py, galaxy_ng/tests/unit/api/test_api_ui_sync_config.py, galaxy_ng/tests/unit/api/test_api_ui_user_viewsets.py, galaxy_ng/tests/unit/api/test_api_v3_namespace_viewsets.py, galaxy_ng/tests/unit/api/test_api_v3_tasks.py
Reverts ansible/galaxy_ng#1205
=> Reinstate RBAC Roles into 4.6

CHANGES/1468.misc, docker/etc/settings.py
If S3 location is in AWS:
* configure virtual-hosted addressing style
* configure signature v3
* set endpoint URL to match virtual-hosted addressing style
Issue: AAH-1468
=> configure S3 for virtual hosted style and signature v4

.github/workflows/ci_standalone.yml, dev/common/RUN_INTEGRATION.sh
=> Continue on error does not work as expected.

galaxy_ng/app/access_control/statements/insights.py, galaxy_ng/app/access_control/statements/standalone.py, galaxy_ng/app/api/v3/views/excludes.py, galaxy_ng/app/api/v3/views/not_found.py, galaxy_ng/tests/integration/api/test_sync_enhancement_endpoints.py
=> Enable repo metadata endpoint

.github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, template_config.yml
=> Add the PULP_USER env var to CI tasks so that backport checks pass

galaxy_ng/app/access_control/statements/insights.py, galaxy_ng/app/access_control/statements/standalone.py, galaxy_ng/app/api/v3/views/excludes.py, galaxy_ng/app/api/v3/views/not_found.py, galaxy_ng/tests/integration/api/test_sync_enhancement_endpoints.py
* Enable repo metadata endpoint
* Fix excludes endpoint
* Fix not found on content/ urls
* Add tests
(cherry picked from commit 2857863cc7ed15b4c8fd5d3b70c98621b84bb0f5)
=> Enable repo metadata endpoint (#1228)

.github/workflows/ci_tdd.yml, dev/common/tdd.py, galaxy_ng/tests/integration/utils.py
=> It's time for TDD!!!

galaxy_ng/locale/fr/LC_MESSAGES/django.po, galaxy_ng/locale/ja/LC_MESSAGES/django.po, galaxy_ng/locale/ko/LC_MESSAGES/django.po, galaxy_ng/locale/nl/LC_MESSAGES/django.po, galaxy_ng/locale/zh/LC_MESSAGES/django.po
Localization Update from 4-19 push.  Soon to follow, the translated strings from the 4-19 push.
=> Localization stable-4.5 string update

.github/workflows/ci_tdd.yml, dev/common/tdd.py
We can't trust the forked repos to have updated master branches.
=> Use the real repo for TDD checks.

.github/pull_request_template.md
Simplified the PR template, removed the checkboxes
No-Issue
Nothing :) 
=> Simplify PR Template

CHANGES/1530.misc, docs/config/options.md, docs/config/user_access.md
Adds SESSION_COOKIE_AGE to the docs.
Issue: AAH-1530
This is a docs only change, feature was already present on Django.
=> [docs] Auto logout after set period of time

galaxy_ng/app/access_control/mixins.py
No-Issue
This is a stopgap solution until we get a release with https://github.com/pulp/pulpcore/pull/2728
=> Fix groups on namespaces and container namespaces.

galaxy_ng/app/access_control/statements/roles.py
=> Add scary comments to roles.

dev/Dockerfile.base
Fixes ./compose build
No-Issue
=> Update dev env base image to use ubi8

CHANGES/1371.misc, openshift/clowder/clowd-app.yaml
* Add and parameterize the GALAXY_SIGNATURE_UPLOAD_ENABLED setting
* Add and parameterize the GALAXY_REQUIRE_SIGNATURE_FOR_APPROVAL setting
* Add and parameterize the GALAXY_COLLECTION_SIGNING_SERVICE setting
* Add and parameterize the GALAXY_AUTO_SIGN_COLLECTIONS setting
Issue: AAH-1371
=> Add signature parameters for c.rh.c

setup.py
=> Strip package to deal with git urls

CHANGES/1700.bugfix, galaxy_ng/app/access_control/statements/insights.py, galaxy_ng/tests/integration/api/test_collection_signing.py
=> Add upload statements to insights

dev/ephemeral/jdoe_pe_group.py
This script can be called by integration tests or https://gitlab.cee.redhat.com/insights-platform/cicd-common/-/blob/master/app_scripts/ahub.sh
No-Issue
=> Add script that can add ephemeral user to partner-engineers group

galaxy_ng/app/__init__.py
Replaces https://github.com/ansible/galaxy_ng/pull/1313
=> Add python package name to AppConfig

openshift/clowder/clowd-app.yaml
The values in ephemeral environments where coming across as type string, this format matches other bool values
No-Issue
=> Update CRC signature defaults to become python boolean

galaxy_ng/tests/integration/utils.py
Move tasks weren't pollable before? Now they are? ... anyways, poll them and check state.
=> Poll the move task(s) during integration

dev/Dockerfile.base
=> Update dev Dockerfile to remove unneeded workaround

CHANGES/1449.misc, dev/common/RUN_INTEGRATION.sh, dev/common/setup_test_users.py, dev/ephemeral/smoke_test.sh, galaxy_ng/app/auth/auth.py, galaxy_ng/tests/integration/api/test_synclist.py, galaxy_ng/tests/integration/api/test_ui_paths.py, galaxy_ng/tests/integration/conftest.py, galaxy_ng/tests/integration/utils.py
* Define allowed profiles for ansible config fixture
* Update test users for ephemeral
* Temp keepalive
* Skip token auth for ephemeral
* Use new org_admin user
* Ensure user gets added to group
Issue: [AAH-1449](https://issues.redhat.com/browse/AAH-1449)
=> Add user profiles to integration tests

.github/workflows/scripts/before_install.sh, CHANGES/1202.bugfix, requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, setup.py, template_config.yml
Issue: AAH-1202
What is this PR doing:
Updating pulpcore from 3.15.5 to 3.15.8, to address an intermittent issue recorded in:
Issue: AAH-1202
=> update pulpcore to 3.15.8

.github/workflows/ci_standalone.yml, Makefile, dev/common/RUN_INTEGRATION.sh, dev/common/setup_test_data.py, dev/common/setup_test_users.py, dev/ephemeral/fixuser.py, dev/ephemeral/smoke_test.sh, galaxy_ng/tests/integration/api/test_api_base.py, galaxy_ng/tests/integration/api/test_artifact_upload.py, galaxy_ng/tests/integration/api/test_auth.py, galaxy_ng/tests/integration/api/test_collection_delete.py, galaxy_ng/tests/integration/api/test_collection_signing.py, galaxy_ng/tests/integration/api/test_landing_page.py, galaxy_ng/tests/integration/api/test_ldap.py, galaxy_ng/tests/integration/api/test_move.py, galaxy_ng/tests/integration/api/test_namespace_management.py, galaxy_ng/tests/integration/api/test_openapi.py, galaxy_ng/tests/integration/api/test_pulp_api.py, galaxy_ng/tests/integration/api/test_sync_enhancement_endpoints.py, galaxy_ng/tests/integration/api/test_synclist.py, galaxy_ng/tests/integration/api/test_ui_paths.py, galaxy_ng/tests/integration/cli/test_cli_flow.py, galaxy_ng/tests/integration/cli/test_dependencies.py, galaxy_ng/tests/integration/conftest.py
Edit integration test users to specify non-admins
No-Issue
=> Edit integration test users to specify non-admins

Makefile
Having to type "yes" after calling the make target was getting annoying.
=> Automate yes response to docker/resetdb

Makefile
Improves quality of life for QE and backporters.
=> Add normalized make target for docker/all

galaxy_ng/tests/unit/api/test_api_v3_collections.py
This commit https://github.com/pulp/pulp_ansible/commit/d4c2ecdaeb4f1ae2bc654e1728e93eda4c1e8516
renamed `get_dependents` function and that change was backported to pulp_ansible version that is installed on this branch.
this was the PR https://github.com/pulp/pulp_ansible/pull/934 - The rename of a public function was a breaking change.
The test logic has been fixed on rbac branch by this PR https://github.com/ansible/galaxy_ng/pull/1279 so the change also needs to go to stable-4.5
No-Issue
=> [bugfix] Fix CI:  Backport rename of `unique_dependents` function

CHANGES/1768.misc, docker/entrypoint.sh
Import all keys from the keyfile to the keyring.
Issue: AAH-1768
=> Import all keys from keyfile

dev/common/setup_test_data.py
Keycloak ephemeral has account numbers for each user, adding them to the test data as comments
No-Issue
=> Add ephemeral keycloak account numbers to test data

openshift/clowder/clowd-app.yaml
- Feature flag to turn of badges for collection signing
- Feature flag to set execution_environments to false to match how CRC already behaves
No-Issue
=> Set feature flags in CRC clowd-app.yaml

CHANGES/1386.bugfix, galaxy_ng/app/access_control/access_policy.py, galaxy_ng/app/access_control/statements/insights.py, galaxy_ng/app/access_control/statements/standalone.py, galaxy_ng/app/api/views.py, galaxy_ng/tests/functional/cli/test_collection_install.py, galaxy_ng/tests/functional/utils.py
=> Allow unauth access when the setting is set

.github/workflows/ci_insights.yml, dev/insights/RUN_INTEGRATION.sh, dev/insights/docker-compose.yml, dev/insights/galaxy-importer/galaxy-importer.cfg, dev/insights/proxy/Dockerfile, dev/insights/proxy/flaskapp.py, dev/insights/proxy/requirements.txt
Allows someone to spin up the docker compose insights profile and run integration tests against it, without needing to be inside an ephemeral environment, or inside an insights platform or to use the insights proxy or to be on the vpn.
=> Flask proxy insights

.github/workflows/ci_standalone-ldap.yml, dev/standalone-ldap/RUN_INTEGRATION.sh, galaxy_ng/tests/integration/api/test_ldap.py, galaxy_ng/tests/integration/conftest.py
No-Issue
Add a new job to run only tests related to LDAP on a LDAP enabled system.
=> [ci] Add a job to run LDAP tests

.github/workflows/ci_insights.yml, .github/workflows/ci_standalone-ldap.yml, .github/workflows/ci_standalone.yml
Fixing
```
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/p/python2.7/python2.7-dev_2.7.18-1~20.04.1_amd64.deb  404  Not Found [IP: 20.106.104.242 80]
```
No-Issue
=> Update github ci ubuntu packages to fix fetching error

.github/workflows/ci_insights.yml, .github/workflows/ci_standalone-community.yml, .github/workflows/ci_standalone-ldap.yml, CHANGES/1788.misc, dev/common/RUN_INTEGRATION.sh, dev/ephemeral/smoke_test.sh, dev/standalone-community/Dockerfile, dev/standalone-community/RUN_INTEGRATION.sh, dev/standalone-community/docker-compose-ui.yml, dev/standalone-community/docker-compose.yml, dev/standalone-community/galaxy-importer.cfg, dev/standalone-community/galaxy_ng.env, dev/standalone-ldap/RUN_INTEGRATION.sh, galaxy_ng/app/api/ui/serializers/synclist.py, galaxy_ng/app/auth/auth.py, galaxy_ng/tests/integration/api/test_community.py, galaxy_ng/tests/integration/api/test_ldap.py, galaxy_ng/tests/integration/conftest.py, galaxy_ng/tests/unit/app/test_app_auth.py
Add a new profile to mimic the upcoming galaxy_ng beta. This lays the foundation for adding social auth, api/v1, and related tests.
=> standalone-community compose profile

galaxy_ng/locale/ja/LC_MESSAGES/django.po, galaxy_ng/locale/ko/LC_MESSAGES/django.po, galaxy_ng/locale/zh/LC_MESSAGES/django.po
Hello,
This PR is for the recent translated strings retrieved from Memsource and the strings were uploaded to Memsource from the master branch on 5th July, 2022. 
Commit belongs to Sprint 13 (https://issues.redhat.com/browse/AAP-4770)
=> Pushing updated strings for localization

CHANGES.rst, CHANGES/1202.bugfix, CHANGES/1349.bugfix, CHANGES/1557.bugfix, CHANGES/1583.bugfix, CHANGES/1737.misc, CHANGES/1749.bugfix, CHANGES/1791.bugfix, galaxy_ng/__init__.py, galaxy_ng/app/__init__.py, setup.cfg, setup.py
PR for release 4.4.4
Please review:)
=> release 4.4.4

galaxy_ng/app/access_control/fields.py, galaxy_ng/app/access_control/statements/insights.py, galaxy_ng/app/access_control/statements/standalone.py
No-Issue
- Fixes a bug where my permissions on container namespaces showed the wrong permissions
- Allow any user to view roles
=> Make my permissions work with proxy models.

openshift/clowder/clowd-app.yaml
* Increase the default memory values for the API and content-app containers in ephemeral, and c.rh.c environements
* add health checks to the content-app container to ensure deployments in ephemeral, and c.rh.c environements are successful
No-Issue
=> Clowder: bump memory defaults and add health checks

dev/common/setup_test_data.py, docker/entrypoint.sh, galaxy_ng/app/api/ui/serializers/execution_environment.py, galaxy_ng/app/management/commands/maintain-pe-group.py, galaxy_ng/app/migrations/0029_update_synclist_model.py, galaxy_ng/app/models/synclist.py, galaxy_ng/tests/integration/api/rbac_actions/utils.py, galaxy_ng/tests/integration/api/test_groups.py, galaxy_ng/tests/integration/api/test_locked_roles.py, galaxy_ng/tests/unit/migrations/test_0029_update_synclist_model.py, requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, setup.py
Resolve post-rebase issues:
* Remove unused import left over from rebase
* Update requirements via make requirements/pip-upgrade-all
* Resolve conflicting migration numbers
* Update groups in setup data to use rbac
* Update rbac_actions utils for moving collection
No-Issue
=> Post-rebase updates

.github/workflows/ci_insights.yml, .github/workflows/ci_standalone-community.yml, .github/workflows/ci_standalone-ldap.yml, galaxy_ng/app/settings.py
=> Remove guardian from LDAP on rbac-roles branch.

CHANGES/1850.misc, galaxy_ng/tests/integration/api/test_rbac_roles.py
Adds object based tests for RBAC.
Issue: AAH-1850
=> [RBAC] Add RBAC object tests

.github/workflows/ci_standalone-rbac-roles.yml, dev/common/RUN_INTEGRATION.sh, dev/insights/RUN_INTEGRATION.sh, dev/standalone-rbac-roles/Dockerfile, dev/standalone-rbac-roles/RUN_INTEGRATION.sh, dev/standalone-rbac-roles/docker-compose-ui.yaml, dev/standalone-rbac-roles/docker-compose.yml, dev/standalone-rbac-roles/galaxy_ng.env, galaxy_ng/tests/integration/api/test_rbac_roles.py, galaxy_ng/tests/integration/conftest.py
Add a RBAC Roles CI workflow
Removes RBAC Roles tests from standalone_only workflow
Renames tag from 'role_rbac' to 'rbac_roles' and improves tag description
No-Issue
=> Add RBAC Roles CI workflow

galaxy_ng/app/migrations/0029_move_perms_to_roles.py
=> Clear out old django model permissions

galaxy_ng/tests/unit/migrations/test_0029_move_perms_to_roles.py
* Add test that can check if migration cleared Group.permissions
* Check that assigning a role does not alter Group.permissions
No-Issue
=> Check expected state and behavior of group permissions

.gitleaks.toml
Ignore the `tests` dir in gitleaks.toml
No-Issue
=> Add tests dir to gitleaks.toml allowlist

galaxy_ng/tests/integration/api/test_rbac_roles.py
RBAC Roles tests are currently standalone only.
No-Issue
=> Fix rbac test failures in ephemeral

galaxy_ng/app/api/ui/viewsets/collection.py, galaxy_ng/tests/unit/api/test_api_ui_collection_viewsets.py
=> Fix the include_related query param on the ui collections viewset.

galaxy_ng/app/management/commands/create-test-collections.py
No-Issue
Add role with permissions to the group instead of just permissions. 
=> Use role instead of permissions in `create-test-collection` command

galaxy_ng/app/api/ui/viewsets/collection.py, galaxy_ng/tests/integration/api/test_collection_signing.py
No-Issue
Connected to https://github.com/ansible/galaxy_ng/pull/1396 / AAH-1794 for fixing the annotation method call.
=> update annotation method

CHANGES/1586.misc, CHANGES/1589.misc, galaxy_ng/tests/integration/api/test_ui_paths.py, galaxy_ng/tests/integration/schemas.py
Add tests for my-namespaces endpoint, also avoiding using admin for tests where reasonable
Issue: AAH-1586
Issue: AAH-1589
=> Add tests for my-namespaces endpoint

CHANGES/1587.misc, galaxy_ng/tests/integration/api/test_artifact_download.py, galaxy_ng/tests/integration/utils.py
Added an integration test for collection-artifact-download endpoint.
Issue: AAH-1587
=> Add integration test for collection-artifact-download endpoint

galaxy_ng/tests/integration/api/test_artifact_download.py
Marked `test_artifact_download` to `standalone_only` and added a `TODO` for a long-term fix for the cause.
No-Issue
=> Fix failing integration test in ephemeral

CHANGES/1588.misc, galaxy_ng/tests/integration/api/test_remote_sync.py
Adding an integration test which tests updating and syncing a collection from the community remote.
Issue: AAH-1588
=> Add integration test for sync-config, sync

CHANGES/1443.misc, openshift/clowder/deploy-acceptance.yaml
* Adds a delay to the post-deploy-test to give Jenkins time to process the webhook
Issue: AAH-1443
=> add delay to post-deploy-test

CHANGES/1654.misc, galaxy_ng/app/access_control/statements/roles.py
Related issue: [AAH-1654](https://issues.redhat.com/browse/AAH-1654)
Remove role description and add it as a comment instead
=> Remove role descriptions

CHANGES/1932.bugfix, galaxy_ng/app/api/ui/serializers/collection.py
=> Fix 500s on the certified repository after syncing signed collections.

CHANGES.rst, CHANGES/1932.bugfix, galaxy_ng/__init__.py, galaxy_ng/app/__init__.py, setup.cfg, setup.py
No-Issue
Release 4.5.3
Please review, thank you.
=> Release 4.5.3

CHANGES/1585.misc, galaxy_ng/tests/integration/api/test_ui_paths.py, galaxy_ng/tests/integration/schemas.py, galaxy_ng/tests/integration/utils/client_ui.py
Adds integration tests for container_repo_paths endpoints, update the UI Client and add a schema used in the tests.
Issue: AAH-1585
=> Add integration tests for container_repo_paths endpoints

galaxy_ng/tests/integration/api/test_api_base.py, galaxy_ng/tests/integration/api/test_collection_delete.py, galaxy_ng/tests/integration/api/test_collection_signing.py, galaxy_ng/tests/integration/api/test_namespace_management.py, galaxy_ng/tests/integration/api/test_openapi.py, galaxy_ng/tests/integration/api/test_pulp_api.py, galaxy_ng/tests/integration/api/test_sync_enhancement_endpoints.py, galaxy_ng/tests/integration/conftest.py, galaxy_ng/tests/integration/utils/collections.py, galaxy_ng/tests/integration/utils/namespaces.py
Fixes integration tests for oci-env
=> Integration api prefix fix

CHANGES/1937.bugfix, galaxy_ng/app/api/v3/serializers/__init__.py, galaxy_ng/app/api/v3/serializers/collection.py, galaxy_ng/app/api/v3/urls.py, galaxy_ng/app/api/v3/viewsets/__init__.py, galaxy_ng/app/api/v3/viewsets/collection.py, galaxy_ng/tests/integration/api/test_collection_signing.py, galaxy_ng/tests/integration/api/test_container_signing.py
This reverts commit 14f148a699b42ba380f85af1ffea9f7c75a183bb.
No-Issue
=> Revert "Disable signatures in the v3 collection detail serializer (#1455)"

galaxy_ng/app/dynaconf_hooks.py, galaxy_ng/social/pipeline/user.py, galaxy_ng/tests/integration/api/test_community.py, galaxy_ng/tests/integration/utils/__init__.py, galaxy_ng/tests/integration/utils/users.py
=> Bypass social_core's randomized username creation when a user exists.

.github/workflows/ci_standalone-community.yml, dev/standalone-community/RUN_INTEGRATION.sh, dev/standalone-community/galaxy-importer.cfg, galaxy_ng/app/utils/rbac.py, galaxy_ng/social/__init__.py, galaxy_ng/tests/integration/api/test_community.py, galaxy_ng/tests/integration/conftest.py, galaxy_ng/tests/integration/utils/__init__.py, galaxy_ng/tests/integration/utils/client_social_github.py, galaxy_ng/tests/integration/utils/collections.py, galaxy_ng/tests/integration/utils/namespaces.py, galaxy_ng/tests/integration/utils/users.py
=> Social auth create namespace

dev/standalone-community/github_mock/flaskapp.py, galaxy_ng/app/dynaconf_hooks.py, galaxy_ng/social/pipeline/user.py, galaxy_ng/tests/integration/api/test_community.py, galaxy_ng/tests/integration/conftest.py, galaxy_ng/tests/unit/app/utils/test_galaxy.py
=> Fix v1 sync users

CHANGES/1812.feature
=> Changelog entry for v1 addition

CHANGES/1613.misc, openshift/clowder/deploy-acceptance.yaml
* adds a ServiceAccount to be deployed
* specifies the serviceAccountName in the job's pod specification
Issue: AAH-1613
Dependent on [app-interface MR 49442](https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/49442) being merged first.
=> clowder: run post-deploy-test with specific serviceaccount

CHANGES/1672.misc, CHANGES/1872.misc, openshift/clowder/run-job.yaml
* specifies a serviceAccountName in the job's pod specification
Issue: AAH-1672, AAH-1872
=> clowder: run jobs with a specific service account

CHANGES.rst, CHANGES/1812.feature, CHANGES/1950.misc, galaxy_ng/__init__.py, galaxy_ng/app/__init__.py, setup.cfg, setup.py
No-Issue
Bumping version to 4.6.1. 
Please review, thank you!
=> Release 4.6.1

galaxy_ng/app/api/v1/filtersets.py, galaxy_ng/tests/integration/api/test_community.py
Somehow the final refactor got rid of some important filters.
=> re-add missing v1 filters.

CHANGES/1995.misc, galaxy_ng/tests/integration/api/test_pulp_api.py
Remove a hard coded url from a test.
Issue: AAH-1995
=> Remove hard-coded url

CHANGES/1994.bugfix, galaxy_ng/app/migrations/0029_move_perms_to_roles.py
=> Fix broken migration

CHANGES.rst, CHANGES/1994.bugfix, galaxy_ng/__init__.py, galaxy_ng/app/__init__.py, setup.cfg, setup.py
No-Issue
Updating the changelog and bumping versions for the 4.6.2 release. 
Please review. Thank you!
=> Release-4.6.2

CHANGES/1714.feature, galaxy_ng/app/api/ui/serializers/user.py, galaxy_ng/app/constants.py, galaxy_ng/tests/unit/api/test_api_ui_user_viewsets.py
[WIP]
Issue: AAH-1714
First bit of the UI Permissions refactor. 
All relevant permissions are added to the `galaxy_ng/app/constants.py` file. 
Reviewers, please check for appropriate phrasing for each permission.
Thank you!
=> UI permissions refactor

CHANGES/1598.misc, openshift/clowder/clowd-app.yaml
Adds apiPath to the clowd-app as required by the frontend operator
Issue: AAH-1598
=> Add frontend requirements to clowd-app

MANIFEST.in, dev/common/RUN_INTEGRATION_STAGE.sh, integration_requirements.txt, integration_stage_requirements.txt
No-Issue
Use a single requirements file for both integration tests and stage integration tests
=> single req file for stage and non stage integration tests

CHANGES/1315.feature, galaxy_ng/app/api/utils.py, galaxy_ng/app/api/views.py, galaxy_ng/app/constants.py
API Issue for [AAH-1315](https://issues.redhat.com/browse/AAH-1315)
I tested this only locally, not with AAP installation.
=> Get AAP version from VERSION file

CHANGES/1956.misc, dev/ephemeral/create_keycloak_users.sh, dev/ephemeral/patch_ephemeral.sh, dev/ephemeral/smoke_test.sh, pr_check.sh
=> convert pr_check.sh to use frontend operator

CHANGES/2038.bugfix, galaxy_ng/app/migrations/0033_update_validated_repo.py, galaxy_ng/tests/integration/api/test_artifact_download.py
Fixes broken download from validated repo
Issue: AAH-2038
=> Add content_guard to validated repo's distro via migration

CHANGES/1911.misc, openshift/clowder/deploy-acceptance.yaml
Updates the deploy acceptance script
* reorganize script to allow multiple triggers
* adds trigger for 2nd Jenkins job
* sends slack notifications with the results from the Jenkins jobs
Issue: AAH-1911
=> update post-merge CI tests

CHANGES.rst, galaxy_ng/__init__.py, galaxy_ng/app/__init__.py, setup.cfg, setup.py
=> Release 4.4.5

CHANGES.rst, CHANGES/1957.bugfix, galaxy_ng/__init__.py, galaxy_ng/app/__init__.py, setup.cfg, setup.py
=> Release 4.5.4

openshift/clowder/deploy-acceptance.yaml
* fix bash syntax error
* silence curl requests
No-Issue
=> fix post-deploy-test script

galaxy_ng/locale/es/LC_MESSAGES/django.po, galaxy_ng/locale/fr/LC_MESSAGES/django.po, galaxy_ng/locale/ja/LC_MESSAGES/django.po, galaxy_ng/locale/ko/LC_MESSAGES/django.po, galaxy_ng/locale/nl/LC_MESSAGES/django.po, galaxy_ng/locale/zh/LC_MESSAGES/django.po
bringing strings from https://github.com/ansible/galaxy_ng/pull/1532 which was a stable-4.6 PR to master
git checkout upstream/stable-4.6 -- galaxy_ng/locale/
make docker/translations
(also UI: https://github.com/ansible/ansible-hub-ui/pull/2895)
=> Update localization strings

CHANGES.rst, CHANGES/1920.misc, CHANGES/1957.bugfix, CHANGES/2038.bugfix, galaxy_ng/__init__.py, galaxy_ng/app/__init__.py, setup.cfg, setup.py
=> Release 4.6.3

openshift/clowder/deploy-acceptance.yaml
Change the post-deploy-test script from using the slack chat.postMessage api to using a slack incoming webhook
Issue: AAH-1911
=> change slack notification to use incoming webhook

.ci/scripts/validate_commit_message_custom.py, .github/pull_request_template.md
This should avoid confusing first time contributors to the project(s).
No-Issue
=> Improve commit validation message

CHANGES/2018.feature, galaxy_ng/app/api/ui/viewsets/collection.py, galaxy_ng/tests/integration/api/test_ui_paths.py
Issue: AAH-2018
(cherry picked from commit 4056813)
https://github.com/ansible/galaxy_ng/pull/1571
=> Backport stable-4.5 - Add ?version_range filter (#1571)

CHANGES/1777.feature, CHANGES/2104.feature, galaxy_ng/app/api/ui/serializers/collection.py, galaxy_ng/app/api/ui/viewsets/distribution.py, galaxy_ng/app/api/v3/viewsets/collection.py, galaxy_ng/app/api/v3/viewsets/namespace.py, galaxy_ng/app/management/commands/create-test-collections.py, galaxy_ng/app/migrations/0034_remove_inbound_repos.py, galaxy_ng/app/models/namespace.py, galaxy_ng/app/tasks/promotion.py, galaxy_ng/app/tasks/publishing.py, galaxy_ng/app/tasks/signing.py, galaxy_ng/tests/functional/cli/test_collection_upload.py, galaxy_ng/tests/integration/utils/collections.py, galaxy_ng/tests/unit/api/test_api_ui_distributions.py, galaxy_ng/tests/unit/api/test_api_v3_namespace_viewsets.py, galaxy_ng/tests/unit/app/test_tasks.py, galaxy_ng/tests/unit/test_models.py
Issues: [AAH-1777](https://issues.redhat.com/browse/AAH-1777) [AAH-2104](https://issues.redhat.com/browse/AAH-2104)
=> Remove repository lock and `inbound` repository/distribution logic 

galaxy_ng/app/api/v1/filtersets.py, galaxy_ng/app/api/v1/viewsets/roles.py, galaxy_ng/tests/integration/api/test_community.py
https://issues.redhat.com/browse/AAH-2154
https://issues.redhat.com/browse/AAH-2085
=> Add legacy role filter for tag(s) & reduce default page size to 10

CHANGES/2138.misc, galaxy_ng/tests/integration/conftest.py
No-Issue 
created new usernames solely for hub testing
=> change vault usernames

Dockerfile.rhel8, dev/Dockerfile.base, setup.py
=> Update containers to python 3.9

CHANGES/2149.feature, galaxy_ng/app/access_control/statements/standalone.py, galaxy_ng/app/api/v3/viewsets/collection.py, galaxy_ng/tests/integration/api/test_collection_signing.py, galaxy_ng/tests/integration/api/test_move.py
Issue: AAH-2149
Copy the collection version and associated content to the selected repository
Currently copied content:
=> Update copy endpoint to copy collection version and associated content

requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, setup.py
replaces https://github.com/ansible/galaxy_ng/pull/1633
=> Pin dynaconf to 3.1.12 for pulpcore requirements.

CHANGES/2150.bugfix, docs/integration/ldap.md, galaxy_ng/app/dynaconf_hooks.py, galaxy_ng/tests/integration/api/test_ldap.py, galaxy_ng/tests/integration/api/test_openapi.py
backports #1636 
replaces #1645
Issue: AAH-2150
=> Backport 1636 to stable 4.6 - LDAP OPT REFERRAL

galaxy_ng/app/access_control/statements/pulp.py, galaxy_ng/tests/integration/api/test_cross_repository_search.py
depends on https://github.com/pulp/pulp_ansible/pull/1406
=> minimal cross repo search ACL

galaxy_ng/app/access_control/statements/roles.py, galaxy_ng/app/constants.py, galaxy_ng/tests/integration/api/rbac_actions/collections.py, galaxy_ng/tests/integration/api/rbac_actions/exec_env.py, galaxy_ng/tests/integration/api/rbac_actions/utils.py, galaxy_ng/tests/integration/api/test_rbac_roles.py
=> Add galaxy.collection_remote_owner role

CHANGES/2000.feature, galaxy_ng/app/access_control/access_policy.py, galaxy_ng/app/access_control/statements/insights.py, galaxy_ng/app/access_control/statements/pulp.py, galaxy_ng/app/access_control/statements/roles.py, galaxy_ng/app/access_control/statements/standalone.py, galaxy_ng/app/constants.py, galaxy_ng/tests/integration/api/rbac_actions/collections.py, galaxy_ng/tests/integration/api/rbac_actions/utils.py, galaxy_ng/tests/integration/api/test_private_repositories.py, galaxy_ng/tests/integration/api/test_rbac_roles.py, galaxy_ng/tests/integration/conftest.py
Creates custom querysets when user LIST/RETRIEVE AnsibleRepository/AnsibleDistribution api endpoints.
Users should be able to see all repositories or distributions unless the (associated) repository is marked private.
Issue: AAH-2000
=> Custom querysets for private repos

requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, setup.py, template_config.yml
=> Update galaxy_ng dependencies

CHANGES.rst, CHANGES/1958.bugfix, CHANGES/2018.feature, CHANGES/2029.misc, CHANGES/2112.feature, CHANGES/2137.misc, CHANGES/2150.bugfix, galaxy_ng/__init__.py, galaxy_ng/app/__init__.py, setup.cfg, setup.py
=> Release 4.6.4

galaxy_ng/__init__.py, galaxy_ng/app/__init__.py, setup.cfg, setup.py
=> Set version to 4.7.0b1

CHANGES/2279.misc, galaxy_ng/app/access_control/access_policy.py, galaxy_ng/app/access_control/statements/pulp.py, galaxy_ng/tests/integration/api/test_collection_delete.py
=> Prevent deletion of default distributions and repositories

CHANGES/2213.misc, openshift/clowder/clowd-app.yaml
* set PULP_CONTENT_PATH_PREFIX to /api/automation-hub/pulp/content/
* dependant on nginx envvars via https://github.com/ansible/galaxy_ng/pull/1660
Issue: AAH-2213
=> proxy content app for CRC

CHANGES.rst, galaxy_ng/__init__.py, galaxy_ng/app/__init__.py, setup.cfg, setup.py
=> Release 4.6.5

dev/ephemeral/patch_ephemeral.sh
updates the patch_ephemeral.sh script to set CONTENT_ORIGIN properly based on changes in crc-bonfire 4.13
No-Issue
=> set proper CONTENT_ORIGIN for ephemeral

docs/community/api_v3.md, docs/community/userguide.md, mkdocs.yml
No-Issue
Related to AAH-2131
Check the  link from netlify [preview](https://deploy-preview-1693--galaxyng.netlify.app/community/api_v3/)
=> Add v3 API reference to community user guide

docs/config/container_signing.md
Fixed script on galaxy docs according to pulp docs, pulp docs got some update on script, reflecting on the docs here.
- The variable `PULP_CONTAINER_SIGNING_KEY_FINGERPRINT` is not needed, the right variable name is `PULP_SIGNING_KEY_FINGERPRINT`
No-Issue
Related: https://issues.redhat.com/browse/AAP-10305
replaces #1437 
Co-authored-by: Mike DePaulo  @mikedep333
=> Fix signing script example for container

CHANGES/2327.bugfix, galaxy_ng/app/access_control/statements/pulp_container.py, galaxy_ng/tests/integration/api/test_container_push_update.py
=> Backport Fix permission set for updating a container push repo #1698 to stable 4.6

CHANGES/2151.misc, docker/etc/settings.py
=> Turn on collection download log in image used for CRC deploys

CHANGES/2341.misc, dev/ephemeral/smoke_test.sh, dev/standalone/RUN_INTEGRATION.sh, galaxy_ng/tests/integration/api/rbac_actions/collections.py, galaxy_ng/tests/integration/api/rbac_actions/utils.py, galaxy_ng/tests/integration/api/test_artifact_download.py, galaxy_ng/tests/integration/api/test_artifact_upload.py, galaxy_ng/tests/integration/api/test_container_delete.py, galaxy_ng/tests/integration/api/test_container_push_update.py, galaxy_ng/tests/integration/api/test_iqe_rbac.py, galaxy_ng/tests/integration/api/test_move.py, galaxy_ng/tests/integration/api/test_private_repositories.py, galaxy_ng/tests/integration/api/test_rbac_on_repos.py, galaxy_ng/tests/integration/api/test_rbac_roles.py, galaxy_ng/tests/integration/api/test_repositories.py, galaxy_ng/tests/integration/api/test_repository_labels.py, galaxy_ng/tests/integration/api/test_sync_stage.py, galaxy_ng/tests/integration/api/test_ui_paths.py, galaxy_ng/tests/integration/api/test_upload_to_custom_repos.py, galaxy_ng/tests/integration/api/test_v3_plugin_paths.py, galaxy_ng/tests/integration/conftest.py, galaxy_ng/tests/integration/schemas.py, galaxy_ng/tests/integration/utils/client_ui.py, galaxy_ng/tests/integration/utils/iqe_utils.py, galaxy_ng/tests/integration/utils/rbac_utils.py, galaxy_ng/tests/integration/utils/repo_management_utils.py, integration_requirements.txt
Integration tests have been adapted so that Jenkins AAP integration pipelines can run them
Issue: AAH-2341
=> Lets use galaxy ng tests everywhere

galaxy_ng/tests/integration/conftest.py
=> fix admin token issue

galaxy_ng/tests/integration/api/rbac_actions/utils.py, galaxy_ng/tests/integration/api/test_artifact_upload.py, galaxy_ng/tests/integration/api/test_collection_delete.py, galaxy_ng/tests/integration/api/test_collection_signing.py, galaxy_ng/tests/integration/api/test_container_delete.py, galaxy_ng/tests/integration/api/test_container_signing.py, galaxy_ng/tests/integration/api/test_cross_repository_search.py, galaxy_ng/tests/integration/api/test_iqe_rbac.py, galaxy_ng/tests/integration/api/test_move.py, galaxy_ng/tests/integration/api/test_openapi.py, galaxy_ng/tests/integration/api/test_private_repositories.py, galaxy_ng/tests/integration/api/test_pulp_api.py, galaxy_ng/tests/integration/api/test_remote_sync.py, galaxy_ng/tests/integration/api/test_repository_labels.py, galaxy_ng/tests/integration/api/test_tasks.py, galaxy_ng/tests/integration/api/test_ui_paths.py, galaxy_ng/tests/integration/api/test_upload_concurrency.py, galaxy_ng/tests/integration/api/test_upload_to_custom_repos.py, galaxy_ng/tests/integration/api/test_v3_plugin_paths.py, galaxy_ng/tests/integration/cli/test_cli_flow.py, galaxy_ng/tests/integration/cli/test_dependencies.py, galaxy_ng/tests/integration/conftest.py, galaxy_ng/tests/integration/schemas.py
=> update tests to make them compatible against hub 4.6

galaxy_ng/tests/integration/api/test_container_delete.py, galaxy_ng/tests/integration/api/test_container_push_update.py, galaxy_ng/tests/integration/api/test_container_signing.py
=> fix url and skip tests

docs/dev/getting_started.md
=> fix docs typo

galaxy_ng/tests/integration/api/rbac_actions/utils.py, galaxy_ng/tests/integration/api/test_container_delete.py, galaxy_ng/tests/integration/api/test_container_push_update.py, galaxy_ng/tests/integration/api/test_container_signing.py, galaxy_ng/tests/integration/api/test_iqe_rbac.py, galaxy_ng/tests/integration/api/test_move.py, galaxy_ng/tests/integration/utils/iqe_utils.py, galaxy_ng/tests/integration/utils/rbac_utils.py
this is to avoid the docker pull limit that happens in pipelines
=> Galaxy ng pipelines

CHANGES.rst, CHANGES/2327.bugfix, galaxy_ng/__init__.py, galaxy_ng/app/__init__.py, setup.cfg, setup.py
=> Release 4.7.1

galaxy_ng/tests/integration/api/test_openapi.py, galaxy_ng/tests/integration/utils/iqe_utils.py
=> Handle unexpected docker errors

galaxy_ng/tests/integration/api/test_iqe_rbac.py, galaxy_ng/tests/integration/utils/iqe_utils.py, galaxy_ng/tests/integration/utils/rbac_utils.py
fix the push retry mechanism
in certain envs the docker push fails (blob unknown to registry, invalid manifest) we need to run docker system prune and retry
=> Podman docker retry

CHANGES/2383.bugfix, galaxy_ng/app/api/v1/filtersets.py, galaxy_ng/tests/integration/cli/test_community_import_install.py
=> Make legacy role owner__username filter check against namespace name

CHANGES/2385.bugfix, galaxy_ng/app/migrations/0040_fix_collection_remote_pulp_type.py, galaxy_ng/tests/unit/api/test_collectionremotes.py
=> Fix the pulp_type for the default CollectionRemotes.

galaxy_ng/tests/integration/api/rbac_actions/collections.py, galaxy_ng/tests/integration/api/test_rbac_roles.py
Issue: [AAH-2074](https://issues.redhat.com/browse/AAH-2074)
Requires https://github.com/pulp/pulp_ansible/pull/1311
=> Enable `rebuild_metadata_ansible_repository_version` rbac test

.github/workflows/ci_insights.yml, dev/insights/galaxy_ng.env, galaxy_ng/tests/integration/api/test_artifact_upload.py, galaxy_ng/tests/integration/api/test_collection_delete.py, galaxy_ng/tests/integration/api/test_collection_signing.py, galaxy_ng/tests/integration/api/test_cross_repository_search.py, galaxy_ng/tests/integration/api/test_synclist.py, galaxy_ng/tests/integration/cli/test_cli_flow.py, galaxy_ng/tests/integration/conftest.py, galaxy_ng/tests/integration/utils/__init__.py, galaxy_ng/tests/integration/utils/collections.py, galaxy_ng/tests/integration/utils/signatures.py
https://issues.redhat.com/browse/AAH-2384
=> Add config setting for insights that requires signature on approval.

galaxy_ng/tests/integration/api/test_collection_signing.py, galaxy_ng/tests/integration/api/test_repositories.py
* Clean up repos and distros for repo tests running in crc
* Explicitly skip signing service tests in crc
No-Issue
=> Integration test updates for CRC

.github/workflows/i18n.yml
No-Issue
- open pull requests against branches in matrix.branch
- fix to pass the `check_commit` ci
- add committer and author
(Hopefully last fix for the automated translations :D)
=> Fix automated translation to open PRs against all branches 

CHANGES/2415.misc, galaxy_ng/app/api/v1/viewsets/roles.py
Issue: [AAH-2415](https://issues.redhat.com/browse/AAH-2415)
=> Role download count fail gracefully if read-only database

galaxy_ng/tests/integration/cli/test_cli_flow.py
=> Ensure test is skipped in insights mode

CHANGES/2442.misc, galaxy_ng/tests/integration/cli/test_cli_flow.py
=> Remove forced skip of test_publish_and_expect_uncertified_hidden

requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt
https://github.com/pulp/pulpcore/issues/4042
=> Update pulpcore to handle otel dependency issues.

Dockerfile.rhel8, dev/Dockerfile.base, docker/entrypoint.sh, profiles/base/compose.yaml
https://issues.redhat.com/browse/AAP-13370
oci argument related to https://github.com/pulp/oci_env/pull/127
=> [WIP] Move to python 3.11

.github/workflows/ci_automation_hub_collection.yml, CHANGES/2419.misc, dev/ah_collection_plays/content.yml, dev/ah_collection_plays/ee.yml, dev/ah_collection_plays/repo.yml, dev/ah_collection_plays/user.yml, dev/ah_collection_plays/vars.yml
=> add new CI workflow to test against the automation hub collection

docker/bin/start-api
* increases the max header size
No-Issue
=> increase max header size

docker/bin/start-api
* increases the max header size
No-Issue
=> increase max header size (#1813)

.github/workflows/ci_automation_hub_collection.yml
=> remove ah collection ansible.cfg in CI

galaxy_ng/tests/integration/api/test_ui_paths.py
https://github.com/ansible/galaxy_ng/pull/1820#issuecomment-1659046788
=> Undo skip marker now that httpdownloader+async is fixed in pulpcore.

CHANGES/2631.bugfix, galaxy_ng/app/access_control/statements/pulp.py, galaxy_ng/tests/integration/api/test_tasks.py, galaxy_ng/tests/integration/utils/__init__.py
=> Allow admins to be able to cancel tasks.

CHANGES/2078.misc, openshift/clowder/deploy-acceptance.yaml
* updates the post-deploy-test script to allow running [stage_sync_tests](https://main-jenkins-csb-aap.apps.ocp-c1.prod.psi.redhat.com/job/AAPQA/job/Automation_Hub/job/Stage_Sync_Tests/) 
Issue: AAH-2078
=> update post-deploy-test to run stage_sync_tests

galaxy_ng/tests/integration/utils/__init__.py, galaxy_ng/tests/integration/utils/github.py, profiles/community/github_mock/flaskapp.py
separated out of https://github.com/ansible/galaxy_ng/pull/1853 to make smaller PRs
=> Enhance the github shim for future v1 to v3 rbac changes.

profiles/insights/proxy/main.go
The insights profile tests fail randomly because of broken pipe errors when connecting to galaxy_ng.
=> Insights proxy broken pipe retry

galaxy_ng/tests/integration/api/test_artifact_upload.py
=> skip lint exception check on 4.7

docker/bin/start-api
Increases the gunicorn timeout to 60 seconds
No-Issue
=> inrease gunicorn timeout

galaxy_ng/locale/es/LC_MESSAGES/django.po, galaxy_ng/locale/fr/LC_MESSAGES/django.po, galaxy_ng/locale/ja/LC_MESSAGES/django.po, galaxy_ng/locale/ko/LC_MESSAGES/django.po, galaxy_ng/locale/nl/LC_MESSAGES/django.po, galaxy_ng/locale/zh/LC_MESSAGES/django.po
=> [stable-4.8] [i18n] Update latest translation files 

galaxy_ng/locale/es/LC_MESSAGES/django.po, galaxy_ng/locale/fr/LC_MESSAGES/django.po, galaxy_ng/locale/ja/LC_MESSAGES/django.po, galaxy_ng/locale/ko/LC_MESSAGES/django.po, galaxy_ng/locale/nl/LC_MESSAGES/django.po, galaxy_ng/locale/zh/LC_MESSAGES/django.po
=> [i18n] Update latest translation files

CHANGES.rst, CHANGES/2078.misc, CHANGES/2125.misc, CHANGES/2151.misc, CHANGES/2213.misc, CHANGES/2238.feature, CHANGES/2265.feature, CHANGES/2327.bugfix, CHANGES/2328.feature, CHANGES/2341.misc, CHANGES/2343.misc, CHANGES/2362.misc, CHANGES/2364.bugfix, CHANGES/2382.feature, CHANGES/2383.bugfix, CHANGES/2385.bugfix, CHANGES/2388.bugfix, CHANGES/2393.misc, CHANGES/2409.misc, CHANGES/2415.misc, CHANGES/2419.misc, CHANGES/2442.misc, CHANGES/2575.bugfix, CHANGES/2615.misc, CHANGES/2631.bugfix, CHANGES/2654.misc, galaxy_ng/__init__.py, galaxy_ng/app/__init__.py, setup.cfg, setup.py
=> Release 4.8.0

.github/labeler.yml, galaxy_ng/__init__.py, galaxy_ng/app/__init__.py, setup.cfg, setup.py
=> Bump master to 4.9.0dev

CHANGES.rst, galaxy_ng/__init__.py, galaxy_ng/app/__init__.py, setup.cfg, setup.py
=> Release 4.7.2

CHANGES/2648.bugfix, profiles/base/compose.yaml
=> [oci-env] Add pulp_certs volume

galaxy_ng/tests/integration/api/test_artifact_download.py, galaxy_ng/tests/integration/api/test_artifact_upload.py, galaxy_ng/tests/integration/api/test_collection_signing.py, galaxy_ng/tests/integration/api/test_move.py, galaxy_ng/tests/integration/api/test_sync_stage.py, galaxy_ng/tests/integration/api/test_synclist.py, galaxy_ng/tests/integration/cli/test_dependencies.py, galaxy_ng/tests/integration/conftest.py, galaxy_ng/tests/integration/utils/collections.py, galaxy_ng/tests/integration/utils/iqe_utils.py
=> fix and improve sync tests

galaxy_ng/tests/integration/api/test_sync_stage.py, galaxy_ng/tests/integration/conftest.py, galaxy_ng/tests/integration/utils/iqe_utils.py
=> make sync test work with older version (credentials were changed)

dev/galaxy_ansible/RUN_INTEGRATION_GALAXY_STAGE_ANSIBLE.sh, galaxy_ng/tests/integration/api/test_galaxy_stage_ansible.py, galaxy_ng/tests/integration/conftest.py, galaxy_ng/tests/integration/constants.py, galaxy_ng/tests/integration/utils/iqe_utils.py
=> from beta galaxy to galaxy stage ansible

galaxy_ng/app/api/v1/models.py, galaxy_ng/app/management/commands/copy-owner-permissions.py, galaxy_ng/app/management/commands/download-namespace-logos.py, galaxy_ng/app/management/commands/sync-galaxy-collections.py, galaxy_ng/app/management/commands/sync-galaxy-namespaces.py, galaxy_ng/app/management/commands/sync-galaxy-roles.py, galaxy_ng/app/utils/galaxy.py, galaxy_ng/app/utils/legacy.py, galaxy_ng/tests/unit/app/management/commands/test_community_commands.py
A bunch of stuff to ease maintenance and support local development ...
copy-owner-permissions.py -- grant ownership to a user based on another user's namespace ownerships
sync-galaxy-namespacess.py -- sync all or some namespaces from old-galaxy
sync-galaxy-collections.py -- sync all or some collections from old-galaxy
sync-galaxy-roles.py -- sync all or some roles from old-galaxy
changes:
download-namespace-logos.py -- add *optional* argument for which namespace to download
sync-collection-download-counts.py -- set the default url to old-galaxy
=> more community management commands

galaxy_ng/tests/integration/api/rbac_actions/utils.py, galaxy_ng/tests/integration/api/test_artifact_upload.py, galaxy_ng/tests/integration/utils/collections.py
=> update tests to fix failing pipelines

CHANGES/2760.misc, galaxy_ng/app/api/v1/filtersets.py, galaxy_ng/app/api/v1/viewsets/roles.py, galaxy_ng/tests/integration/api/test_community.py
=> Add `download_count` ordering to legacy roles endpoint

galaxy_ng/tests/integration/api/test_galaxy_stage_ansible.py
=> skip test_social_auth_creates_group

galaxy_ng/tests/integration/api/test_namespace_management.py
=> skip namespace tests if version is lower than 4.9

galaxy_ng/tests/integration/api/test_artifact_upload.py
make lint test homogeneous for all versions
No-Issue
=> make lint test homogeneous for all versions

CHANGES/2782.feature, galaxy_ng/app/api/v1/filtersets.py, galaxy_ng/tests/integration/api/test_community.py
Issue: [AAH-2782](https://issues.redhat.com/browse/AAH-2782)
=> `username_autocomplete` filter in legacy roles endpoint 

CHANGES.rst, galaxy_ng/__init__.py, galaxy_ng/app/__init__.py, setup.cfg, setup.py
=> Release 4.8.1

.ci/aap_upgrade.groovy, galaxy_ng/tests/integration/api/test_artifact_download.py, galaxy_ng/tests/integration/conftest.py
jenkins job to be run on every PR that installs AAP 2.3, upgrades to AAP2.4 and upgrades again to AAP devel branch taking hub from source (fork/branch from PR) and runs a single smoke test
=> CI job AAP upgrade

galaxy_ng/tests/integration/api/test_galaxy_stage_ansible.py, galaxy_ng/tests/integration/conftest.py, galaxy_ng/tests/integration/utils/collections.py, galaxy_ng/tests/integration/utils/legacy.py, galaxy_ng/tests/integration/utils/namespaces.py, galaxy_ng/tests/integration/utils/tools.py, galaxy_ng/tests/integration/utils/users.py
lately, a bunch of tests have been added to community tests. With this PR, some of them have been adapted moved to the file that the galaxy stage pipeline runs.
Additionally, some methods have been duplicated so that they use galaxykit tools, this parts is still work in progress.
=> add tests for galaxy stage

requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, setup.py
=> Bump galaxy-importer to `0.4.16`

galaxy_ng/app/api/v1/serializers.py, galaxy_ng/tests/integration/community/test_v1_namespaces.py
https://issues.redhat.com/browse/AAH-2829
=> Use provider namespace avatar url if possible.

galaxy_ng/tests/integration/utils/iqe_utils.py
ephemeral URL changed in pr check ci job
No-Issue
=> fix pr check job

CHANGES/2296.bugfix, galaxy_ng/app/api/v3/serializers/namespace.py, galaxy_ng/app/models/namespace.py, galaxy_ng/app/tasks/namespaces.py, galaxy_ng/tests/integration/api/test_namespace_management.py
Issue: AAH-2296
Fixes the propagation of the logo from namespace to collection: https://forum.ansible.com/t/collection-update-image/1357
=> Fix updating my_namespace avatar multiple times

galaxy_ng/locale/es/LC_MESSAGES/django.po, galaxy_ng/locale/fr/LC_MESSAGES/django.po, galaxy_ng/locale/ja/LC_MESSAGES/django.po, galaxy_ng/locale/ko/LC_MESSAGES/django.po, galaxy_ng/locale/nl/LC_MESSAGES/django.po, galaxy_ng/locale/zh/LC_MESSAGES/django.po
=> [i18n] Update latest translations

MANIFEST.in, galaxy_ng/tests/integration/api/test_load_data.py, galaxy_ng/tests/integration/api/test_verify_data.py, galaxy_ng/tests/integration/conftest.py, galaxy_ng/tests/integration/load_data.yaml, galaxy_ng/tests/integration/utils/iqe_utils.py, integration_requirements.txt
this is the implementation of the load data stage and the verify data stage for all the jenkins pipelines. We need these to verify the integrity of the data after AAP upgrades or restores
=> Load data and verify

.github/labeler.yml, .github/workflows/i18n.yml, galaxy_ng/__init__.py, galaxy_ng/app/__init__.py, setup.cfg, setup.py
=> Bump master to 4.10.0dev

galaxy_ng/tests/integration/api/test_namespace_management.py
=> skip ns test for versions < 4.9

galaxy_ng/tests/integration/api/test_verify_data.py, galaxy_ng/tests/integration/utils/iqe_utils.py
=> skip verify data stage if upgrade from aap22 hub45

dev/oci_env_integration/oci_env_configs/standalone.compose.env, galaxy_ng/tests/integration/api/test_iqe_ldap.py, galaxy_ng/tests/integration/conftest.py
=> import ldap tests from iqe plugin

galaxy_ng/tests/integration/api/test_iqe_ldap.py, galaxy_ng/tests/integration/conftest.py, profiles/ldap/pulp_config.env
=> deployment_standalone

profiles/base/Dockerfile, profiles/base/compose.yaml
https://issues.redhat.com/browse/AAH-3042
related https://github.com/pulp/oci_env/pull/139
=> Fixup PYTHON_VERSION usage and prep for new images.

docs/usage_guide/installation.md
https://issues.redhat.com/browse/AAP-18292
pulp-installer is no longer supported.
=> Change install instructions to use OCI

requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, setup.py
https://issues.redhat.com/browse/AAH-2854
https://issues.redhat.com/browse/AAH-2855
=> Bump galaxy-importer to 0.4.19

.github/workflows/changelog.yml, .github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .github/workflows/update-labels.yml, .github/workflows/update_ci.yml, profiles/dab/README.md, profiles/dab/profile_requirements.txt, profiles/dab/pulp_config.env, requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, setup.py, template_config.yml
=> Add django ansible base

CHANGES.rst, CHANGES/2588.bugfix, galaxy_ng/__init__.py, galaxy_ng/app/__init__.py, galaxy_ng/tests/integration/api/test_namespace_management.py, galaxy_ng/tests/integration/utils/tasks.py, setup.cfg, setup.py, unittest_requirements.txt
=> Release 4.9.1

requirements/requirements.insights.in, requirements/requirements.insights.txt
No-Issue
When deploying with Azure Blob storage backend, it fails with this error in the API logs.  
```
ModuleNotFoundError: No module named 'azure'
```
=> Add azure-storage-blob dep for azure blob content storage support

requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt
https://issues.redhat.com/browse/AAH-3001
https://issues.redhat.com/browse/AAH-3023
https://issues.redhat.com/browse/AAH-3075
=> Bump pulpcore and aiohttp.

CHANGES/3121.bugfix, galaxy_ng/app/access_control/mixins.py, galaxy_ng/tests/integration/api/test_ui_namespace_owners.py
https://issues.redhat.com/browse/AAH-3121
=> Do not include group members when fetching the list of users for a namespace

galaxy_ng/tests/integration/api/test_auth.py, galaxy_ng/tests/integration/utils/iqe_utils.py, integration_requirements.txt, profiles/base/run_integration.sh
=> add test to cover scenario AAP-21532

galaxy_ng/app/migrations/0051_rename_created_modified.py
=> Fix rename of fields in models inherited from DAB

galaxy_ng/tests/integration/api/test_sync_stage.py
=> fix sync tests

.github/workflows/ci_automation_hub_collection.yml, Makefile, dev/galaxy_collection_plays/content.yml, dev/galaxy_collection_plays/vars.yml, dev/oci_poll, dev/oci_start
collectstatic is broken in the old dev stack (thereby breaking the collection test), so this is an immediate need.
=> Switch collection testing over to oci-env.

galaxy_ng/app/dynaconf_hooks.py, galaxy_ng/app/settings.py, galaxy_ng/app/urls.py, galaxy_ng/tests/integration/api/test_dab.py, profiles/dab/pulp_config.env
copy of https://github.com/ansible/galaxy_ng/pull/2106  + a test
=> Disable DAB resource registry

galaxy_ng/app/settings.py, galaxy_ng/tests/integration/api/test_hubjwt.py
adds the HubJWTAuth authentication class
No-Issue
=> add HubJWTAuth authentication class

galaxy_ng/app/dynaconf_hooks.py
Improves check if galaxy_ng is behind the resource_provider
No-Issue
=> Fix resource_provider dynaconf hook

galaxy_ng/app/dynaconf_hooks.py
AAP-20998
AAP-20299
AAP-20589
No-Issue
=> Fix download url behind resource_provider

CHANGES.rst, CHANGES/2836.bugfix, CHANGES/3121.bugfix, galaxy_ng/__init__.py, galaxy_ng/app/__init__.py, setup.cfg, setup.py
=> Release 4.9.2

galaxy_ng/tests/integration/api/test_auth.py, galaxy_ng/tests/integration/api/test_dab.py
=> skip tests in gateway deployment

profiles/dab/pulp_config.env
=> Fix download redirects through resource_provider

galaxy_ng/tests/integration/api/test_auth.py, galaxy_ng/tests/integration/api/test_dab.py, galaxy_ng/tests/integration/api/test_ui_namespace_owners.py, galaxy_ng/tests/integration/cli/test_cli_flow.py
=> fix gw pipelines

profiles/dab_jwt/proxy/Dockerfile
Air comes from a different place now?
=> Fix the air install for the jwt proxy.

dev/playbooks/start_container.yaml, galaxy_ng/app/dynaconf_hooks.py, galaxy_ng/app/settings.py
=> fix: attempt to fix jwt app_label error

galaxy_ng/tests/integration/api/test_x_repo_search.py, galaxy_ng/tests/integration/conftest.py
=> avoid group creation directly in the hub

galaxy_ng/tests/integration/api/test_ui_paths_gateway.py
=> update tests - groups can't be created in hub now

integration_requirements.txt
pin requests library in integration tests to avoid docker bug
https://github.com/docker/docker-py/issues/3256
=> pin requests library in integration tests to avoid docker bug

galaxy_ng/tests/integration/utils/iqe_utils.py
=> HUB_API_ROOT needs to be localhost in sync tests

galaxy_ng/tests/integration/api/test_auth.py
=> csrftoken test should POST instead of GET

galaxy_ng/tests/integration/api/test_artifact_upload.py
change basic_user to admin so that they can publish
=> admin users in test_artifact_upload.py

galaxy_ng/tests/integration/api/test_auth.py, galaxy_ng/tests/integration/conftest.py
=> fix csrftoken

.github/workflows/ci_oci-env-integration.yml
https://issues.redhat.com/browse/AAH-3335
=> Always install a valid docker-compose binary in CI.

profiles/base/Dockerfile, requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, setup.py
No-Issue
Bumping DAB to include changes from https://github.com/ansible/django-ansible-base/releases/tag/2024.8.1
=> Bump DAB to `v2024.8.1`

galaxy_ng/app/models/auth.py
split out from https://github.com/ansible/galaxy_ng/pull/2202 per request
=> Add resource to the User model.

galaxy_ng/app/signals/handlers.py, galaxy_ng/tests/integration/dab/test_dab_rbac.py
https://issues.redhat.com/browse/AAH-3357
=> Map galaxy.auditor to "Platform Auditor".

galaxy_ng/app/api/ui_v2/views.py, galaxy_ng/app/settings.py, galaxy_ng/tests/integration/dab/test_dab_rbac_pagination.py
https://issues.redhat.com/browse/AAP-29285
=> Make some ui/v2 base view classes for DRY and to drive dab.rbac pagination

MANIFEST.in, sonar-project.properties
=> Add SonarCloud configuration

.github/workflows/ci_oci-env-integration.yml, Makefile, dev/oci_env_integration/actions/rbac-parallel.py, galaxy_ng/tests/integration/api/test_rbac_roles.py, galaxy_ng/tests/integration/conftest.py
=> Try to parallelize rbac roles tests

galaxy_ng/tests/integration/dab/test_dab_rbac.py, galaxy_ng/tests/integration/dab/test_dab_rbac_contract.py
No-Issue
Run these tests in >=2.5 AAP(4.10 Hub) installers
=> Mark more 2.5 tests

.github/labeler.yml, .github/workflows/i18n.yml, CHANGES.md, CHANGES/.TEMPLATE.md, CHANGES/18825.misc, CHANGES/2420.doc, CHANGES/2822.misc, CHANGES/2836.bugfix, CHANGES/3036.misc, CHANGES/3064.misc, CHANGES/3121.bugfix, CHANGES/3190.bugfix, CHANGES/3358.misc, galaxy_ng/__init__.py, galaxy_ng/app/__init__.py, setup.cfg, setup.py
This is our last build/cleanup of CHANGES.md
We will soon disable the changelog generation using towncrier.
=> Bump master to 4.11.0dev + CHANGES cleanup

galaxy_ng/tests/integration/conftest.py
https://issues.redhat.com/browse/AAP-33988
=> recreate gateway users during test setup as needed.

dev/compose/README.md, dev/compose/community.yaml
Add dev/compose/community.yaml
=> dev: add community compose

dev/compose/insights.yaml
```
docker compose -f dev/compose/insights.yaml up
```
=> Insights profile

galaxy_ng/tests/integration/api/test_load_data.py, galaxy_ng/tests/integration/api/test_verify_data.py, galaxy_ng/tests/integration/load_data.yaml
Issue: [AAP-33822](https://issues.redhat.com/browse/AAP-33822)
Tested in::
- containerized minor upgrade - [productBuildContainerizedMinorUpgradePipeline](https://main-jenkins-csb-aap.apps.ocp-c1.prod.psi.redhat.com/job/AAPQA/job/Sandbox/job/christian/job/00_hubdebug/46/)
=> Update `TestLoadData` and `TestVerifyData` to work with 2.5 GW

galaxy_ng/app/tasks/namespaces.py, requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt
fixes async issues
https://github.com/pulp/pulpcore/issues/5790
https://github.com/pulp/pulpcore/commit/386c0b99f2baa9f871c9d0a0be44c2be53581746
=> Bump to pulpcore 3.49.24

.tekton/automation-hub-galaxy-ng-master-pull-request.yaml, .tekton/automation-hub-galaxy-ng-master-push.yaml
adds rpms-signature-scan to konflux pipelines
=> konflux: add rpms-signature-scan

docs/community/userguide.md
Adding details for how to delete role namespaces and then delete the parent namespace.
No-Issue
=> Docs: add details for deleting a namespace

.github/workflows/ci-docker-compose-integration.yml, .github/workflows/ci_oci-env-integration.yml, galaxy_ng/tests/integration/api/test_collection_signing.py
https://issues.redhat.com/browse/AAP-38042
=> Add timeouts for integration tests.

galaxy_ng/tests/unit/api/test_api_ui_distributions.py
https://issues.redhat.com/browse/AAP-38033
=> fix list distributions unit test

galaxy_ng/tests/unit/api/test_view_only_access.py
https://issues.redhat.com/browse/AAP-38035
https://issues.redhat.com/browse/AAP-38036
=> Fix more unit tests by direct mocking of settings.

README.md, docs/dev/docker_environment.md, docs/dev/getting_started.md, docs/index.md, mkdocs.yml
- remove reference to the vagrant env
- fix the link for the docker compose
- update CI badges
=> Fix docs broken links

.bumpversion.cfg, CHANGES.md, galaxy_ng/__init__.py, galaxy_ng/app/__init__.py, galaxy_ng/locale/es/LC_MESSAGES/django.po, galaxy_ng/locale/fr/LC_MESSAGES/django.po, galaxy_ng/locale/ja/LC_MESSAGES/django.po, galaxy_ng/locale/ko/LC_MESSAGES/django.po, galaxy_ng/locale/nl/LC_MESSAGES/django.po, galaxy_ng/locale/zh/LC_MESSAGES/django.po, setup.cfg, setup.py
=> Release 4.10.2

README.md, dev/compose/README.md, docs/config/options.md, docs/dev/getting_started.md, docs/dev/integration_tests.md, docs/dev/tests/integration.md, docs/dev/tests/unit.md, docs/index.md, docs/tags.md, docs/usage_guide/installation.md, galaxy_ng/tests/integration/README.md, galaxy_ng/tests/unit/README.md, mkdocs.yml
- update broken links
- remove references to the old galaxy.com
- remove empty md files
=> Address mkdocs warnings

dev/compose/aap.yaml, dev/compose/certified-sync.yaml, dev/compose/community.yaml, dev/compose/insights.yaml, dev/compose/standalone.yaml
https://docs.docker.com/engine/storage/bind-mounts/#options-for---volume
No-Issue
=> Configure SELinux on compose env

dev/compose/keycloak.yaml, dev/compose/ldap.yaml, dev/compose/standalone.yaml
https://docs.docker.com/engine/storage/bind-mounts/#options-for---volume
No-Issue
(cherry picked from commit 6bee156363953fb68b86740a0eee2a1d1e8d8f5d)
=> [backport-4.9] Configure SELinux on compose env (#2428)

README.md, docs/index.md, sonar-project.properties
Temporarily disable coverage on legacy/auxiliary code
=> Update sonar properties

README.md
=> Galaxy has a logo

.github/workflows/ci-docker-compose-integration.yml, .github/workflows/ci_automation_hub_collection.yml
Gather logs for helping to debug failures
=> Adding CI logs

.gitignore, dev/compose/Dockerfile.dev, dev/compose/aap.yaml, dev/compose/certified-sync.yaml, dev/compose/community.yaml, dev/compose/insights.yaml, dev/compose/standalone.yaml
Some oci-env docs mentioned pulp CLI commands,
so we are adding it for not breaking it for people that used to it
Issue: AAP-32608
=> Add pulp-cli to the dev env

dev/ephemeral/patch_ephemeral.sh
fixes the rollout to devshift ephemeral environment in the PR check by patching the correct resources in the clowdapp
No-Issue
=> deployment fixes for devshift PR check

.github/workflows/ci_full.yml, galaxy_ng/tests/unit/README.md, galaxy_ng/tests/unit/api/base.py, galaxy_ng/tests/unit/api/rh_auth.py, galaxy_ng/tests/unit/api/test_api_ui_auth_views.py, galaxy_ng/tests/unit/api/test_api_ui_container_remote.py, galaxy_ng/tests/unit/api/test_api_ui_distributions.py, galaxy_ng/tests/unit/api/test_api_ui_synclists.py, galaxy_ng/tests/unit/api/test_api_ui_user_viewsets.py, galaxy_ng/tests/unit/api/test_api_v3_collections.py, galaxy_ng/tests/unit/api/test_localization.py, galaxy_ng/tests/unit/api/test_view_only_access.py, galaxy_ng/tests/unit/app/api/v1/test_tasks.py, galaxy_ng/tests/unit/app/management/commands/analytics/automation_analytics/test_collector.py, galaxy_ng/tests/unit/app/management/commands/analytics/automation_analytics/test_data.py, galaxy_ng/tests/unit/app/management/commands/test_dump_auth_config.py, galaxy_ng/tests/unit/app/management/commands/test_metrics_collection_lightspeed.py, galaxy_ng/tests/unit/app/management/commands/test_populate_role_tags_commands.py, galaxy_ng/tests/unit/app/test_dynaconf_hooks.py, galaxy_ng/tests/unit/app/test_role_permissions_in_constants.py, galaxy_ng/tests/unit/app/utils/test_galaxy.py, galaxy_ng/tests/unit/migrations/test_0029_move_perms_to_roles.py, galaxy_ng/tests/unit/migrations/test_0030_update_collection_remote_rhcertified_url.py, galaxy_ng/tests/unit/migrations/test_0048_update_collection_remote_rhcertified_url.py, galaxy_ng/tests/unit/test_models.py, tox.ini, unittest_requirements.txt
=> [stable-4.10] Adding tox

requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt
```
make requirements/pip-upgrade-all
```
=> chore: Bump all pip requirements

.github/workflows/ci-docker-compose-integration.yml, dev/compose/keycloak.yaml
Updated CI test matrix to include LDAP-marked tests and corrected Keycloak API root path to match manager service references.
=> Minor fixes to CI and Keycloak profile

docs/community/devstack.md, docs/usage_guide/installation.md
=> Update docs after removing OCI env

.github/workflows/ci-docker-compose-integration.yml, .github/workflows/ci_automation_hub_collection.yml, Dockerfile.rhel8, Makefile, dev/compose/Dockerfile.dev, dev/compose/aap.yaml, dev/compose/certified-sync.yaml, dev/compose/community.yaml, dev/compose/insights.yaml, dev/compose/signing/setup_repo_keyring.sh, dev/compose/signing/setup_signing_services.sh, dev/compose/standalone.yaml, galaxy_ng/tests/integration/README.md, galaxy_ng/tests/integration/utils/github.py, profiles/community/galaxy-importer/galaxy-importer.cfg
After merging this PR, you might get some permission errors, as volumes might have root owned files.
Cleaning the volumes would fix that
```
docker system prune -a --volumes && docker volume rm $(docker volume ls -qf dangling=true)
```
You might also need to remove some "cache" dirs under galaxy_ng
```
ls -al | grep root
sudo rm -rf <ROOT_OWNED>
```
=> Use galaxy user instead of root

.github/workflows/ci-docker-compose-integration.yml, .github/workflows/ci_automation_hub_collection.yml, Dockerfile.rhel8, Makefile, dev/compose/Dockerfile.dev, dev/compose/aap.yaml, dev/compose/certified-sync.yaml, dev/compose/community.yaml, dev/compose/insights.yaml, dev/compose/keycloak.yaml, dev/compose/ldap.yaml, dev/compose/signing/setup_repo_keyring.sh, dev/compose/signing/setup_signing_services.sh, dev/compose/standalone.yaml, galaxy_ng/tests/integration/utils/github.py, profiles/community/galaxy-importer/galaxy-importer.cfg
(cherry picked from commit aec6a84c59c19649bf92c5bef1844d74a512e14f)
=> [stable-4.9] Use galaxy user instead of root (#2449)

.github/workflows/ci-docker-compose-integration.yml, .github/workflows/ci_automation_hub_collection.yml, Dockerfile.rhel8, MANIFEST.in, Makefile, dev/compose/Dockerfile.dev, dev/compose/aap.yaml, dev/compose/certified-sync.yaml, dev/compose/community.yaml, dev/compose/insights.yaml, dev/compose/signing/setup_repo_keyring.sh, dev/compose/signing/setup_signing_services.sh, dev/compose/standalone.yaml, galaxy_ng/tests/integration/utils/github.py, profiles/community/galaxy-importer/galaxy-importer.cfg, tox.ini
(cherry picked from commit aec6a84c59c19649bf92c5bef1844d74a512e14f)
=> [stable-4.10] Use galaxy user instead of root (#2449)

Dockerfile.rhel8, dev/compose/Dockerfile.dev, dev/compose/Dockerfile.nginx, dev/compose/signing/setup_gpg_keys.sh
Fixes the permission error when setting DEV_SOURCE_PATH
=> Fix docker images

Dockerfile.rhel8, dev/compose/Dockerfile.dev, dev/compose/Dockerfile.nginx, dev/compose/signing/setup_gpg_keys.sh
(cherry picked from commit e62c49b064ced78e7c442d9c5cd0eb3c0b2993a4)
=> [stable-4.9] Fix docker images (#2496)

Dockerfile.rhel8, dev/compose/Dockerfile.dev, dev/compose/Dockerfile.nginx, dev/compose/signing/setup_gpg_keys.sh
(cherry picked from commit e62c49b064ced78e7c442d9c5cd0eb3c0b2993a4)
=> [stable-4.10] Fix docker images (#2496)

Makefile, doc_requirements.txt, requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt
For addressing jinja CVE-2025-27516
Issue: AAP-41699
=> [stable-4.10] Bump requirements

Makefile, docs_requirements.txt, requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt
For addressing jinja CVE-2025-27516
Issue: AAP-41697
=> [stable-4.9] Bump requirements

doc_requirements.txt, docs/index.md, mkdocs.yml
https://github.com/ansible/mkdocs-ansible
=> Use mkdocs-ansible

dev/compose/aap.yaml, dev/compose/certified-sync.yaml, dev/compose/community.yaml, dev/compose/insights.yaml, dev/compose/standalone.yaml
=> Enable cache on docker compose

openshift/clowder/clowd-app.yaml
update postgres to v16 in crc eph
Issue: AAP-43164
=> update postgres to v16 in crc eph

galaxy_ng/app/api/views.py, galaxy_ng/app/dynaconf_hooks.py, galaxy_ng/tests/unit/app/test_dynaconf_hooks.py, profiles/dab/compose.yaml, profiles/dab_jwt/compose.yaml, requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, setup.py
- Use DAB Dynaconf to load DAB reuired settings
- Add a reference to the dynaconf CLI that merges settings from Pulp and DAB
Closes AAP-41686
=> [backport] AAP-37675- DAB Dynaconf (#2420)

dev/compose/aap.yaml, dev/compose/certified-sync.yaml, dev/compose/community.yaml, dev/compose/insights.yaml, dev/compose/standalone.yaml
- Ensure redis is considered on health check
- Add UI link on manager status
=> Minor improvements on dev env

requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, setup.py
Latest DAB includes some bug fixes
* fix(dynamic_config): Warn on PermissionError instead of erroring. by @rochacbruno in https://github.com/ansible/django-ansible-base/pull/704
* AAP-38380: Fix dynaconf handling of spectacular by @bhavenst in https://github.com/ansible/django-ansible-base/pull/705
* AAP-41636 Support extracting the groups claim from `id_token` when using social auth by @markafarrell in https://github.com/ansible/django-ansible-base/pull/682
* AAP-41636 Add configurable group claim and reading groups from backend by @tznamena in https://github.com/ansible/django-ansible-base/pull/708
* Fix the docker-compose serving by @AlanCoding in https://github.com/ansible/django-ansible-base/pull/694
* [AAP-41963] Fix SonarCloud security hotspots by @trucdg in …
=> Bump DAB to the latest upstream release

requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, setup.py
(cherry picked from commit a9dcfbad448e6a957c586aacbdc07ffe77a47be4)
=> [backport] Bump DAB to the latest upstream release (#2549)

galaxy_ng/__init__.py, galaxy_ng/app/__init__.py, pyproject.toml, setup.py
Issue: [AAH-44935](https://issues.redhat.com/browse/AAP-44935)
=> Release 4.10.4

requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, setup.py
Ensuring the sync optimization from https://github.com/pulp/pulp_ansible/blob/main/CHANGES.md#bugfixes--02011-bugfix-
=> [stable-4.9] Bump pulp_ansible

requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, setup.py
Dynaconf 3.2.11 fixes a bug on django templates
https://github.com/dynaconf/dynaconf/pull/1287
=> fix: Bump dynaconf to 3.2.11

dev/compose/Dockerfile.dev, docker/bin/start-api, docker/bin/start-content-app, docker/bin/start-worker
=> Add reload option to docker binaries

dev/compose/Dockerfile.dev, docker/bin/start-api, docker/bin/start-content-app, docker/bin/start-worker
(cherry picked from commit 8f54dd46042db651d56cf8e6c101a6ad2a13c75f)
=> Add reload option to docker binaries (#2567)

galaxy_ng/app/api/ui/v1/serializers/execution_environment.py
closes AAP-43795
https://github.com/pulp/pulp_container/blob/main/pulp_container/app/viewsets.py#L1284-L1291
https://github.com/pulp/pulp_container/blob/main/pulp_container/app/global_access_conditions.py#L86-L90
https://github.com/pulp/pulp_container/blob/main/pulp_container/app/models.py#L827-L834
=> Make ContainerDistribution private

requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, setup.py
=> Bump pulpcore

requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, setup.py
Issue AAP-45056
(cherry picked from commit 3d4d4bb07eb123fd00680239d24d653634b8bd3d)
=> Bump pulpcore (#2577)

dev/compose/Dockerfile.dev, dev/compose/aap.yaml, dev/compose/certified-sync.yaml, dev/compose/community.yaml, dev/compose/insights.yaml, dev/compose/standalone.yaml, docker/bin/start-api, docker/bin/start-content-app, docker/bin/start-worker
https://code.visualstudio.com/docs/containers/debug-python
https://code.visualstudio.com/docs/python/debugging
https://github.com/microsoft/debugpy/wiki/Command-Line-Reference
(cherry picked from commit 983387c2447f7c2b6d6d6294a7f452190e415807)
=> [stable-4.10] Enable vscode debugging (#2588)

Dockerfile.rhel8
rh-pre-commit.version: 2.3.2
rh-pre-commit.check-secrets: ENABLED
=> [stable-4.9] Fix permission error

requirements/requirements.common.txt, requirements/requirements.insights.txt, requirements/requirements.standalone.txt, setup.py
Upstream PR:  (#2598)
Issue: AAP-43138
(cherry picked from commit fcde54d5e0ad46e14b9378181f8d76e5b8eeb143)
=> [stable-4.10] Update to galaxy-importer v0.4.30 for adding ai to required tags list

galaxy_ng/__init__.py, galaxy_ng/app/__init__.py, pyproject.toml, setup.py
Issue: https://issues.redhat.com/browse/AAP-48300
=> Release 4.10.5

.tekton/automation-hub-galaxy-ng-pull-request.yaml, .tekton/automation-hub-galaxy-ng-push.yaml
add the GIT_COMMIT build-arg needed to populate the `galaxy_ng_commit` field in the API response
No-Issue
=> konflux: add galaxy_ng_commit build args

galaxy_ng/app/utils/roles.py, galaxy_ng/tests/unit/app/api/ui/v1/views/test_search.py, galaxy_ng/tests/unit/app/auth/test_keycloak.py, galaxy_ng/tests/unit/app/auth/test_ldap.py, galaxy_ng/tests/unit/app/auth/test_token.py, galaxy_ng/tests/unit/app/metrics_collection/automation_analytics/test_data.py, galaxy_ng/tests/unit/app/test_dynaconf_hooks.py, galaxy_ng/tests/unit/app/test_pipelines.py, galaxy_ng/tests/unit/app/utils/test_galaxy.py, galaxy_ng/tests/unit/app/utils/test_legacy.py, galaxy_ng/tests/unit/app/utils/test_roles.py
=> Improve test coverage
